import Image from "next/image";
import Link from "next/link";
import { localizePath } from "@/lib/i18n";
import { getPageLocale, type LocalePageProps } from "@/lib/localePage";
import { getIntroCallUrl } from "@/lib/marketingLinks";
import { createPageMetadata } from "@/lib/metadata";

const COPY = {
  en: {
    meta: { title: "Selected work", socialTitle: "Selected product work · MaydaLabs", description: "Selected MaydaLabs product work, including HodlStay and Satoshi Gazette." },
    kicker: "Selected work / Built, not rendered", heading: ["Two products.", "One point of view."], intro: "The strongest proof is software you can open. These projects show how MaydaLabs moves between consumer experience, complex operations, editorial systems, and growth.", engagement: "Engagement", full: "Open full case study", visit: "Visit", challenge: "The challenge", built: "The system we built", stack: "Core stack", inside: "Inside the product", galleryHeading: "A marketplace is more than its landing page.", proofKicker: "The system behind the screen", proofHeading: "Four hard problems, connected.", availability: "Open for new client work", cta: "Let’s build the proof.", start: "Start a project",
    cases: [
      { id: "hodlstay", number: "01", name: "HodlStay", category: "Marketplace · Travel · Bitcoin", title: "A global stay marketplace, rebuilt around a sharper product idea.", summary: "HodlStay evolved from AirBTC into a premium travel product with Bitcoin-friendly booking built in. The work spans public discovery, host operations, guest journeys, legacy-data migration, partner inventory, payments, and the brand system around it.", engagement: "End-to-end client product build, prepared for handover on completion.", challenge: "Turn a promising niche platform into a credible, scalable marketplace without losing the community and Bitcoin roots that made it distinct.", built: ["Unified marketplace discovery and stay dossiers", "Host onboarding, listing, calendar, and payout operations", "Booking, availability, review, and payment lifecycles", "AirBTC to HodlStay product and brand evolution", "Conference accommodation and partner inventory flows"], stack: ["Next.js", "React", "Supabase", "BTCPay", "Resend", "Vercel"], image: "/work/hodlstay-home.png", width: 1270, height: 714, alt: "HodlStay global booking marketplace", status: "Client project · Live", domain: "hodlstay.com", url: "https://hodlstay.com", gallery: [["/work/hodlstay-stays.png", "HodlStay stay discovery and search interface", "Discovery", "Category-led search, dates, guests, filters, and live inventory."], ["/work/hodlstay-listing.png", "HodlStay property dossier and booking interface", "Stay dossier", "Property story, media, host context, fiat and sats pricing, and booking entry."], ["/work/hodlstay-conferences.png", "HodlStay conference accommodation interface", "Conference product", "Dedicated accommodation paths for events, attendees, organizers, and hosts."]], proof: [["01", "Unified discovery", "One search layer can present native HodlStay inventory alongside eligible HotelPlanner and Dtravel partner supply."], ["02", "Availability safety", "Imported iCal blocks, manual host blocks, and internal bookings are checked together to reduce double-booking risk."], ["03", "Bitcoin payment lifecycle", "Host acceptance leads into BTCPay checkout, signed webhook verification, booking settlement, and a traceable payout record."], ["04", "Operational migration", "Legacy WordPress and founder spreadsheet records are reconciled into a structured launch pipeline with explicit exception handling."]] },
      { id: "satoshi-gazette", number: "02", name: "Satoshi Gazette", category: "Media · Data · AI-assisted operations", title: "A Bitcoin newsroom designed as an information product.", summary: "Satoshi Gazette combines a live market layer, structured editorial desks, long-form reporting, wire updates, and briefings. The live product is in an active build phase as the newsroom and publishing workflows are brought to showcase level.", engagement: "", challenge: "Build a publication that feels authoritative and editorial while the operating system behind it stays fast, structured, and ready for responsible AI assistance.", built: ["Editorial information architecture and visual system", "Market, mining, policy, wire, and briefing surfaces", "Publishing workflows and internal newsroom tooling", "Live Bitcoin market and network context", "AI-assisted research and production foundations"], stack: ["Next.js", "React", "Supabase", "Editorial CMS", "Market data", "AI workflows"], image: "/work/satoshi-gazette-live-home.png", width: 1440, height: 900, alt: "Satoshi Gazette Bitcoin newsroom", status: "Live · Active build", domain: "satoshigazette.org", url: "https://satoshigazette.org", gallery: [], proof: [] },
    ],
  },
  tr: {
    meta: { title: "Seçili projeler", socialTitle: "Seçili ürün projeleri · MaydaLabs", description: "HodlStay ve Satoshi Gazette dahil seçili MaydaLabs ürün projeleri." },
    kicker: "Seçili projeler / Render değil, çalışan ürün", heading: ["İki ürün.", "Tek bakış açısı."], intro: "En güçlü kanıt açıp kullanabileceğiniz yazılımdır. Bu projeler MaydaLabs'in tüketici deneyimi, karmaşık operasyonlar, editoryal sistemler ve büyüme arasında nasıl hareket ettiğini gösteriyor.", engagement: "Çalışma", full: "Tam vaka çalışmasını aç", visit: "Ziyaret et", challenge: "Problem", built: "Geliştirdiğimiz sistem", stack: "Temel teknoloji", inside: "Ürünün içinden", galleryHeading: "Bir pazar yeri açılış sayfasından fazlasıdır.", proofKicker: "Ekranın arkasındaki sistem", proofHeading: "Birbirine bağlı dört zor problem.", availability: "Yeni müşteri projelerine açık", cta: "Kanıtı birlikte geliştirelim.", start: "Proje başlat",
    cases: [
      { id: "hodlstay", number: "01", name: "HodlStay", category: "Pazar yeri · Seyahat · Bitcoin", title: "Daha keskin bir ürün fikri etrafında yeniden kurulan küresel konaklama pazarı.", summary: "HodlStay, AirBTC’den Bitcoin dostu rezervasyonu deneyime yerleştiren premium bir seyahat ürününe dönüştü. Çalışma; keşif, ev sahibi operasyonları, misafir yolculukları, eski veri göçü, iş ortağı envanteri, ödemeler ve marka sistemini kapsıyor.", engagement: "Tam kapsamlı müşteri ürünü geliştirmesi; tamamlandığında devre hazır.", challenge: "Topluluğu ve Bitcoin köklerini kaybetmeden umut vadeden niş platformu güven veren, ölçeklenebilir bir pazar yerine dönüştürmek.", built: ["Birleşik pazar yeri keşfi ve konaklama dosyaları", "Ev sahibi katılımı, ilan, takvim ve ödeme operasyonları", "Rezervasyon, uygunluk, yorum ve ödeme yaşam döngüleri", "AirBTC’den HodlStay’e ürün ve marka dönüşümü", "Konferans konaklaması ve iş ortağı envanter akışları"], stack: ["Next.js", "React", "Supabase", "BTCPay", "Resend", "Vercel"], image: "/work/hodlstay-home.png", width: 1270, height: 714, alt: "HodlStay küresel rezervasyon pazarı", status: "Müşteri projesi · Canlı", domain: "hodlstay.com", url: "https://hodlstay.com", gallery: [["/work/hodlstay-stays.png", "HodlStay konaklama keşfi ve arama arayüzü", "Keşif", "Kategori odaklı arama, tarihler, misafirler, filtreler ve canlı envanter."], ["/work/hodlstay-listing.png", "HodlStay konaklama dosyası ve rezervasyon arayüzü", "Konaklama dosyası", "Mülk hikâyesi, medya, ev sahibi bağlamı, fiat ve sats fiyatlandırması ve rezervasyon girişi."], ["/work/hodlstay-conferences.png", "HodlStay konferans konaklama arayüzü", "Konferans ürünü", "Etkinlikler, katılımcılar, organizatörler ve ev sahipleri için özel konaklama yolları."]], proof: [["01", "Birleşik keşif", "Tek arama katmanı yerel HodlStay envanteriyle uygun HotelPlanner ve Dtravel iş ortağı arzını birlikte sunabilir."], ["02", "Uygunluk güvenliği", "İçe aktarılan iCal blokları, manuel ev sahibi blokları ve dahili rezervasyonlar çifte rezervasyon riskini azaltmak için birlikte kontrol edilir."], ["03", "Bitcoin ödeme yaşam döngüsü", "Ev sahibi kabulü; BTCPay ödeme, imzalı webhook doğrulaması, rezervasyon mutabakatı ve izlenebilir ödeme kaydına bağlanır."], ["04", "Operasyonel veri göçü", "Eski WordPress ve kurucu tablo kayıtları açık istisna yönetimiyle yapılandırılmış lansman hattına dönüştürülür."]] },
      { id: "satoshi-gazette", number: "02", name: "Satoshi Gazette", category: "Medya · Veri · Yapay zekâ destekli operasyon", title: "Bilgi ürünü olarak tasarlanmış bir Bitcoin haber merkezi.", summary: "Satoshi Gazette; canlı piyasa katmanı, yapılandırılmış editoryal masalar, uzun haberler, Wire güncellemeleri ve bültenleri birleştiriyor. Haber merkezi ve yayın akışları vitrin seviyesine taşınırken canlı ürün aktif geliştirme aşamasında.", engagement: "", challenge: "Arka plandaki işletim sistemi hızlı, yapılandırılmış ve sorumlu yapay zekâ desteğine hazır kalırken otoriter ve editoryal hissettiren bir yayın kurmak.", built: ["Editoryal bilgi mimarisi ve görsel sistem", "Piyasa, madencilik, politika, Wire ve bülten yüzeyleri", "Yayın akışları ve dahili haber merkezi araçları", "Canlı Bitcoin piyasa ve ağ bağlamı", "Yapay zekâ destekli araştırma ve üretim temelleri"], stack: ["Next.js", "React", "Supabase", "Editoryal CMS", "Piyasa verisi", "Yapay zekâ akışları"], image: "/work/satoshi-gazette-live-home.png", width: 1440, height: 900, alt: "Satoshi Gazette Bitcoin haber merkezi", status: "Canlı · Aktif geliştirme", domain: "satoshigazette.org", url: "https://satoshigazette.org", gallery: [], proof: [] },
    ],
  },
  fr: {
    meta: { title: "Projets sélectionnés", socialTitle: "Projets produit sélectionnés · MaydaLabs", description: "Une sélection de projets MaydaLabs, dont HodlStay et Satoshi Gazette." },
    kicker: "Projets sélectionnés / Construits, pas rendus", heading: ["Deux produits.", "Un seul point de vue."], intro: "La meilleure preuve est un logiciel que l’on peut ouvrir. Ces projets montrent comment MaydaLabs relie expérience client, opérations complexes, systèmes éditoriaux et croissance.", engagement: "Mission", full: "Ouvrir l’étude de cas", visit: "Visiter", challenge: "Le défi", built: "Le système construit", stack: "Technologies clés", inside: "Dans le produit", galleryHeading: "Une marketplace dépasse sa landing page.", proofKicker: "Le système derrière l’écran", proofHeading: "Quatre problèmes difficiles, connectés.", availability: "Ouvert à de nouveaux projets clients", cta: "Construisons la preuve.", start: "Lancer un projet",
    cases: [
      { id: "hodlstay", number: "01", name: "HodlStay", category: "Marketplace · Voyage · Bitcoin", title: "Une marketplace mondiale de séjours reconstruite autour d’une idée plus forte.", summary: "HodlStay a évolué d’AirBTC vers un produit de voyage premium intégrant la réservation compatible Bitcoin. Le travail couvre découverte, opérations hôtes, parcours voyageurs, migration, inventaire partenaire, paiements et système de marque.", engagement: "Construction produit client de bout en bout, préparée pour transmission.", challenge: "Transformer une plateforme de niche prometteuse en marketplace crédible et évolutive sans perdre la communauté et les racines Bitcoin qui la distinguent.", built: ["Découverte unifiée et dossiers de séjour", "Intégration hôtes, annonces, calendriers et versements", "Cycles de réservation, disponibilité, avis et paiement", "Évolution produit et marque d’AirBTC à HodlStay", "Hébergement de conférences et inventaire partenaire"], stack: ["Next.js", "React", "Supabase", "BTCPay", "Resend", "Vercel"], image: "/work/hodlstay-home.png", width: 1270, height: 714, alt: "Marketplace mondiale de réservation HodlStay", status: "Projet client · En ligne", domain: "hodlstay.com", url: "https://hodlstay.com", gallery: [["/work/hodlstay-stays.png", "Interface de découverte et recherche HodlStay", "Découverte", "Recherche par catégorie, dates, voyageurs, filtres et inventaire en direct."], ["/work/hodlstay-listing.png", "Dossier de propriété et réservation HodlStay", "Dossier de séjour", "Histoire du lieu, médias, contexte hôte, prix fiat et sats et entrée de réservation."], ["/work/hodlstay-conferences.png", "Interface d’hébergement conférence HodlStay", "Produit conférence", "Parcours dédiés aux événements, participants, organisateurs et hôtes."]], proof: [["01", "Découverte unifiée", "Une seule couche de recherche présente l’inventaire HodlStay et les offres partenaires HotelPlanner et Dtravel éligibles."], ["02", "Sécurité de disponibilité", "Blocs iCal importés, blocages manuels et réservations internes sont vérifiés ensemble pour réduire les doubles réservations."], ["03", "Cycle de paiement Bitcoin", "L’acceptation hôte mène au checkout BTCPay, à la vérification webhook, au règlement et à un versement traçable."], ["04", "Migration opérationnelle", "Les données WordPress et feuilles fondateur sont réconciliées dans un pipeline de lancement structuré avec gestion explicite des exceptions."]] },
      { id: "satoshi-gazette", number: "02", name: "Satoshi Gazette", category: "Média · Données · Opérations assistées par IA", title: "Une rédaction Bitcoin conçue comme un produit d’information.", summary: "Satoshi Gazette réunit marché en direct, rubriques éditoriales, reportages longs, fil Wire et briefings. Le produit est en construction active pendant que rédaction et workflows de publication atteignent leur niveau vitrine.", engagement: "", challenge: "Construire une publication éditoriale et crédible tout en gardant son système d’exploitation rapide, structuré et prêt pour une assistance IA responsable.", built: ["Architecture de l’information et système visuel", "Marché, minage, politique, Wire et briefings", "Workflows de publication et outils internes", "Contexte marché et réseau Bitcoin en direct", "Fondations de recherche et production assistées par IA"], stack: ["Next.js", "React", "Supabase", "CMS éditorial", "Données marché", "Workflows IA"], image: "/work/satoshi-gazette-live-home.png", width: 1440, height: 900, alt: "Rédaction Bitcoin Satoshi Gazette", status: "En ligne · Construction active", domain: "satoshigazette.org", url: "https://satoshigazette.org", gallery: [], proof: [] },
    ],
  },
} as const;

export async function generateMetadata({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  return createPageMetadata({ ...COPY[locale].meta, path: "/case-studies", locale, socialCard: "work" });
}

function Arrow() { return <span aria-hidden>↗</span>; }

export default async function CaseStudiesPage({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  const copy = COPY[locale];
  return (
    <div className="studio-inner-page">
      <section className="studio-inner-hero"><p className="studio-kicker">{copy.kicker}</p><h1>{copy.heading[0]}<br /><em>{copy.heading[1]}</em></h1><p>{copy.intro}</p></section>
      {copy.cases.map((item) => (
        <article id={item.id} key={item.id} className="case-detail scroll-mt-28">
          <div className="case-detail-heading"><p>{item.number} / {item.name}</p><span>{item.category}</span></div>
          <div className="case-detail-title"><h2>{item.title}</h2><div><p>{item.summary}</p>{item.engagement ? <p className="case-detail-engagement"><span>{copy.engagement}</span>{item.engagement}</p> : null}<div className="case-detail-links"><Link href={localizePath(`/case-studies/${item.id}`, locale)} className="studio-text-link">{copy.full} <Arrow /></Link><a href={item.url} target="_blank" rel="noopener noreferrer" className="studio-text-link">{copy.visit} {item.domain} <Arrow /></a></div></div></div>
          <div className="case-detail-screen"><div className="project-browser-chrome"><div><i /><i /><i /></div><span>{item.domain}</span><b>{item.status}</b></div><Image src={item.image} alt={item.alt} width={item.width} height={item.height} sizes="(max-width: 900px) 100vw, 90vw" /></div>
          <div className="case-detail-grid"><section><p className="studio-kicker">{copy.challenge}</p><p>{item.challenge}</p></section><section><p className="studio-kicker">{copy.built}</p><ul>{item.built.map((entry) => <li key={entry}>{entry}</li>)}</ul></section><section><p className="studio-kicker">{copy.stack}</p><div>{item.stack.map((entry) => <span key={entry}>{entry}</span>)}</div></section></div>
          {item.gallery.length ? <section className="case-gallery" aria-label={`${item.name} product gallery`}><div className="case-subheading"><p className="studio-kicker">{copy.inside}</p><h3>{copy.galleryHeading}</h3></div><div className="case-gallery-grid">{item.gallery.map(([src, alt, label, detail]) => <figure key={src}><div className="case-gallery-frame"><Image src={src} alt={alt} width={1270} height={714} sizes="(max-width: 900px) 100vw, 72vw" /></div><figcaption><strong>{label}</strong><span>{detail}</span></figcaption></figure>)}</div></section> : null}
          {item.proof.length ? <section className="case-proof"><div className="case-subheading"><p className="studio-kicker">{copy.proofKicker}</p><h3>{copy.proofHeading}</h3></div><div className="case-proof-grid">{item.proof.map(([number, title, description]) => <article key={number}><span>{number}</span><h4>{title}</h4><p>{description}</p></article>)}</div></section> : null}
        </article>
      ))}
      <section className="studio-inner-cta"><p className="studio-kicker">{copy.availability}</p><h2>{copy.cta}</h2><Link href={getIntroCallUrl("work_bottom")} target="_blank" rel="noopener noreferrer" className="studio-button">{copy.start} <Arrow /></Link></section>
    </div>
  );
}
