import Image from "next/image";
import Link from "next/link";
import { InProgressVisual } from "@/components/InProgressVisual";
import { localizePath } from "@/lib/i18n";
import { getPageLocale, type LocalePageProps } from "@/lib/localePage";
import { getIntroCallUrl } from "@/lib/marketingLinks";
import { createPageMetadata } from "@/lib/metadata";

const COPY = {
  en: {
    meta: { title: "Selected work", socialTitle: "Selected product work · MaydaLabs", description: "Four MaydaLabs product cases: live HodlStay and Satoshi Gazette work, plus Mortal Vault and Sofra in active private development." },
    kicker: "Selected work / Evidence with status", heading: ["Four products.", "One point of view."], intro: "Two products are live and open to inspect. Two are private working builds with their current boundaries stated plainly. Together they show product, engineering, operations, and growth as one connected discipline.", engagement: "Engagement", full: "Open full case study", visit: "Visit", private: "No public release yet", challenge: "The challenge", built: "The system we built", stack: "Core stack", inside: "Inside the product", galleryHeading: "A marketplace is more than its landing page.", proofKicker: "The system behind the screen", proofHeading: "Four hard problems, connected.", availability: "Open for new client work", cta: "Let’s build the proof.", start: "Start a project",
    cases: [
      { id: "hodlstay", number: "01", name: "HodlStay", category: "Marketplace · Travel · Bitcoin", title: "A global stay marketplace, rebuilt around a sharper product idea.", summary: "HodlStay evolved from AirBTC into a premium travel product with Bitcoin-friendly booking built in. The current live product connects category-led stay discovery, detailed stay dossiers, conference travel, host operations, and the systems behind each journey.", engagement: "End-to-end client product build, prepared for handover on completion.", challenge: "Turn a promising niche platform into a credible, scalable marketplace without losing the community and Bitcoin roots that made it distinct.", built: ["Unified marketplace discovery and current stay dossiers", "Host onboarding, listing, calendar, and payout operations", "Booking, availability, review, and payment lifecycles", "AirBTC to HodlStay product and brand evolution", "Dedicated conference accommodation product"], stack: ["Next.js", "React", "Supabase", "BTCPay", "Resend", "Vercel"], image: "/work/hodlstay-2026-08-home.png", width: 1440, height: 900, alt: "Current HodlStay global booking marketplace", status: "Client project · Live", domain: "hodlstay.com", url: "https://hodlstay.com", gallery: [["/work/hodlstay-2026-08-stays.png", "Current HodlStay stay discovery and search interface", "Discovery", "Category-led search, dates, guests, filters, and current public inventory."], ["/work/hodlstay-2026-08-listing.png", "Current HodlStay stay dossier and booking interface", "Stay dossier", "Property story, media, host context, pricing, and booking entry."], ["/work/hodlstay-2026-08-conferences.png", "Current HodlStay conference accommodation interface", "Conference product", "A dedicated event accommodation journey for attendees, organizers, and hosts."]], proof: [["01", "Unified discovery", "One search layer presents a coherent discovery experience across the marketplace’s eligible inventory."], ["02", "Availability safety", "Imported calendar blocks, manual host blocks, and internal bookings are checked together to reduce double-booking risk."], ["03", "Bitcoin payment lifecycle", "Host acceptance connects to BTCPay checkout, signed webhook verification, booking settlement, and a traceable payout record."], ["04", "Operational migration", "Legacy WordPress and founder spreadsheet records are reconciled into a structured launch pipeline with explicit exception handling."]] },
      { id: "satoshi-gazette", number: "02", name: "Satoshi Gazette", category: "Media · Data · AI-assisted operations", title: "A Bitcoin newsroom designed as an information product.", summary: "Satoshi Gazette now combines populated editorial desks, long-form stories, current Wire updates, briefings, live market context, and a primary-evidence Data Desk. The public newsroom is live while the operating system continues to evolve behind it.", engagement: "", challenge: "Build a publication that feels authoritative and editorial while the operating system behind it stays fast, structured, and ready for responsible AI assistance.", built: ["Editorial information architecture and visual system", "Current story, Wire, briefing, and Data Desk surfaces", "Publishing workflows and internal newsroom tooling", "Live Bitcoin market and network context", "Guarded retrieval and AI-assisted production foundations"], stack: ["Next.js", "React", "Supabase", "Editorial CMS", "Market data", "AI workflows"], image: "/work/satoshi-gazette-2026-08-home.png", width: 1440, height: 900, alt: "Current Satoshi Gazette Bitcoin newsroom", status: "Live · Active build", domain: "satoshigazette.org", url: "https://satoshigazette.org", gallery: [], proof: [] },
    ],
    developmentCases: [
      { id: "mortal-vault", variant: "mortal", number: "03", name: "Mortal Vault", category: "Crypto · Self-custody · Continuity", title: "A continuity vault engineered around explicit time, role, and risk boundaries.", summary: "Mortal Vault is a private alpha for owner check-ins and delayed beneficiary claims. The current repository includes a bounded Solidity lifecycle, owner and beneficiary interfaces, event-backed history, reminder planning, and security testing.", engagement: "MaydaLabs product · Active private development.", challenge: "Make a high-consequence self-custody lifecycle understandable without hiding the irreversible risks or implying legal and security guarantees the product cannot make.", built: ["Owner and beneficiary contract lifecycle", "Delayed claim with owner challenge window", "Event-backed activity and deterministic reminder rules", "Adversarial, fuzz, invariant, and static-analysis gates", "Testnet-first network and release configuration"], stack: ["Solidity", "Hardhat", "Next.js", "ethers", "EVM testnets", "Security testing"], status: "Private alpha · Unaudited" },
      { id: "sofra", variant: "sofra", number: "04", name: "Sofra", category: "Marketplace · Hospitality · Trust", title: "A managed household dinner marketplace where trust is part of the product model.", summary: "Sofra is a private Türkiye-first Phase 1 product for scheduled dinners in verified households. It connects bilingual guest, host, and operator journeys while protecting exact household, dietary, assessment, and safety data.", engagement: "MaydaLabs product · Active private development.", challenge: "Design a warm consumer experience on top of a rigorous approval, privacy, booking, incident, and operating model—without exposing the household behind the table.", built: ["Public table discovery and guest journeys", "Host application and managed approval lifecycle", "Operator, booking, pricing, and incident surfaces", "Explicit public/private data projections", "English and Turkish product architecture"], stack: ["Next.js", "TypeScript", "Supabase", "next-intl", "Vitest", "Playwright"], status: "Private Phase 1 · Demo-safe" },
    ],
  },
  tr: {
    meta: { title: "Seçili projeler", socialTitle: "Seçili ürün projeleri · MaydaLabs", description: "Canlı HodlStay ve Satoshi Gazette ile aktif özel geliştirmedeki Mortal Vault ve Sofra'yı kapsayan dört MaydaLabs ürün vakası." },
    kicker: "Seçili projeler / Durumuyla birlikte kanıt", heading: ["Dört ürün.", "Tek bakış açısı."], intro: "İki ürün canlı ve incelenebilir. İki özel çalışan ürün ise mevcut sınırları açıkça belirtilerek sunuluyor. Birlikte ürün, mühendislik, operasyon ve büyümeyi bağlı tek disiplin olarak gösteriyorlar.", engagement: "Çalışma", full: "Tam vaka çalışmasını aç", visit: "Ziyaret et", private: "Henüz açık sürüm yok", challenge: "Problem", built: "Geliştirdiğimiz sistem", stack: "Temel teknoloji", inside: "Ürünün içinden", galleryHeading: "Bir pazar yeri açılış sayfasından fazlasıdır.", proofKicker: "Ekranın arkasındaki sistem", proofHeading: "Birbirine bağlı dört zor problem.", availability: "Yeni müşteri projelerine açık", cta: "Kanıtı birlikte geliştirelim.", start: "Proje başlat",
    cases: [
      { id: "hodlstay", number: "01", name: "HodlStay", category: "Pazar yeri · Seyahat · Bitcoin", title: "Daha keskin bir ürün fikri etrafında yeniden kurulan küresel konaklama pazarı.", summary: "HodlStay, AirBTC’den Bitcoin dostu rezervasyonu deneyime yerleştiren premium bir seyahat ürününe dönüştü. Çalışma; keşif, ev sahibi operasyonları, misafir yolculukları, eski veri göçü, iş ortağı envanteri, ödemeler ve marka sistemini kapsıyor.", engagement: "Tam kapsamlı müşteri ürünü geliştirmesi; tamamlandığında devre hazır.", challenge: "Topluluğu ve Bitcoin köklerini kaybetmeden umut vadeden niş platformu güven veren, ölçeklenebilir bir pazar yerine dönüştürmek.", built: ["Birleşik pazar yeri keşfi ve konaklama dosyaları", "Ev sahibi katılımı, ilan, takvim ve ödeme operasyonları", "Rezervasyon, uygunluk, yorum ve ödeme yaşam döngüleri", "AirBTC’den HodlStay’e ürün ve marka dönüşümü", "Konferans konaklaması ve iş ortağı envanter akışları"], stack: ["Next.js", "React", "Supabase", "BTCPay", "Resend", "Vercel"], image: "/work/hodlstay-home.png", width: 1270, height: 714, alt: "HodlStay küresel rezervasyon pazarı", status: "Müşteri projesi · Canlı", domain: "hodlstay.com", url: "https://hodlstay.com", gallery: [["/work/hodlstay-stays.png", "HodlStay konaklama keşfi ve arama arayüzü", "Keşif", "Kategori odaklı arama, tarihler, misafirler, filtreler ve canlı envanter."], ["/work/hodlstay-listing.png", "HodlStay konaklama dosyası ve rezervasyon arayüzü", "Konaklama dosyası", "Mülk hikâyesi, medya, ev sahibi bağlamı, fiat ve sats fiyatlandırması ve rezervasyon girişi."], ["/work/hodlstay-conferences.png", "HodlStay konferans konaklama arayüzü", "Konferans ürünü", "Etkinlikler, katılımcılar, organizatörler ve ev sahipleri için özel konaklama yolları."]], proof: [["01", "Birleşik keşif", "Tek arama katmanı yerel HodlStay envanteriyle uygun HotelPlanner ve Dtravel iş ortağı arzını birlikte sunabilir."], ["02", "Uygunluk güvenliği", "İçe aktarılan iCal blokları, manuel ev sahibi blokları ve dahili rezervasyonlar çifte rezervasyon riskini azaltmak için birlikte kontrol edilir."], ["03", "Bitcoin ödeme yaşam döngüsü", "Ev sahibi kabulü; BTCPay ödeme, imzalı webhook doğrulaması, rezervasyon mutabakatı ve izlenebilir ödeme kaydına bağlanır."], ["04", "Operasyonel veri göçü", "Eski WordPress ve kurucu tablo kayıtları açık istisna yönetimiyle yapılandırılmış lansman hattına dönüştürülür."]] },
      { id: "satoshi-gazette", number: "02", name: "Satoshi Gazette", category: "Medya · Veri · Yapay zekâ destekli operasyon", title: "Bilgi ürünü olarak tasarlanmış bir Bitcoin haber merkezi.", summary: "Satoshi Gazette; canlı piyasa katmanı, yapılandırılmış editoryal masalar, uzun haberler, Wire güncellemeleri ve bültenleri birleştiriyor. Haber merkezi ve yayın akışları vitrin seviyesine taşınırken canlı ürün aktif geliştirme aşamasında.", engagement: "", challenge: "Arka plandaki işletim sistemi hızlı, yapılandırılmış ve sorumlu yapay zekâ desteğine hazır kalırken otoriter ve editoryal hissettiren bir yayın kurmak.", built: ["Editoryal bilgi mimarisi ve görsel sistem", "Piyasa, madencilik, politika, Wire ve bülten yüzeyleri", "Yayın akışları ve dahili haber merkezi araçları", "Canlı Bitcoin piyasa ve ağ bağlamı", "Yapay zekâ destekli araştırma ve üretim temelleri"], stack: ["Next.js", "React", "Supabase", "Editoryal CMS", "Piyasa verisi", "Yapay zekâ akışları"], image: "/work/satoshi-gazette-live-home.png", width: 1440, height: 900, alt: "Satoshi Gazette Bitcoin haber merkezi", status: "Canlı · Aktif geliştirme", domain: "satoshigazette.org", url: "https://satoshigazette.org", gallery: [], proof: [] },
    ],
    developmentCases: [
      { id: "mortal-vault", variant: "mortal", number: "03", name: "Mortal Vault", category: "Kripto · Self-custody · Süreklilik", title: "Açık zaman, rol ve risk sınırları etrafında geliştirilen süreklilik kasası.", summary: "Mortal Vault, sahip check-in'leri ve gecikmeli lehtar talepleri için özel alpha üründür. Mevcut repository sınırlı Solidity yaşam döngüsü, sahip ve lehtar arayüzleri, event tabanlı geçmiş, hatırlatma planı ve güvenlik testleri içerir.", engagement: "MaydaLabs ürünü · Aktif özel geliştirme.", challenge: "Yüksek sonuçlu bir self-custody yaşam döngüsünü geri döndürülemez riskleri gizlemeden ve hukuki ya da güvenlik garantisi ima etmeden anlaşılır kılmak.", built: ["Sahip ve lehtar sözleşme yaşam döngüsü", "Sahip itiraz pencereli gecikmeli talep", "Event tabanlı aktivite ve deterministik hatırlatmalar", "Adversarial, fuzz, invariant ve statik analiz kapıları", "Testnet öncelikli ağ ve sürüm yapılandırması"], stack: ["Solidity", "Hardhat", "Next.js", "ethers", "EVM testnetleri", "Güvenlik testleri"], status: "Özel alpha · Denetlenmedi" },
      { id: "sofra", variant: "sofra", number: "04", name: "Sofra", category: "Pazar yeri · Ağırlama · Güven", title: "Güvenin ürün modelinin parçası olduğu yönetilen ev yemeği pazarı.", summary: "Sofra, doğrulanmış hanelerde planlı akşam yemekleri için Türkiye odaklı özel Phase 1 üründür. Tam hane, beslenme, değerlendirme ve güvenlik verilerini korurken iki dilli misafir, ev sahibi ve operatör yolculuklarını bağlar.", engagement: "MaydaLabs ürünü · Aktif özel geliştirme.", challenge: "Sofranın arkasındaki haneyi açığa çıkarmadan sıcak tüketici deneyimini disiplinli onay, gizlilik, rezervasyon, olay ve işletim modeli üzerine kurmak.", built: ["Açık sofra keşfi ve misafir yolculukları", "Ev sahibi başvurusu ve yönetilen onay yaşam döngüsü", "Operatör, rezervasyon, fiyat ve olay yüzeyleri", "Açık/özel veri projeksiyonları", "İngilizce ve Türkçe ürün mimarisi"], stack: ["Next.js", "TypeScript", "Supabase", "next-intl", "Vitest", "Playwright"], status: "Özel Phase 1 · Demo güvenli" },
    ],
  },
  fr: {
    meta: { title: "Projets sélectionnés", socialTitle: "Projets produit sélectionnés · MaydaLabs", description: "Quatre cas MaydaLabs : HodlStay et Satoshi Gazette en ligne, Mortal Vault et Sofra en construction privée." },
    kicker: "Projets sélectionnés / Preuve et statut", heading: ["Quatre produits.", "Un seul point de vue."], intro: "Deux produits sont en ligne et ouverts à l’inspection. Deux constructions privées affichent clairement leurs limites actuelles. Ensemble, ils relient produit, ingénierie, opérations et croissance.", engagement: "Mission", full: "Ouvrir l’étude de cas", visit: "Visiter", private: "Aucune sortie publique", challenge: "Le défi", built: "Le système construit", stack: "Technologies clés", inside: "Dans le produit", galleryHeading: "Une marketplace dépasse sa landing page.", proofKicker: "Le système derrière l’écran", proofHeading: "Quatre problèmes difficiles, connectés.", availability: "Ouvert à de nouveaux projets clients", cta: "Construisons la preuve.", start: "Lancer un projet",
    cases: [
      { id: "hodlstay", number: "01", name: "HodlStay", category: "Marketplace · Voyage · Bitcoin", title: "Une marketplace mondiale de séjours reconstruite autour d’une idée plus forte.", summary: "HodlStay a évolué d’AirBTC vers un produit de voyage premium intégrant la réservation compatible Bitcoin. Le travail couvre découverte, opérations hôtes, parcours voyageurs, migration, inventaire partenaire, paiements et système de marque.", engagement: "Construction produit client de bout en bout, préparée pour transmission.", challenge: "Transformer une plateforme de niche prometteuse en marketplace crédible et évolutive sans perdre la communauté et les racines Bitcoin qui la distinguent.", built: ["Découverte unifiée et dossiers de séjour", "Intégration hôtes, annonces, calendriers et versements", "Cycles de réservation, disponibilité, avis et paiement", "Évolution produit et marque d’AirBTC à HodlStay", "Hébergement de conférences et inventaire partenaire"], stack: ["Next.js", "React", "Supabase", "BTCPay", "Resend", "Vercel"], image: "/work/hodlstay-home.png", width: 1270, height: 714, alt: "Marketplace mondiale de réservation HodlStay", status: "Projet client · En ligne", domain: "hodlstay.com", url: "https://hodlstay.com", gallery: [["/work/hodlstay-stays.png", "Interface de découverte et recherche HodlStay", "Découverte", "Recherche par catégorie, dates, voyageurs, filtres et inventaire en direct."], ["/work/hodlstay-listing.png", "Dossier de propriété et réservation HodlStay", "Dossier de séjour", "Histoire du lieu, médias, contexte hôte, prix fiat et sats et entrée de réservation."], ["/work/hodlstay-conferences.png", "Interface d’hébergement conférence HodlStay", "Produit conférence", "Parcours dédiés aux événements, participants, organisateurs et hôtes."]], proof: [["01", "Découverte unifiée", "Une seule couche de recherche présente l’inventaire HodlStay et les offres partenaires HotelPlanner et Dtravel éligibles."], ["02", "Sécurité de disponibilité", "Blocs iCal importés, blocages manuels et réservations internes sont vérifiés ensemble pour réduire les doubles réservations."], ["03", "Cycle de paiement Bitcoin", "L’acceptation hôte mène au checkout BTCPay, à la vérification webhook, au règlement et à un versement traçable."], ["04", "Migration opérationnelle", "Les données WordPress et feuilles fondateur sont réconciliées dans un pipeline de lancement structuré avec gestion explicite des exceptions."]] },
      { id: "satoshi-gazette", number: "02", name: "Satoshi Gazette", category: "Média · Données · Opérations assistées par IA", title: "Une rédaction Bitcoin conçue comme un produit d’information.", summary: "Satoshi Gazette réunit marché en direct, rubriques éditoriales, reportages longs, fil Wire et briefings. Le produit est en construction active pendant que rédaction et workflows de publication atteignent leur niveau vitrine.", engagement: "", challenge: "Construire une publication éditoriale et crédible tout en gardant son système d’exploitation rapide, structuré et prêt pour une assistance IA responsable.", built: ["Architecture de l’information et système visuel", "Marché, minage, politique, Wire et briefings", "Workflows de publication et outils internes", "Contexte marché et réseau Bitcoin en direct", "Fondations de recherche et production assistées par IA"], stack: ["Next.js", "React", "Supabase", "CMS éditorial", "Données marché", "Workflows IA"], image: "/work/satoshi-gazette-live-home.png", width: 1440, height: 900, alt: "Rédaction Bitcoin Satoshi Gazette", status: "En ligne · Construction active", domain: "satoshigazette.org", url: "https://satoshigazette.org", gallery: [], proof: [] },
    ],
    developmentCases: [
      { id: "mortal-vault", variant: "mortal", number: "03", name: "Mortal Vault", category: "Crypto · Autogarde · Continuité", title: "Un coffre de continuité conçu autour de limites explicites de temps, rôle et risque.", summary: "Mortal Vault est une alpha privée pour les check-ins et réclamations différées. Le dépôt comprend cycle Solidity borné, interfaces, historique d’événements, rappels et tests de sécurité.", engagement: "Produit MaydaLabs · Construction privée active.", challenge: "Rendre compréhensible un cycle d’autogarde à conséquences fortes sans cacher les risques irréversibles ni suggérer de garanties légales ou de sécurité.", built: ["Cycle contractuel propriétaire et bénéficiaire", "Réclamation différée avec délai de recours", "Historique et rappels déterministes", "Tests adversariaux, fuzz, invariants et analyse statique", "Configuration testnet et conditions de sortie"], stack: ["Solidity", "Hardhat", "Next.js", "ethers", "Testnets EVM", "Tests de sécurité"], status: "Alpha privée · Non auditée" },
      { id: "sofra", variant: "sofra", number: "04", name: "Sofra", category: "Marketplace · Hospitalité · Confiance", title: "Une marketplace gérée de dîners où la confiance fait partie du modèle produit.", summary: "Sofra est un produit privé en Phase 1, pensé pour la Türkiye et des dîners planifiés dans des foyers vérifiés. Il relie les parcours bilingues tout en protégeant les données exactes du foyer et de sécurité.", engagement: "Produit MaydaLabs · Construction privée active.", challenge: "Créer une expérience chaleureuse sur un modèle rigoureux d’approbation, confidentialité, réservation, incidents et opérations sans exposer le foyer.", built: ["Découverte publique et parcours invité", "Candidature hôte et approbation gérée", "Surfaces opérateur, réservation, prix et incidents", "Projections de données public/privé", "Architecture produit anglaise et turque"], stack: ["Next.js", "TypeScript", "Supabase", "next-intl", "Vitest", "Playwright"], status: "Phase 1 privée · Démo sûre" },
    ],
  },
} as const;

export async function generateMetadata({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  return createPageMetadata({ ...COPY[locale].meta, path: "/case-studies", locale, socialCard: "work" });
}

function Arrow() { return <span aria-hidden>↗</span>; }

const CURRENT_ASSETS: Record<string, string> = {
  "/work/hodlstay-home.png": "/work/hodlstay-2026-08-home.png",
  "/work/hodlstay-stays.png": "/work/hodlstay-2026-08-stays.png",
  "/work/hodlstay-listing.png": "/work/hodlstay-2026-08-listing.png",
  "/work/hodlstay-conferences.png": "/work/hodlstay-2026-08-conferences.png",
  "/work/satoshi-gazette-live-home.png": "/work/satoshi-gazette-2026-08-home.png",
};

function currentAsset(path: string) {
  return CURRENT_ASSETS[path] ?? path;
}

export default async function CaseStudiesPage({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  const copy = COPY[locale];
  return (
    <div className="studio-inner-page">
      <section className="studio-inner-hero"><p className="studio-kicker">{copy.kicker}</p><h1>{copy.heading[0]}<br /><em>{copy.heading[1]}</em></h1><p>{copy.intro}</p></section>
      {copy.cases.map((item) => (
        <article id={item.id} key={item.id} className="case-detail scroll-mt-28">
          <div className="case-detail-heading"><p>{item.number} / {item.name}</p><span>{item.category}</span></div>
          <div className="case-detail-title"><h2>{item.title}</h2><div><p>{item.summary}</p>{item.engagement ? <p className="case-detail-engagement"><span>{copy.engagement}</span>{item.engagement}</p> : null}<div className="case-detail-links"><Link href={localizePath(`/case-studies/${item.id}`, locale)} className="studio-text-link">{copy.full} <Arrow /></Link><a href={item.url} target="_blank" rel="noopener noreferrer" className="studio-text-link">{copy.visit} {item.domain} <Arrow /></a></div></div></div>
          <div className="case-detail-screen"><div className="project-browser-chrome"><div><i /><i /><i /></div><span>{item.domain}</span><b>{item.status}</b></div><Image src={currentAsset(item.image)} alt={item.alt} width={item.id === "satoshi-gazette" ? 1280 : 1430} height={item.id === "satoshi-gazette" ? 720 : 894} sizes="(max-width: 900px) 100vw, 90vw" /></div>
          <div className="case-detail-grid"><section><p className="studio-kicker">{copy.challenge}</p><p>{item.challenge}</p></section><section><p className="studio-kicker">{copy.built}</p><ul>{item.built.map((entry) => <li key={entry}>{entry}</li>)}</ul></section><section><p className="studio-kicker">{copy.stack}</p><div>{item.stack.map((entry) => <span key={entry}>{entry}</span>)}</div></section></div>
          {item.gallery.length ? <section className="case-gallery" aria-label={`${item.name} product gallery`}><div className="case-subheading"><p className="studio-kicker">{copy.inside}</p><h3>{copy.galleryHeading}</h3></div><div className="case-gallery-grid">{item.gallery.map(([src, alt, label, detail]) => <figure key={src}><div className="case-gallery-frame"><Image src={currentAsset(src)} alt={alt} width={1430} height={894} sizes="(max-width: 900px) 100vw, 72vw" /></div><figcaption><strong>{label}</strong><span>{detail}</span></figcaption></figure>)}</div></section> : null}
          {item.proof.length ? <section className="case-proof"><div className="case-subheading"><p className="studio-kicker">{copy.proofKicker}</p><h3>{copy.proofHeading}</h3></div><div className="case-proof-grid">{item.proof.map(([number, title, description]) => <article key={number}><span>{number}</span><h4>{title}</h4><p>{description}</p></article>)}</div></section> : null}
        </article>
      ))}
      {copy.developmentCases.map((item) => (
        <article id={item.id} key={item.id} className="case-detail scroll-mt-28">
          <div className="case-detail-heading"><p>{item.number} / {item.name}</p><span>{item.category}</span></div>
          <div className="case-detail-title"><h2>{item.title}</h2><div><p>{item.summary}</p><p className="case-detail-engagement"><span>{copy.engagement}</span>{item.engagement}</p><div className="case-detail-links"><Link href={localizePath(`/case-studies/${item.id}`, locale)} className="studio-text-link">{copy.full} <Arrow /></Link><span className="case-detail-private-note">{copy.private}</span></div></div></div>
          <div className="case-detail-screen case-detail-development"><InProgressVisual locale={locale} variant={item.variant} /></div>
          <div className="case-detail-grid"><section><p className="studio-kicker">{copy.challenge}</p><p>{item.challenge}</p></section><section><p className="studio-kicker">{copy.built}</p><ul>{item.built.map((entry) => <li key={entry}>{entry}</li>)}</ul></section><section><p className="studio-kicker">{copy.stack}</p><div>{item.stack.map((entry) => <span key={entry}>{entry}</span>)}</div></section></div>
        </article>
      ))}
      <section className="studio-inner-cta"><p className="studio-kicker">{copy.availability}</p><h2>{copy.cta}</h2><Link href={getIntroCallUrl("work_bottom")} target="_blank" rel="noopener noreferrer" className="studio-button">{copy.start} <Arrow /></Link></section>
    </div>
  );
}
