import { LegalDocument } from "@/components/LegalDocument";
import { getPageLocale, type LocalePageProps } from "@/lib/localePage";
import { createPageMetadata } from "@/lib/metadata";

const COPY = {
  en: {
    meta: { title: "Privacy notice", socialTitle: "Privacy notice · MaydaLabs", description: "How MaydaLabs handles information from this website, analytics, email, localization, and project-call scheduling." }, kicker: "Legal / Privacy", heading: ["Privacy,", "without fog."], introduction: "A plain-language account of the information involved when you visit MaydaLabs, email us, change language, or schedule a project conversation.", updated: "Last updated · 22 July 2026", documentTitle: "Website privacy notice", contactTitle: "Contact", contactCopy: "Questions about this notice or information connected to your enquiry can be sent to", contactLink: "Go to contact",
    sections: [
      { number: "01", title: "Information we receive", paragraphs: ["When you email MaydaLabs or schedule a project call, we receive the information you choose to provide, such as your name, email address, company, and project context.", "The website uses Vercel Web Analytics and Speed Insights to understand page visits, referral sources, device-level performance, and high-level interactions. These tools are configured without advertising profiles."] },
      { number: "02", title: "Language and location", paragraphs: ["On a first visit, the site may use the country code supplied by Vercel and your browser language to suggest English, Turkish, or French. We do not store your precise location.", "When you choose a language, a functional cookie named maydalabs_locale remembers that preference for up to one year. You can change it at any time from the site header."] },
      { number: "03", title: "How information is used", paragraphs: ["We use information to respond to enquiries, evaluate projects, operate and improve the website, understand which work is useful to visitors, measure performance, and maintain system security.", "We do not sell personal information or use project enquiries for unrelated bulk marketing without permission."] },
      { number: "04", title: "Providers and external links", paragraphs: ["The site is hosted on Vercel and links to Calendly for scheduling. Email is handled through Google Workspace. Those providers process information under their own terms and privacy notices.", "Links to HodlStay, Satoshi Gazette, X, LinkedIn, and other external services take you outside MaydaLabs and are controlled by their respective operators."] },
      { number: "05", title: "Retention and updates", paragraphs: ["Enquiry records are kept only as long as reasonably needed for a conversation, potential or active engagement, legal obligations, and basic business records.", "This notice may change when the site, analytics, localization, or services change. You may request access, correction, or deletion where applicable by contacting us."] },
    ],
  },
  tr: {
    meta: { title: "Gizlilik bildirimi", socialTitle: "Gizlilik bildirimi · MaydaLabs", description: "MaydaLabs'in web sitesi, analitik, e-posta, dil seçimi ve proje görüşmelerindeki bilgileri nasıl işlediği." }, kicker: "Yasal / Gizlilik", heading: ["Gizlilik,", "sis perdesi olmadan."], introduction: "MaydaLabs'i ziyaret ettiğinizde, e-posta gönderdiğinizde, dil değiştirdiğinizde veya proje görüşmesi ayarladığınızda kullanılan bilgilere dair açık anlatım.", updated: "Son güncelleme · 22 Temmuz 2026", documentTitle: "Web sitesi gizlilik bildirimi", contactTitle: "İletişim", contactCopy: "Bu bildirim veya başvurunuzla bağlantılı bilgiler hakkındaki sorularınızı şu adrese gönderebilirsiniz:", contactLink: "İletişime git",
    sections: [
      { number: "01", title: "Aldığımız bilgiler", paragraphs: ["MaydaLabs'e e-posta gönderdiğinizde veya proje görüşmesi ayarladığınızda adınız, e-posta adresiniz, şirketiniz ve proje bağlamınız gibi paylaşmayı seçtiğiniz bilgileri alırız.", "Web sitesi; sayfa ziyaretleri, yönlendirme kaynakları, cihaz düzeyinde performans ve genel etkileşimleri anlamak için Vercel Web Analytics ve Speed Insights kullanır. Bu araçlar reklam profili oluşturmadan yapılandırılmıştır."] },
      { number: "02", title: "Dil ve konum", paragraphs: ["İlk ziyarette site, İngilizce, Türkçe veya Fransızca önermek için Vercel'in sağladığı ülke kodunu ve tarayıcı dilinizi kullanabilir. Kesin konumunuzu saklamayız.", "Dil seçtiğinizde maydalabs_locale adlı işlevsel çerez bu tercihi bir yıla kadar hatırlar. Üst menüden istediğiniz zaman değiştirebilirsiniz."] },
      { number: "03", title: "Bilgilerin kullanımı", paragraphs: ["Bilgileri başvurulara yanıt vermek, projeleri değerlendirmek, siteyi işletmek ve iyileştirmek, faydalı içerikleri anlamak, performansı ölçmek ve sistem güvenliğini korumak için kullanırız.", "Kişisel bilgileri satmayız veya proje başvurularını izinsiz ve ilgisiz toplu pazarlama için kullanmayız."] },
      { number: "04", title: "Hizmet sağlayıcılar ve dış bağlantılar", paragraphs: ["Site Vercel üzerinde barındırılır ve planlama için Calendly'ye bağlanır. E-posta Google Workspace üzerinden yürütülür. Bu sağlayıcılar bilgileri kendi koşulları ve gizlilik bildirimleri kapsamında işler.", "HodlStay, Satoshi Gazette, X, LinkedIn ve diğer harici hizmet bağlantıları sizi MaydaLabs dışına götürür ve ilgili operatörler tarafından kontrol edilir."] },
      { number: "05", title: "Saklama ve güncellemeler", paragraphs: ["Başvuru kayıtları yalnızca görüşme, potansiyel veya aktif çalışma, yasal yükümlülükler ve temel iş kayıtları için makul süre boyunca saklanır.", "Site, analitik, dil sistemi veya hizmetler değiştiğinde bu bildirim güncellenebilir. Uygun olduğu durumlarda erişim, düzeltme veya silme talep edebilirsiniz."] },
    ],
  },
  fr: {
    meta: { title: "Avis de confidentialité", socialTitle: "Avis de confidentialité · MaydaLabs", description: "Comment MaydaLabs traite les informations liées au site, aux analytics, aux e-mails, aux langues et aux appels projet." }, kicker: "Juridique / Confidentialité", heading: ["La confidentialité,", "sans brouillard."], introduction: "Une explication claire des informations impliquées lorsque vous visitez MaydaLabs, nous écrivez, changez de langue ou réservez un échange projet.", updated: "Dernière mise à jour · 22 juillet 2026", documentTitle: "Avis de confidentialité du site", contactTitle: "Contact", contactCopy: "Les questions sur cet avis ou les informations liées à votre demande peuvent être envoyées à", contactLink: "Aller au contact",
    sections: [
      { number: "01", title: "Informations reçues", paragraphs: ["Lorsque vous écrivez à MaydaLabs ou réservez un appel projet, nous recevons les informations que vous choisissez de fournir : nom, e-mail, société et contexte du projet.", "Le site utilise Vercel Web Analytics et Speed Insights pour comprendre les visites, sources de référence, performances par appareil et interactions générales. Ces outils sont configurés sans profils publicitaires."] },
      { number: "02", title: "Langue et localisation", paragraphs: ["Lors d’une première visite, le site peut utiliser le code pays fourni par Vercel et la langue du navigateur pour proposer l’anglais, le turc ou le français. Nous ne stockons pas votre localisation précise.", "Lorsque vous choisissez une langue, un cookie fonctionnel nommé maydalabs_locale mémorise ce choix jusqu’à un an. Vous pouvez le modifier depuis l’en-tête."] },
      { number: "03", title: "Utilisation des informations", paragraphs: ["Nous utilisons ces informations pour répondre aux demandes, évaluer les projets, exploiter et améliorer le site, comprendre les contenus utiles, mesurer les performances et protéger nos systèmes.", "Nous ne vendons pas les informations personnelles et n’utilisons pas les demandes projet pour du marketing de masse sans autorisation."] },
      { number: "04", title: "Prestataires et liens externes", paragraphs: ["Le site est hébergé sur Vercel et utilise Calendly pour la planification. Les e-mails passent par Google Workspace. Ces prestataires traitent les informations selon leurs propres conditions.", "Les liens vers HodlStay, Satoshi Gazette, X, LinkedIn et d’autres services vous font quitter MaydaLabs et sont contrôlés par leurs opérateurs."] },
      { number: "05", title: "Conservation et mises à jour", paragraphs: ["Les demandes sont conservées uniquement pendant la durée raisonnablement nécessaire à l’échange, à une mission potentielle ou active, aux obligations légales et aux archives professionnelles.", "Cet avis peut évoluer avec le site, les analytics, les langues ou les services. Vous pouvez demander accès, correction ou suppression lorsque la loi le permet."] },
    ],
  },
} as const;

export async function generateMetadata({ params }: LocalePageProps) { const locale = await getPageLocale(params); return createPageMetadata({ ...COPY[locale].meta, path: "/privacy", locale, socialCard: "legal" }); }
export default async function PrivacyPage({ params }: LocalePageProps) { const locale = await getPageLocale(params); const copy = COPY[locale]; return <LegalDocument locale={locale} kicker={copy.kicker} heading={copy.heading} introduction={copy.introduction} updated={copy.updated} documentId="Document / ML-P01" documentTitle={copy.documentTitle} sections={copy.sections} contactNumber="06" contactTitle={copy.contactTitle} contactCopy={copy.contactCopy} contactLink={copy.contactLink} />; }
