import { LegalDocument } from "@/components/LegalDocument";
import { getPageLocale, type LocalePageProps } from "@/lib/localePage";
import { createPageMetadata } from "@/lib/metadata";

const COPY = {
  en: {
    meta: { title: "Privacy notice", socialTitle: "Privacy notice · MaydaLabs", description: "How MaydaLabs handles information from this website: analytics, enquiries, accounts, email preferences, and scheduling." },
    kicker: "Legal / Privacy", heading: ["Privacy,", "without fog."],
    introduction: "A plain-language account of the information involved when you visit MaydaLabs, send an enquiry, create an account, or schedule a conversation.",
    updated: "Last updated · 11 September 2026", documentTitle: "Website privacy notice", contactTitle: "Contact and your rights", contactCopy: "You can request access, correction, or deletion of your information — including your whole account — by writing from the relevant address to", contactLink: "Go to contact",
    sections: [
      { number: "01", title: "Information we receive", paragraphs: ["When you send an enquiry or email MaydaLabs, we receive what you choose to provide: typically your name, email address, company, and project context. Enquiries are stored only with your explicit consent, given on the form itself, and each one receives a single acknowledgement by email — nothing more.", "The website uses Vercel Web Analytics and Speed Insights to understand page visits, referral sources, and performance. These tools are configured without advertising profiles, and analytics events never contain what you type into forms."] },
      { number: "02", title: "Accounts and the portal", paragraphs: ["Signing in uses a one-time email code — no password is created or stored. An account exists so you can see work prepared for your decision and follow an engagement with MaydaLabs.", "Account data is stored in a Supabase-hosted database with row-level security: your records are readable and editable only by you and, for enquiries, by MaydaLabs for review."] },
      { number: "03", title: "Email updates", paragraphs: ["The updates preference is a free, optional subscription offered on the contact form. It stays pending until a confirmed sending setup exists, and no marketing email is sent before then. You can withdraw it any time by writing to us.", "Enquiries you submit are used to respond to you — never for unrelated bulk marketing."] },
      { number: "04", title: "Language choice", paragraphs: ["English uses unprefixed URLs. Turkish and French are available at explicit localized routes, and the site does not use precise location or browser language to redirect visitors. There is no language-preference cookie."] },
      { number: "05", title: "Providers and external links", paragraphs: ["The site is hosted on Vercel; the database and authentication run on Supabase; scheduling links to Calendly; email is handled through Google Workspace, and transactional messages such as sign-in codes and enquiry acknowledgements are sent through Resend. These providers process information under their own terms and privacy notices.", "Links to HodlStay, Satoshi Gazette, X, LinkedIn, and other external services take you outside MaydaLabs and are controlled by their respective operators."] },
      { number: "06", title: "Retention and updates", paragraphs: ["Records are kept only as long as reasonably needed for a conversation, potential or active engagement, legal obligations, and basic business records. Deleting your account removes its records.", "This notice changes when the site's data handling changes; the current version is always published here with its revision date."] },
    ],
  },
  tr: {
    meta: { title: "Gizlilik bildirimi", socialTitle: "Gizlilik bildirimi · MaydaLabs", description: "MaydaLabs'in bu web sitesindeki bilgileri nasıl işlediği: analitik, talepler, hesaplar, e-posta tercihleri ve planlama." },
    kicker: "Yasal / Gizlilik", heading: ["Gizlilik,", "sis perdesi olmadan."],
    introduction: "MaydaLabs'i ziyaret ettiğinizde, talep gönderdiğinizde, hesap oluşturduğunuzda veya görüşme ayarladığınızda kullanılan bilgilerin sade bir açıklaması.",
    updated: "Son güncelleme · 11 Eylül 2026", documentTitle: "Web sitesi gizlilik bildirimi", contactTitle: "İletişim ve haklarınız", contactCopy: "Bilgilerinize erişim, düzeltme veya silme — tüm hesabınız dahil — talebinizi ilgili adresten şu adrese yazarak iletebilirsiniz:", contactLink: "İletişime git",
    sections: [
      { number: "01", title: "Aldığımız bilgiler", paragraphs: ["Talep gönderdiğinizde veya MaydaLabs'e e-posta yazdığınızda paylaşmayı seçtiğiniz bilgileri alırız: genellikle adınız, e-posta adresiniz, şirketiniz ve proje bağlamınız. Talepler yalnızca formun üzerinde verdiğiniz açık onayla saklanır ve her talep için tek bir onay e-postası gönderilir — başka bir şey değil.", "Web sitesi; sayfa ziyaretlerini, yönlendirme kaynaklarını ve performansı anlamak için Vercel Web Analytics ve Speed Insights kullanır. Bu araçlar reklam profili olmadan yapılandırılmıştır ve analitik olaylar formlara yazdıklarınızı asla içermez."] },
      { number: "02", title: "Hesaplar ve portal", paragraphs: ["Giriş, tek kullanımlık bir e-posta koduyla yapılır — parola oluşturulmaz ve saklanmaz. Hesap; kararınız için hazırlanan işleri görebilmeniz ve MaydaLabs ile çalışmanızı izleyebilmeniz için vardır.", "Hesap verileri, satır düzeyinde güvenlikle Supabase'te barındırılan bir veritabanında tutulur: kayıtlarınızı yalnızca siz okuyup değiştirebilirsiniz; gönderilen talepleri inceleme amacıyla MaydaLabs da görebilir."] },
      { number: "03", title: "E-posta güncellemeleri", paragraphs: ["Güncelleme tercihi, iletişim formunda sunulan ücretsiz ve opsiyonel bir aboneliktir. Onaylı bir gönderim altyapısı kurulana kadar beklemede kalır ve o zamana kadar hiçbir pazarlama e-postası gönderilmez. Bize yazarak her an geri çekebilirsiniz.", "Gönderdiğiniz talepler size yanıt vermek için kullanılır — ilgisiz toplu pazarlama için asla."] },
      { number: "04", title: "Dil seçimi", paragraphs: ["İngilizce ön eksiz URL'leri kullanır. Türkçe ve Fransızca açık yerelleştirilmiş rotalarda sunulur; site ziyaretçileri yönlendirmek için kesin konum veya tarayıcı dili kullanmaz. Dil tercihi çerezi yoktur."] },
      { number: "05", title: "Hizmet sağlayıcılar ve dış bağlantılar", paragraphs: ["Site Vercel üzerinde barındırılır; veritabanı ve kimlik doğrulama Supabase'te çalışır; planlama Calendly'ye bağlanır; e-posta Google Workspace üzerinden yürütülür; giriş kodları ve talep onayları gibi işlemsel e-postalar ise Resend üzerinden gönderilir. Bu sağlayıcılar bilgileri kendi koşulları ve gizlilik bildirimleri kapsamında işler.", "HodlStay, Satoshi Gazette, X, LinkedIn ve diğer dış hizmet bağlantıları sizi MaydaLabs dışına götürür ve ilgili operatörler tarafından kontrol edilir."] },
      { number: "06", title: "Saklama ve güncellemeler", paragraphs: ["Kayıtlar yalnızca görüşme, potansiyel veya aktif çalışma, yasal yükümlülükler ve temel iş kayıtları için makul süre boyunca saklanır. Hesabınızı silmek hesap kayıtlarınızı kaldırır.", "Sitenin veri işleme biçimi değiştiğinde bu bildirim güncellenir; güncel sürüm her zaman revizyon tarihiyle burada yayınlanır."] },
    ],
  },
  fr: {
    meta: { title: "Avis de confidentialité", socialTitle: "Avis de confidentialité · MaydaLabs", description: "Comment MaydaLabs traite les informations de ce site : analytics, demandes, comptes, préférences e-mail et planification." },
    kicker: "Juridique / Confidentialité", heading: ["La confidentialité,", "sans brouillard."],
    introduction: "Une explication claire des informations impliquées quand vous visitez MaydaLabs, envoyez une demande, créez un compte ou réservez un échange.",
    updated: "Dernière mise à jour · 11 septembre 2026", documentTitle: "Avis de confidentialité du site", contactTitle: "Contact et vos droits", contactCopy: "Vous pouvez demander l'accès, la correction ou la suppression de vos informations — y compris votre compte entier — en écrivant depuis l'adresse concernée à", contactLink: "Aller au contact",
    sections: [
      { number: "01", title: "Informations reçues", paragraphs: ["Quand vous envoyez une demande ou écrivez à MaydaLabs, nous recevons ce que vous choisissez de fournir : en général nom, e-mail, société et contexte du projet. Les demandes ne sont conservées qu'avec votre consentement explicite, donné sur le formulaire, et chacune reçoit un seul accusé de réception par e-mail — rien de plus.", "Le site utilise Vercel Web Analytics et Speed Insights pour comprendre visites, sources et performances. Ces outils sont configurés sans profils publicitaires, et les événements analytics ne contiennent jamais ce que vous tapez dans les formulaires."] },
      { number: "02", title: "Comptes et portail", paragraphs: ["La connexion utilise un code e-mail à usage unique — aucun mot de passe n'est créé ni stocké. Le compte existe pour voir le travail préparé pour votre décision et suivre une mission avec MaydaLabs.", "Les données de compte sont stockées dans une base hébergée par Supabase avec sécurité au niveau des lignes : vos enregistrements ne sont lisibles et modifiables que par vous et, pour les demandes envoyées, par MaydaLabs pour leur examen."] },
      { number: "03", title: "Nouvelles par e-mail", paragraphs: ["La préférence de nouvelles est un abonnement gratuit et optionnel proposé sur le formulaire de contact. Elle reste en attente tant qu'aucune infrastructure d'envoi confirmée n'existe, et aucun e-mail marketing n'est envoyé avant. Vous pouvez la retirer à tout moment en nous écrivant.", "Les demandes envoyées servent à vous répondre — jamais à du marketing de masse sans rapport."] },
      { number: "04", title: "Choix de langue", paragraphs: ["L'anglais utilise les URL sans préfixe. Le turc et le français sont proposés sur des routes localisées explicites ; le site n'utilise ni localisation précise ni langue du navigateur pour rediriger. Aucun cookie de préférence linguistique n'existe."] },
      { number: "05", title: "Prestataires et liens externes", paragraphs: ["Le site est hébergé sur Vercel ; base de données et authentification tournent sur Supabase ; la planification renvoie vers Calendly ; les e-mails passent par Google Workspace ; les messages transactionnels comme les codes de connexion et les accusés de réception de demandes sont envoyés via Resend. Ces prestataires traitent les informations selon leurs propres conditions.", "Les liens vers HodlStay, Satoshi Gazette, X, LinkedIn et d'autres services vous font quitter MaydaLabs et sont contrôlés par leurs opérateurs."] },
      { number: "06", title: "Conservation et mises à jour", paragraphs: ["Les enregistrements sont conservés uniquement le temps raisonnablement nécessaire à l'échange, à une mission potentielle ou active, aux obligations légales et aux archives professionnelles. Supprimer votre compte retire ses enregistrements.", "Cet avis évolue quand le traitement des données du site change ; la version actuelle est toujours publiée ici avec sa date de révision."] },
    ],
  },
} as const;

export async function generateMetadata({ params }: LocalePageProps) { const locale = await getPageLocale(params); return createPageMetadata({ ...COPY[locale].meta, path: "/privacy", locale, socialCard: "legal" }); }
export default async function PrivacyPage({ params }: LocalePageProps) { const locale = await getPageLocale(params); const copy = COPY[locale]; return <LegalDocument locale={locale} kicker={copy.kicker} heading={copy.heading} introduction={copy.introduction} updated={copy.updated} documentId="Document / ML-P02" documentTitle={copy.documentTitle} sections={copy.sections} contactNumber="08" contactTitle={copy.contactTitle} contactCopy={copy.contactCopy} contactLink={copy.contactLink} />; }
