import { InProgressCaseStudy } from "@/components/InProgressCaseStudy";
import { getPageLocale, type LocalePageProps } from "@/lib/localePage";
import { createPageMetadata } from "@/lib/metadata";

const COPY = {
  en: {
    meta: { title: "Mortal Vault case study", socialTitle: "Mortal Vault: self-custodial continuity · MaydaLabs", description: "A work-in-progress MaydaLabs product exploring owner check-ins, delayed beneficiary claims, and explicit self-custody safety boundaries." },
    back: "Selected work", kicker: "Work in progress 03 / Private alpha", status: "Private alpha", statusNote: "Active development · contracts unaudited", scope: "Current scope", scopeItems: ["Solidity", "Hardhat", "Next.js", "EVM testnets"], hero: ["Continuity rules without a", "custodian."], lead: "Mortal Vault is a self-custodial continuity vault: an owner checks in, inactivity opens a delayed beneficiary claim, and owner activity can still cancel it before execution.", visitWork: "Inspect the current build", builtKicker: "Current build / Repository evidence", builtTitle: "A complete lifecycle before a public promise.", boundary: "The engineering story is already substantial, but the release story is intentionally narrower: local and testnet-first work, no meaningful funds, and no mainnet claim before independent review.", built: [["01", "Bounded contract lifecycle", "Create, fund, update, check in, withdraw, close, request a claim, cancel it through owner activity, and execute only after both time gates."], ["02", "Owner and beneficiary journeys", "The Next.js interface separates owner control from a shareable beneficiary claim path and exposes network, contract, and transaction state."], ["03", "Event-backed history", "Contract events are parsed into bounded owner and beneficiary activity views designed to survive refreshes and support deterministic reminder planning."], ["04", "Security work as a gate", "Adversarial tests, fuzzing, invariants, static analysis, a threat model, balance caps, and explicit release blockers are part of the repository." ]], boundaryKicker: "Honest boundary / What this is not", boundaryTitle: "Alpha means the risk is visible.", boundaryItems: ["Contracts are unaudited and must not hold meaningful funds.", "No administrator, custody service, legal determination, or emergency override exists.", "This is not legal inheritance, probate, identity verification, or key recovery.", "Mainnet remains blocked by independent review, external wallet exercises, monitoring, and demonstrated demand."], nextKicker: "Next gates / Before a public beta", next: "Validation outside the repository.", nextItems: ["Complete external testnet owner and beneficiary exercises.", "Resolve every critical or high issue from independent security review.", "Verify deployment inputs, chain disclosures, monitoring, and recovery instructions.", "Keep any mainnet candidate capped until evidence supports expanding it."], ctaKicker: "Building a trust-critical product?", cta: ["Make the state explicit.", "Make the risk legible."], start: "Start a project",
  },
  tr: {
    meta: { title: "Mortal Vault vaka çalışması", socialTitle: "Mortal Vault: self-custody süreklilik · MaydaLabs", description: "Sahip check-in'leri, gecikmeli lehtar talepleri ve açık self-custody güvenlik sınırlarını araştıran geliştirme aşamasındaki MaydaLabs ürünü." },
    back: "Seçili projeler", kicker: "Geliştirme aşamasında 03 / Özel alpha", status: "Özel alpha", statusNote: "Aktif geliştirme · sözleşmeler denetlenmedi", scope: "Mevcut kapsam", scopeItems: ["Solidity", "Hardhat", "Next.js", "EVM testnetleri"], hero: ["Saklama hizmeti olmadan", "süreklilik kuralları."], lead: "Mortal Vault bir self-custody süreklilik kasasıdır: sahip düzenli olarak aktivitesini kanıtlar, hareketsizlik gecikmeli lehtar talebini açar ve sahip aktivitesi gerçekleşmeden önce talebi iptal edebilir.", visitWork: "Mevcut ürünü incele", builtKicker: "Mevcut ürün / Repository kanıtı", builtTitle: "Herkese açık vaatten önce tam yaşam döngüsü.", boundary: "Mühendislik çalışması güçlü; sürüm iddiası bilinçli olarak daha dar: yerel ve testnet öncelikli, anlamlı tutar yok ve bağımsız inceleme öncesi mainnet iddiası yok.", built: [["01", "Sınırlı sözleşme yaşam döngüsü", "Oluşturma, fonlama, güncelleme, check-in, çekme, kapatma, talep başlatma, sahip aktivitesiyle iptal ve yalnızca iki zaman kapısından sonra yürütme."], ["02", "Sahip ve lehtar yolculukları", "Next.js arayüzü sahip kontrolünü paylaşılabilir lehtar talep yolundan ayırır; ağ, sözleşme ve işlem durumunu görünür kılar."], ["03", "Event tabanlı geçmiş", "Sözleşme eventleri, yenilemelerden sonra kalan ve deterministik hatırlatma planını destekleyen sınırlı aktivite görünümlerine dönüşür."], ["04", "Sürüm kapısı olarak güvenlik", "Adversarial testler, fuzzing, invariantlar, statik analiz, tehdit modeli, bakiye limitleri ve açık sürüm engelleri repository'nin parçasıdır." ]], boundaryKicker: "Dürüst sınır / Ne değildir", boundaryTitle: "Alpha, riskin görünür olmasıdır.", boundaryItems: ["Sözleşmeler denetlenmemiştir ve anlamlı tutarlarla kullanılmamalıdır.", "Yönetici, saklama hizmeti, hukuki karar veya acil durum override'ı yoktur.", "Hukuki miras, veraset, kimlik doğrulama veya anahtar kurtarma ürünü değildir.", "Mainnet; bağımsız inceleme, dış cüzdan egzersizleri, izleme ve kanıtlanmış talep olmadan kapalıdır."], nextKicker: "Sonraki kapılar / Açık beta öncesi", next: "Repository dışındaki doğrulama.", nextItems: ["Dış kullanıcılarla testnet sahip ve lehtar akışlarını tamamla.", "Bağımsız güvenlik incelemesindeki tüm kritik ve yüksek bulguları çöz.", "Dağıtım girdileri, ağ bildirimleri, izleme ve kurtarma talimatlarını doğrula.", "Kanıt genişlemeyi destekleyene kadar mainnet adayını sınırlı tut."], ctaKicker: "Güven kritik bir ürün mü geliştiriyorsunuz?", cta: ["Durumu açık kılın.", "Riski anlaşılır yapın."], start: "Proje başlat",
  },
  fr: {
    meta: { title: "Étude de cas Mortal Vault", socialTitle: "Mortal Vault : continuité en autogarde · MaydaLabs", description: "Un produit MaydaLabs en cours qui explore les check-ins, les réclamations différées et des limites de sécurité explicites." },
    back: "Projets sélectionnés", kicker: "En cours 03 / Alpha privée", status: "Alpha privée", statusNote: "Construction active · contrats non audités", scope: "Périmètre actuel", scopeItems: ["Solidity", "Hardhat", "Next.js", "Testnets EVM"], hero: ["Des règles de continuité sans", "dépositaire."], lead: "Mortal Vault est un coffre de continuité en autogarde : le propriétaire confirme son activité, l’inactivité ouvre une réclamation différée et une action du propriétaire peut encore l’annuler.", visitWork: "Inspecter le produit actuel", builtKicker: "Produit actuel / Preuves du dépôt", builtTitle: "Un cycle complet avant une promesse publique.", boundary: "L’ingénierie est déjà substantielle, mais la sortie reste volontairement étroite : local et testnet d’abord, aucun fonds significatif et aucune promesse mainnet avant revue indépendante.", built: [["01", "Cycle contractuel borné", "Créer, financer, modifier, confirmer, retirer, fermer, demander une réclamation, l’annuler par activité et exécuter après les deux délais."], ["02", "Parcours propriétaire et bénéficiaire", "L’interface Next.js sépare le contrôle du propriétaire d’un parcours partageable et expose réseau, contrat et transactions."], ["03", "Historique fondé sur les événements", "Les événements deviennent des vues bornées conçues pour survivre au rafraîchissement et soutenir des rappels déterministes."], ["04", "La sécurité comme condition", "Tests adversariaux, fuzzing, invariants, analyse statique, menace, plafonds et blocages de sortie font partie du dépôt." ]], boundaryKicker: "Limite honnête / Ce que ce n’est pas", boundaryTitle: "Alpha signifie rendre le risque visible.", boundaryItems: ["Les contrats ne sont pas audités et ne doivent pas détenir de fonds significatifs.", "Aucun administrateur, dépositaire, jugement légal ou dérogation d’urgence.", "Ce n’est ni un service successoral, ni une vérification d’identité, ni une récupération de clé.", "Le mainnet reste bloqué par la revue, les essais externes, le suivi et la preuve de demande."], nextKicker: "Prochaines conditions / Avant une bêta", next: "Valider hors du dépôt.", nextItems: ["Réaliser les parcours testnet avec des utilisateurs externes.", "Résoudre tout problème critique ou élevé d’une revue indépendante.", "Vérifier déploiement, réseau, suivi et instructions de récupération.", "Garder tout candidat mainnet plafonné jusqu’à preuve suffisante."], ctaKicker: "Vous construisez un produit critique ?", cta: ["Rendez l’état explicite.", "Rendez le risque lisible."], start: "Lancer un projet",
  },
} as const;

export async function generateMetadata({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  return createPageMetadata({ ...COPY[locale].meta, path: "/case-studies/mortal-vault", locale, socialCard: "mortal-vault" });
}

export default async function MortalVaultCaseStudyPage({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  return <InProgressCaseStudy copy={COPY[locale]} locale={locale} name="Mortal Vault" variant="mortal" />;
}
