import type { Locale } from "@/lib/i18n";

/* Client-facing invoice wording. Operator screens stay English. */

export const INVOICE_COPY = {
  en: {
    heading: "Pay in bitcoin",
    intro: "Scan with any bitcoin wallet, or copy the address. The amount is locked at the rate below.",
    amountLabel: "Amount",
    addressLabel: "Address",
    rateLabel: "Rate locked at",
    expiresLabel: "Quote valid until",
    check: "Check for payment",
    viewOnChain: "View on mempool.space",
    states: {
      open: "Waiting for payment",
      underpaid: "Part of the amount has arrived",
      paid: "Paid",
      expired: "Quote expired",
      void: "Cancelled",
    },
    pending: "Seen in the mempool, waiting for a confirmation",
    received: "Received so far",
    expiredNote: "The rate is no longer held. Ask for a fresh invoice before paying.",
    paidNote: "Confirmed on the chain. Nothing further is needed.",
    manual: "Paying from an exchange? Send the exact amount; exchange fees are yours, and a short payment leaves the invoice open.",
  },
  tr: {
    heading: "Bitcoin ile ödeyin",
    intro: "Herhangi bir bitcoin cüzdanıyla okutun veya adresi kopyalayın. Tutar, aşağıdaki kurdan sabitlenmiştir.",
    amountLabel: "Tutar",
    addressLabel: "Adres",
    rateLabel: "Sabitlenen kur",
    expiresLabel: "Teklif geçerlilik süresi",
    check: "Ödemeyi kontrol et",
    viewOnChain: "mempool.space üzerinde görüntüle",
    states: {
      open: "Ödeme bekleniyor",
      underpaid: "Tutarın bir kısmı ulaştı",
      paid: "Ödendi",
      expired: "Teklif süresi doldu",
      void: "İptal edildi",
    },
    pending: "Mempool'da görüldü, onay bekleniyor",
    received: "Şu ana kadar gelen",
    expiredNote: "Kur artık tutulmuyor. Ödemeden önce yeni bir fatura isteyin.",
    paidNote: "Zincirde onaylandı. Başka bir şey gerekmiyor.",
    manual: "Borsadan mı ödüyorsunuz? Tam tutarı gönderin; borsa masrafları size aittir ve eksik ödeme faturayı açık bırakır.",
  },
  fr: {
    heading: "Payer en bitcoin",
    intro: "Scannez avec n'importe quel portefeuille bitcoin, ou copiez l'adresse. Le montant est bloque au taux ci-dessous.",
    amountLabel: "Montant",
    addressLabel: "Adresse",
    rateLabel: "Taux bloque a",
    expiresLabel: "Devis valable jusqu'au",
    check: "Verifier le paiement",
    viewOnChain: "Voir sur mempool.space",
    states: {
      open: "En attente de paiement",
      underpaid: "Une partie du montant est arrivee",
      paid: "Paye",
      expired: "Devis expire",
      void: "Annule",
    },
    pending: "Vu dans le mempool, en attente de confirmation",
    received: "Recu a ce jour",
    expiredNote: "Le taux n'est plus tenu. Demandez une nouvelle facture avant de payer.",
    paidNote: "Confirme sur la chaine. Rien d'autre n'est necessaire.",
    manual: "Vous payez depuis une plateforme d'echange ? Envoyez le montant exact ; les frais sont a votre charge et un paiement insuffisant laisse la facture ouverte.",
  },
} as const satisfies Record<Locale, unknown>;
