import type { Locale } from "@/lib/i18n";

/* MaydaOS, client-facing.
 *
 * Every value here is a plain string, including the ones with numbers in
 * them: this object crosses into a client component, and a function cannot
 * make that trip. */

export function fillBudget(template: string, spent: string, budget: string): string {
  return template.replace("{spent}", spent).replace("{budget}", budget);
}

export const OS_DESK_COPY = {
  en: {
    kicker: "MaydaOS",
    heading: "Work waiting for you.",
    produceHeading: "Produce the next piece",
    budgetLine: "{spent} of {budget} used this month",
    budgetNote: "Reading sources, editing, approving and sending back cost nothing. Only producing a draft does.",
    topicLabel: "What is this about?",
    topicPlaceholder: "e.g. What changed in EU stablecoin rules this month",
    workflowLabel: "Workflow",
    shapeLabel: "Shape",
    shapes: { note: "Short note", post: "LinkedIn post", summary: "Summary of the sources" },
    sourcesLabel: "Sources (one link per line, up to 5)",
    run: "Run",
    running: "Reading the sources...",
    runsHeading: "Recent work",
    historyLink: "Everything that happened",
    empty: "Nothing yet. Add a link and press run.",
    draftLabel: "Draft",
    claimsLabel: "Every claim, next to its source",
    unsourced: "No source. Check this before approving.",
    copy: "Copy the draft",
    copied: "Copied",
    outcomeLabel: "Where did it go?",
    outcomeNote: "Paste the public link once you have posted or sent it. MaydaOS never posts anything itself.",
    outcomeSave: "Save the link",
    approve: "Approve",
    reject: "Send back",
    noteLabel: "Note (optional)",
    decisions: { pending: "Waiting for you", approved: "Approved by you", rejected: "Sent back" },
    outOfHeading: "This workflow has used its budget for the month.",
    outOfBody: "Everything already produced stays here, and it is yours. The budget resets on the first of the month.",
    noWorkflow: "No workflow yet. Set one up and it appears here, ready to run.",
    setUp: "Set up your workflows",
    notConfigured: "Running is switched off at the moment. Your workflows and everything already produced are safe.",
    failed: "This run failed and cost nothing.",
  },
  tr: {
    kicker: "MaydaOS",
    heading: "Sizi bekleyen iş.",
    produceHeading: "Sonraki işi üretin",
    budgetLine: "Bu ay {budget} bütçenin {spent} kadarı kullanıldı",
    budgetNote: "Kaynakları okumak, düzenlemek, onaylamak ve geri göndermek ücretsizdir. Yalnızca taslak üretmek maliyet oluşturur.",
    topicLabel: "Konu nedir?",
    topicPlaceholder: "örn. Bu ay AB stablecoin kurallarında ne değişti",
    workflowLabel: "İş akışı",
    shapeLabel: "Biçim",
    shapes: { note: "Kısa not", post: "LinkedIn gönderisi", summary: "Kaynakların özeti" },
    sourcesLabel: "Kaynaklar (her satıra bir bağlantı, en fazla 5)",
    run: "Çalıştır",
    running: "Kaynaklar okunuyor...",
    runsHeading: "Son işler",
    historyLink: "Olan biten her şey",
    empty: "Henüz bir şey yok. Bir bağlantı ekleyip çalıştırın.",
    draftLabel: "Taslak",
    claimsLabel: "Her iddia, kaynağının yanında",
    unsourced: "Kaynak yok. Onaylamadan önce kontrol edin.",
    copy: "Taslağı kopyala",
    copied: "Kopyalandı",
    outcomeLabel: "Nereye gitti?",
    outcomeNote: "Yayınladıktan veya gönderdikten sonra herkese açık bağlantıyı yapıştırın. MaydaOS hiçbir şeyi kendisi yayınlamaz.",
    outcomeSave: "Bağlantıyı kaydet",
    approve: "Onayla",
    reject: "Geri gönder",
    noteLabel: "Not (isteğe bağlı)",
    decisions: { pending: "Sizi bekliyor", approved: "Onayladınız", rejected: "Geri gönderildi" },
    outOfHeading: "Bu iş akışı bu ayki bütçesini kullandı.",
    outOfBody: "Üretilen her şey burada kalıyor ve size ait. Bütçe ayın birinde yenilenir.",
    noWorkflow: "Henüz iş akışı yok. Bir tane kurun; burada çalıştırılmaya hazır görünür.",
    setUp: "İş akışlarınızı kurun",
    notConfigured: "Çalıştırma şu anda kapalı. İş akışlarınız ve üretilmiş her şey yerinde duruyor.",
    failed: "Bu çalıştırma başarısız oldu ve bir maliyeti olmadı.",
  },
  fr: {
    kicker: "MaydaOS",
    heading: "Le travail qui vous attend.",
    produceHeading: "Produire la pièce suivante",
    budgetLine: "{spent} sur {budget} utilisés ce mois-ci",
    budgetNote: "Lire les sources, éditer, approuver et renvoyer ne coûtent rien. Seule la production d'un brouillon a un coût.",
    topicLabel: "De quoi s'agit-il ?",
    topicPlaceholder: "ex. Ce qui a changé dans les règles européennes ce mois-ci",
    workflowLabel: "Flux",
    shapeLabel: "Format",
    shapes: { note: "Note courte", post: "Post LinkedIn", summary: "Résumé des sources" },
    sourcesLabel: "Sources (un lien par ligne, 5 maximum)",
    run: "Exécuter",
    running: "Lecture des sources...",
    runsHeading: "Travaux récents",
    historyLink: "Tout ce qui s'est passé",
    empty: "Rien pour l'instant. Ajoutez un lien et lancez.",
    draftLabel: "Brouillon",
    claimsLabel: "Chaque affirmation, à côté de sa source",
    unsourced: "Aucune source. Vérifiez avant d'approuver.",
    copy: "Copier le brouillon",
    copied: "Copié",
    outcomeLabel: "Où est-ce parti ?",
    outcomeNote: "Collez le lien public une fois publié ou envoyé. MaydaOS ne publie jamais rien lui-même.",
    outcomeSave: "Enregistrer le lien",
    approve: "Approuver",
    reject: "Renvoyer",
    noteLabel: "Note (facultatif)",
    decisions: { pending: "En attente de vous", approved: "Approuvé par vous", rejected: "Renvoyé" },
    outOfHeading: "Ce flux a utilisé son budget du mois.",
    outOfBody: "Tout ce qui a été produit reste ici et vous appartient. Le budget repart le premier du mois.",
    noWorkflow: "Aucun flux pour l'instant. Créez-en un et il apparaîtra ici, prêt à être lancé.",
    setUp: "Configurer vos flux",
    notConfigured: "L'exécution est désactivée pour le moment. Vos flux et tout ce qui a déjà été produit sont intacts.",
    failed: "Cette exécution a échoué et n'a rien coûté.",
  },
} as const satisfies Record<Locale, unknown>;

export type OsDeskCopy = (typeof OS_DESK_COPY)[Locale];

/* Setting up your own workflow. A member names the work, says what it reads
 * and how it should be written; the key, the budget and the owner are not
 * theirs to choose and are not asked for here. */
export const OS_WORKFLOW_COPY = {
  en: {
    heading: "Your workflows.",
    intro: "A workflow is one named, repeating piece of work: what it reads, how it should be written, and the shape it comes out in. You run it when you want it, and nothing leaves until you approve it.",
    back: "Back to your account",
    add: "Add a workflow",
    edit: "Edit",
    remove: "Delete",
    removeConfirm: "Delete this workflow? Work it has already produced is kept.",
    empty: "No workflow yet. Add one and it appears on your account, ready to run.",
    limitReached: "You have five workflows, which is the limit. Delete one to add another.",
    nameLabel: "Name",
    namePlaceholder: "Weekly market note",
    purposeLabel: "Purpose, in one line",
    purposePlaceholder: "Turn this week's reading into a note I can act on.",
    briefLabel: "How it should be written. This is the workflow.",
    briefPlaceholder: "A short note, 120 to 180 words, plain sentences, no headings. Lead with the single most useful fact.",
    shapeLabel: "Shape",
    sourcesLabel: "Sources it always reads, one per line. Put feed in front of a feed address.",
    windowLabel: "How far back to read, in days",
    maxSourcesLabel: "Most sources per run",
    destinationLabel: "Where it is meant to go (optional)",
    destinationPlaceholder: "LinkedIn, or my inbox",
    activeLabel: "Ready to run",
    save: "Save workflow",
    saving: "Saving...",
    saved: "Saved",
    failed: "That did not save.",
    companyLabel: "Whose queue it files into",
    companyNone: "Nobody's — keep it to myself",
    cadenceLabel: "How often it runs itself",
    cadenceManual: "Only when I ask",
    cadenceDaily: "Every day",
    cadenceWeekly: "Every week",
    requiredActionLabel: "What it needs your approval for (optional)",
    requiredActionPlaceholder: "publish",
    scheduleNote: "A workflow only runs on its own once it files into a company. What it prepares always waits for you.",
    notYourCompany: "That is not a company you belong to.",
    budgetNote: "What a workflow may spend each month is set by MaydaLabs, not here.",
  },
  tr: {
    heading: "İş akışlarınız.",
    intro: "Bir iş akışı, tekrar eden tek bir iştir: neyi okuduğu, nasıl yazılması gerektiği ve hangi biçimde çıktığı. İstediğinizde çalıştırırsınız ve siz onaylamadan hiçbir şey çıkmaz.",
    back: "Hesabınıza dönün",
    add: "İş akışı ekleyin",
    edit: "Düzenle",
    remove: "Sil",
    removeConfirm: "Bu iş akışı silinsin mi? Şimdiye kadar ürettiği işler kalır.",
    empty: "Henüz iş akışı yok. Bir tane ekleyin; hesabınızda çalıştırılmaya hazır görünür.",
    limitReached: "Beş iş akışınız var, sınır bu. Yenisini eklemek için birini silin.",
    nameLabel: "Ad",
    namePlaceholder: "Haftalık piyasa notu",
    purposeLabel: "Amacı, tek cümlede",
    purposePlaceholder: "Bu haftanın okumalarını harekete geçebileceğim bir nota dönüştür.",
    briefLabel: "Nasıl yazılmalı? İş akışı budur.",
    briefPlaceholder: "Kısa bir not, 120-180 kelime, sade cümleler, başlık yok. En faydalı tek bilgiyle başla.",
    shapeLabel: "Biçim",
    sourcesLabel: "Her zaman okuduğu kaynaklar, her satıra bir tane. Besleme adresinin önüne feed yazın.",
    windowLabel: "Kaç gün geriye kadar okunsun?",
    maxSourcesLabel: "Çalıştırma başına en fazla kaynak",
    destinationLabel: "Nereye gidecek? (isteğe bağlı)",
    destinationPlaceholder: "LinkedIn veya gelen kutum",
    activeLabel: "Çalıştırmaya hazır",
    save: "İş akışını kaydet",
    saving: "Kaydediliyor...",
    saved: "Kaydedildi",
    failed: "Kaydedilemedi.",
    companyLabel: "Hangi sıraya düşsün",
    companyNone: "Hiçbirine — kendime saklayayım",
    cadenceLabel: "Kendi kendine ne sıklıkla çalışsın",
    cadenceManual: "Yalnızca ben istediğimde",
    cadenceDaily: "Her gün",
    cadenceWeekly: "Her hafta",
    requiredActionLabel: "Onayınızı ne için beklesin (isteğe bağlı)",
    requiredActionPlaceholder: "yayınla",
    scheduleNote: "Bir iş akışı ancak bir şirkete düştüğünde kendi kendine çalışır. Hazırladığı şey her zaman sizi bekler.",
    notYourCompany: "Bu, üyesi olduğunuz bir şirket değil.",
    budgetNote: "Bir iş akışının aylık harcama sınırını MaydaLabs belirler, burası değil.",
  },
  fr: {
    heading: "Vos flux.",
    intro: "Un flux est un travail nommé qui se répète : ce qu'il lit, comment il doit être écrit et la forme qu'il prend. Vous le lancez quand vous voulez, et rien ne sort avant votre validation.",
    back: "Retour à votre compte",
    add: "Ajouter un flux",
    edit: "Modifier",
    remove: "Supprimer",
    removeConfirm: "Supprimer ce flux ? Le travail déjà produit est conservé.",
    empty: "Aucun flux pour l'instant. Ajoutez-en un et il apparaîtra sur votre compte, prêt à être lancé.",
    limitReached: "Vous avez cinq flux, c'est la limite. Supprimez-en un pour en ajouter un autre.",
    nameLabel: "Nom",
    namePlaceholder: "Note de marché hebdomadaire",
    purposeLabel: "Objectif, en une ligne",
    purposePlaceholder: "Transformer les lectures de la semaine en une note exploitable.",
    briefLabel: "Comment cela doit être écrit. C'est le flux.",
    briefPlaceholder: "Une note courte, 120 à 180 mots, phrases simples, sans titres. Commencer par le fait le plus utile.",
    shapeLabel: "Format",
    sourcesLabel: "Sources lues à chaque fois, une par ligne. Écrivez feed devant une adresse de flux.",
    windowLabel: "Jusqu'à combien de jours en arrière",
    maxSourcesLabel: "Sources maximum par exécution",
    destinationLabel: "Où cela doit aller (facultatif)",
    destinationPlaceholder: "LinkedIn, ou ma boîte mail",
    activeLabel: "Prêt à être lancé",
    save: "Enregistrer le flux",
    saving: "Enregistrement...",
    saved: "Enregistré",
    failed: "L'enregistrement a échoué.",
    companyLabel: "Dans quelle file elle se range",
    companyNone: "Aucune — je la garde pour moi",
    cadenceLabel: "À quelle fréquence elle se lance seule",
    cadenceManual: "Seulement quand je le demande",
    cadenceDaily: "Chaque jour",
    cadenceWeekly: "Chaque semaine",
    requiredActionLabel: "Ce pour quoi elle attend votre accord (facultatif)",
    requiredActionPlaceholder: "publier",
    scheduleNote: "Une tâche ne se lance seule qu'une fois rangée dans une entreprise. Ce qu'elle prépare vous attend toujours.",
    notYourCompany: "Ce n'est pas une entreprise dont vous faites partie.",
    budgetNote: "Ce qu'un flux peut dépenser chaque mois est fixé par MaydaLabs, pas ici.",
  },
} as const satisfies Record<Locale, unknown>;

export type OsWorkflowCopy = (typeof OS_WORKFLOW_COPY)[Locale];

/* The co-founder itself: what needs you, and starting a company so there is
 * something for it to know. */
export const OS_COFOUNDER_COPY = {
  en: {
    kicker: "MaydaOS",
    heading: "What needs you.",
    clear: "Nothing needs you right now. When something does, it waits here rather than chasing you.",
    routes: { decide: "Waiting on your decision", finish: "Approved, waiting to be done", blocked: "Stuck", other: "Waiting" },
    approve: "Approve",
    sendBack: "Send back",
    noteLabel: "Note (optional)",
    startHeading: "Start with your company.",
    startIntro: "MaydaOS works from what it knows about you. Two lines is enough to begin, and you can change them whenever.",
    nameLabel: "Company name",
    whatLabel: "What you do, and who for",
    whatPlaceholder: "We build booking software for small hotels in Turkey.",
    start: "Start",
    starting: "Starting...",
    startFailed: "That did not work.",
    tooMany: "You already have three companies, which is the limit.",
  },
  tr: {
    kicker: "MaydaOS",
    heading: "Sizi bekleyenler.",
    clear: "Şu anda sizi bekleyen bir şey yok. Olduğunda peşinizden koşmaz, burada bekler.",
    routes: { decide: "Kararınızı bekliyor", finish: "Onaylandı, yapılmayı bekliyor", blocked: "Takıldı", other: "Bekliyor" },
    approve: "Onayla",
    sendBack: "Geri gönder",
    noteLabel: "Not (isteğe bağlı)",
    startHeading: "Şirketinizle başlayın.",
    startIntro: "MaydaOS sizin hakkınızda bildiklerinden çalışır. Başlamak için iki satır yeter; istediğiniz zaman değiştirirsiniz.",
    nameLabel: "Şirket adı",
    whatLabel: "Ne yapıyorsunuz, kimin için?",
    whatPlaceholder: "Türkiye'deki küçük oteller için rezervasyon yazılımı geliştiriyoruz.",
    start: "Başla",
    starting: "Başlatılıyor...",
    startFailed: "Bu işe yaramadı.",
    tooMany: "Zaten üç şirketiniz var, sınır bu.",
  },
  fr: {
    kicker: "MaydaOS",
    heading: "Ce qui vous attend.",
    clear: "Rien ne vous attend pour le moment. Quand ce sera le cas, cela patientera ici au lieu de vous courir après.",
    routes: { decide: "En attente de votre décision", finish: "Validé, en attente d'exécution", blocked: "Bloqué", other: "En attente" },
    approve: "Valider",
    sendBack: "Renvoyer",
    noteLabel: "Note (facultatif)",
    startHeading: "Commencez par votre entreprise.",
    startIntro: "MaydaOS travaille à partir de ce qu'il sait de vous. Deux lignes suffisent pour commencer, et vous pouvez les changer quand vous voulez.",
    nameLabel: "Nom de l'entreprise",
    whatLabel: "Ce que vous faites, et pour qui",
    whatPlaceholder: "Nous créons des logiciels de réservation pour de petits hôtels en Turquie.",
    start: "Commencer",
    starting: "Démarrage...",
    startFailed: "Cela n'a pas fonctionné.",
    tooMany: "Vous avez déjà trois entreprises, c'est la limite.",
  },
} as const satisfies Record<Locale, unknown>;

export type OsCofounderCopy = (typeof OS_COFOUNDER_COPY)[Locale];

/* The process surface: what is scheduled, what ran, what it cost. This is
 * the screen that makes MaydaOS read as a system rather than a set of pages,
 * so it says plainly what is true right now and never implies activity that
 * is not there. */
export const OS_ACTIVITY_COPY = {
  en: {
    kicker: "Running",
    heading: "What is working while you are gone.",
    empty: "Nothing runs on its own yet. Give a workflow a company and a schedule, and it will appear here.",
    manual: "Only when you ask",
    daily: "Every day",
    weekly: "Every week",
    dueNow: "Due now",
    dueIn: (hours: number) => (hours < 24 ? `Due in ${hours}h` : `Due in ${Math.round(hours / 24)}d`),
    off: "Switched off",
    paused: "Paused",
    lastRun: "Last run",
    lastNever: "Has not run yet",
    ranOk: "prepared something",
    ranFailed: "could not finish",
    spend: (spent: string, budget: string) => `${spent} of ${budget} this month`,
    manage: "Set up workflows",
  },
  tr: {
    kicker: "Çalışıyor",
    heading: "Siz yokken çalışanlar.",
    empty: "Henüz kendi kendine çalışan bir şey yok. Bir iş akışına şirket ve program verin, burada görünsün.",
    manual: "Yalnızca siz istediğinizde",
    daily: "Her gün",
    weekly: "Her hafta",
    dueNow: "Şimdi sırada",
    dueIn: (hours: number) => (hours < 24 ? `${hours} saat sonra` : `${Math.round(hours / 24)} gün sonra`),
    off: "Kapalı",
    paused: "Duraklatıldı",
    lastRun: "Son çalışma",
    lastNever: "Henüz çalışmadı",
    ranOk: "bir şey hazırladı",
    ranFailed: "tamamlayamadı",
    spend: (spent: string, budget: string) => `Bu ay ${budget} bütçenin ${spent} kadarı`,
    manage: "İş akışlarını düzenle",
  },
  fr: {
    kicker: "En cours",
    heading: "Ce qui travaille pendant votre absence.",
    empty: "Rien ne se lance encore tout seul. Donnez à une tâche une entreprise et un rythme, et elle apparaîtra ici.",
    manual: "Seulement quand vous le demandez",
    daily: "Chaque jour",
    weekly: "Chaque semaine",
    dueNow: "À faire maintenant",
    dueIn: (hours: number) => (hours < 24 ? `Dans ${hours} h` : `Dans ${Math.round(hours / 24)} j`),
    off: "Désactivée",
    paused: "En pause",
    lastRun: "Dernière exécution",
    lastNever: "Jamais exécutée",
    ranOk: "a préparé quelque chose",
    ranFailed: "n'a pas pu terminer",
    spend: (spent: string, budget: string) => `${spent} sur ${budget} ce mois-ci`,
    manage: "Configurer les tâches",
  },
} as const;

export type OsActivityCopy = (typeof OS_ACTIVITY_COPY)[Locale];
