import type { Locale } from "@/lib/i18n";

/* MaydaOS, client-facing.
 *
 * Every value here is a plain string, including the ones with numbers in
 * them: this object crosses into a client component, and a function cannot
 * make that trip. */

export function fillBudget(template: string, spent: string, budget: string): string {
  return template.replace("{spent}", spent).replace("{budget}", budget);
}

export const OS_DESK_COPY = {
  en: {
    kicker: "MaydaOS",
    heading: "Work waiting for you.",
    produceHeading: "Produce the next piece",
    budgetLine: "{spent} of {budget} used this month",
    budgetNote: "Reading sources, editing, approving and sending back cost nothing. Only producing a draft does.",
    topicLabel: "What is this about?",
    topicPlaceholder: "e.g. What changed in EU stablecoin rules this month",
    workflowLabel: "Workflow",
    shapeLabel: "Shape",
    shapes: { note: "Short note", post: "LinkedIn post", summary: "Summary of the sources" },
    sourcesLabel: "Sources (one link per line, up to 5)",
    run: "Run",
    running: "Reading the sources...",
    runsHeading: "Recent work",
    historyLink: "Everything that happened",
    empty: "Nothing yet. Add a link and press run.",
    draftLabel: "Draft",
    claimsLabel: "Every claim, next to its source",
    unsourced: "No source. Check this before approving.",
    copy: "Copy the draft",
    copied: "Copied",
    outcomeLabel: "Where did it go?",
    outcomeNote: "Paste the public link once you have posted or sent it. MaydaOS never posts anything itself.",
    outcomeSave: "Save the link",
    approve: "Approve",
    reject: "Send back",
    noteLabel: "Note (optional)",
    decisions: { pending: "Waiting for you", approved: "Approved by you", rejected: "Sent back" },
    outOfHeading: "This workflow has used its budget for the month.",
    outOfBody: "Everything already produced stays here, and it is yours. The budget resets on the first of the month.",
    noWorkflow: "No workflow yet. Set one up and it appears here, ready to run.",
    setUp: "Set up your workflows",
    notConfigured: "Running is switched off at the moment. Your workflows and everything already produced are safe.",
    failed: "This run failed and cost nothing.",
  },
  tr: {
    kicker: "MaydaOS",
    heading: "Sizi bekleyen iş.",
    produceHeading: "Sonraki işi üretin",
    budgetLine: "Bu ay {budget} bütçenin {spent} kadarı kullanıldı",
    budgetNote: "Kaynakları okumak, düzenlemek, onaylamak ve geri göndermek ücretsizdir. Yalnızca taslak üretmek maliyet oluşturur.",
    topicLabel: "Konu nedir?",
    topicPlaceholder: "örn. Bu ay AB stablecoin kurallarında ne değişti",
    workflowLabel: "İş akışı",
    shapeLabel: "Biçim",
    shapes: { note: "Kısa not", post: "LinkedIn gönderisi", summary: "Kaynakların özeti" },
    sourcesLabel: "Kaynaklar (her satıra bir bağlantı, en fazla 5)",
    run: "Çalıştır",
    running: "Kaynaklar okunuyor...",
    runsHeading: "Son işler",
    historyLink: "Olan biten her şey",
    empty: "Henüz bir şey yok. Bir bağlantı ekleyip çalıştırın.",
    draftLabel: "Taslak",
    claimsLabel: "Her iddia, kaynağının yanında",
    unsourced: "Kaynak yok. Onaylamadan önce kontrol edin.",
    copy: "Taslağı kopyala",
    copied: "Kopyalandı",
    outcomeLabel: "Nereye gitti?",
    outcomeNote: "Yayınladıktan veya gönderdikten sonra herkese açık bağlantıyı yapıştırın. MaydaOS hiçbir şeyi kendisi yayınlamaz.",
    outcomeSave: "Bağlantıyı kaydet",
    approve: "Onayla",
    reject: "Geri gönder",
    noteLabel: "Not (isteğe bağlı)",
    decisions: { pending: "Sizi bekliyor", approved: "Onayladınız", rejected: "Geri gönderildi" },
    outOfHeading: "Bu iş akışı bu ayki bütçesini kullandı.",
    outOfBody: "Üretilen her şey burada kalıyor ve size ait. Bütçe ayın birinde yenilenir.",
    noWorkflow: "Henüz iş akışı yok. Bir tane kurun; burada çalıştırılmaya hazır görünür.",
    setUp: "İş akışlarınızı kurun",
    notConfigured: "Çalıştırma şu anda kapalı. İş akışlarınız ve üretilmiş her şey yerinde duruyor.",
    failed: "Bu çalıştırma başarısız oldu ve bir maliyeti olmadı.",
  },
  fr: {
    kicker: "MaydaOS",
    heading: "Le travail qui vous attend.",
    produceHeading: "Produire la pièce suivante",
    budgetLine: "{spent} sur {budget} utilisés ce mois-ci",
    budgetNote: "Lire les sources, éditer, approuver et renvoyer ne coûtent rien. Seule la production d'un brouillon a un coût.",
    topicLabel: "De quoi s'agit-il ?",
    topicPlaceholder: "ex. Ce qui a changé dans les règles européennes ce mois-ci",
    workflowLabel: "Flux",
    shapeLabel: "Format",
    shapes: { note: "Note courte", post: "Post LinkedIn", summary: "Résumé des sources" },
    sourcesLabel: "Sources (un lien par ligne, 5 maximum)",
    run: "Exécuter",
    running: "Lecture des sources...",
    runsHeading: "Travaux récents",
    historyLink: "Tout ce qui s'est passé",
    empty: "Rien pour l'instant. Ajoutez un lien et lancez.",
    draftLabel: "Brouillon",
    claimsLabel: "Chaque affirmation, à côté de sa source",
    unsourced: "Aucune source. Vérifiez avant d'approuver.",
    copy: "Copier le brouillon",
    copied: "Copié",
    outcomeLabel: "Où est-ce parti ?",
    outcomeNote: "Collez le lien public une fois publié ou envoyé. MaydaOS ne publie jamais rien lui-même.",
    outcomeSave: "Enregistrer le lien",
    approve: "Approuver",
    reject: "Renvoyer",
    noteLabel: "Note (facultatif)",
    decisions: { pending: "En attente de vous", approved: "Approuvé par vous", rejected: "Renvoyé" },
    outOfHeading: "Ce flux a utilisé son budget du mois.",
    outOfBody: "Tout ce qui a été produit reste ici et vous appartient. Le budget repart le premier du mois.",
    noWorkflow: "Aucun flux pour l'instant. Créez-en un et il apparaîtra ici, prêt à être lancé.",
    setUp: "Configurer vos flux",
    notConfigured: "L'exécution est désactivée pour le moment. Vos flux et tout ce qui a déjà été produit sont intacts.",
    failed: "Cette exécution a échoué et n'a rien coûté.",
  },
} as const satisfies Record<Locale, unknown>;

export type OsDeskCopy = (typeof OS_DESK_COPY)[Locale];

/* Setting up your own workflow. A member names the work, says what it reads
 * and how it should be written; the key, the budget and the owner are not
 * theirs to choose and are not asked for here. */
export const OS_WORKFLOW_COPY = {
  en: {
    heading: "Your workflows.",
    intro: "A workflow is one named, repeating piece of work: what it reads, how it should be written, and the shape it comes out in. You run it when you want it, and nothing leaves until you approve it.",
    back: "Back to your account",
    add: "Add a workflow",
    change: "Change this workflow",
    edit: "Edit",
    remove: "Delete",
    removeConfirm: "Delete this workflow? Work it has already produced is kept.",
    empty: "No workflow yet. Add one and it appears on your account, ready to run.",
    limitReached: "You have five workflows, which is the limit. Delete one to add another.",
    nameLabel: "Name",
    namePlaceholder: "Weekly market note",
    purposeLabel: "Purpose, in one line",
    purposePlaceholder: "Turn this week's reading into a note I can act on.",
    briefLabel: "How it should be written. This is the workflow.",
    briefPlaceholder: "A short note, 120 to 180 words, plain sentences, no headings. Lead with the single most useful fact.",
    shapeLabel: "Shape",
    sourcesLabel: "Sources it always reads, one per line. Put feed in front of a feed address.",
    windowLabel: "How far back to read, in days",
    maxSourcesLabel: "Most sources per run",
    destinationLabel: "Where it is meant to go (optional)",
    destinationPlaceholder: "LinkedIn, or my inbox",
    activeLabel: "Ready to run",
    save: "Save workflow",
    saving: "Saving...",
    saved: "Saved",
    failed: "That did not save.",
    companyLabel: "Whose queue it files into",
    companyNone: "Nobody's — keep it to myself",
    cadenceLabel: "How often it runs itself",
    cadenceManual: "Only when I ask",
    cadenceDaily: "Every day",
    cadenceWeekly: "Every week",
    requiredActionLabel: "What it needs your approval for (optional)",
    requiredActionPlaceholder: "publish",
    scheduleNote: "A workflow only runs on its own once it files into a company. What it prepares always waits for you.",
    notYourCompany: "That is not a company you belong to.",
    budgetNote: "What a workflow may spend each month is set by MaydaLabs, not here.",
  },
  tr: {
    heading: "İş akışlarınız.",
    intro: "Bir iş akışı, tekrar eden tek bir iştir: neyi okuduğu, nasıl yazılması gerektiği ve hangi biçimde çıktığı. İstediğinizde çalıştırırsınız ve siz onaylamadan hiçbir şey çıkmaz.",
    back: "Hesabınıza dönün",
    add: "İş akışı ekleyin",
    change: "Bu iş akışını değiştir",
    edit: "Düzenle",
    remove: "Sil",
    removeConfirm: "Bu iş akışı silinsin mi? Şimdiye kadar ürettiği işler kalır.",
    empty: "Henüz iş akışı yok. Bir tane ekleyin; hesabınızda çalıştırılmaya hazır görünür.",
    limitReached: "Beş iş akışınız var, sınır bu. Yenisini eklemek için birini silin.",
    nameLabel: "Ad",
    namePlaceholder: "Haftalık piyasa notu",
    purposeLabel: "Amacı, tek cümlede",
    purposePlaceholder: "Bu haftanın okumalarını harekete geçebileceğim bir nota dönüştür.",
    briefLabel: "Nasıl yazılmalı? İş akışı budur.",
    briefPlaceholder: "Kısa bir not, 120-180 kelime, sade cümleler, başlık yok. En faydalı tek bilgiyle başla.",
    shapeLabel: "Biçim",
    sourcesLabel: "Her zaman okuduğu kaynaklar, her satıra bir tane. Besleme adresinin önüne feed yazın.",
    windowLabel: "Kaç gün geriye kadar okunsun?",
    maxSourcesLabel: "Çalıştırma başına en fazla kaynak",
    destinationLabel: "Nereye gidecek? (isteğe bağlı)",
    destinationPlaceholder: "LinkedIn veya gelen kutum",
    activeLabel: "Çalıştırmaya hazır",
    save: "İş akışını kaydet",
    saving: "Kaydediliyor...",
    saved: "Kaydedildi",
    failed: "Kaydedilemedi.",
    companyLabel: "Hangi sıraya düşsün",
    companyNone: "Hiçbirine — kendime saklayayım",
    cadenceLabel: "Kendi kendine ne sıklıkla çalışsın",
    cadenceManual: "Yalnızca ben istediğimde",
    cadenceDaily: "Her gün",
    cadenceWeekly: "Her hafta",
    requiredActionLabel: "Onayınızı ne için beklesin (isteğe bağlı)",
    requiredActionPlaceholder: "yayınla",
    scheduleNote: "Bir iş akışı ancak bir şirkete düştüğünde kendi kendine çalışır. Hazırladığı şey her zaman sizi bekler.",
    notYourCompany: "Bu, üyesi olduğunuz bir şirket değil.",
    budgetNote: "Bir iş akışının aylık harcama sınırını MaydaLabs belirler, burası değil.",
  },
  fr: {
    heading: "Vos flux.",
    intro: "Un flux est un travail nommé qui se répète : ce qu'il lit, comment il doit être écrit et la forme qu'il prend. Vous le lancez quand vous voulez, et rien ne sort avant votre validation.",
    back: "Retour à votre compte",
    add: "Ajouter un flux",
    change: "Modifier ce flux",
    edit: "Modifier",
    remove: "Supprimer",
    removeConfirm: "Supprimer ce flux ? Le travail déjà produit est conservé.",
    empty: "Aucun flux pour l'instant. Ajoutez-en un et il apparaîtra sur votre compte, prêt à être lancé.",
    limitReached: "Vous avez cinq flux, c'est la limite. Supprimez-en un pour en ajouter un autre.",
    nameLabel: "Nom",
    namePlaceholder: "Note de marché hebdomadaire",
    purposeLabel: "Objectif, en une ligne",
    purposePlaceholder: "Transformer les lectures de la semaine en une note exploitable.",
    briefLabel: "Comment cela doit être écrit. C'est le flux.",
    briefPlaceholder: "Une note courte, 120 à 180 mots, phrases simples, sans titres. Commencer par le fait le plus utile.",
    shapeLabel: "Format",
    sourcesLabel: "Sources lues à chaque fois, une par ligne. Écrivez feed devant une adresse de flux.",
    windowLabel: "Jusqu'à combien de jours en arrière",
    maxSourcesLabel: "Sources maximum par exécution",
    destinationLabel: "Où cela doit aller (facultatif)",
    destinationPlaceholder: "LinkedIn, ou ma boîte mail",
    activeLabel: "Prêt à être lancé",
    save: "Enregistrer le flux",
    saving: "Enregistrement...",
    saved: "Enregistré",
    failed: "L'enregistrement a échoué.",
    companyLabel: "Dans quelle file elle se range",
    companyNone: "Aucune — je la garde pour moi",
    cadenceLabel: "À quelle fréquence elle se lance seule",
    cadenceManual: "Seulement quand je le demande",
    cadenceDaily: "Chaque jour",
    cadenceWeekly: "Chaque semaine",
    requiredActionLabel: "Ce pour quoi elle attend votre accord (facultatif)",
    requiredActionPlaceholder: "publier",
    scheduleNote: "Une tâche ne se lance seule qu'une fois rangée dans une entreprise. Ce qu'elle prépare vous attend toujours.",
    notYourCompany: "Ce n'est pas une entreprise dont vous faites partie.",
    budgetNote: "Ce qu'un flux peut dépenser chaque mois est fixé par MaydaLabs, pas ici.",
  },
} as const satisfies Record<Locale, unknown>;

export type OsWorkflowCopy = (typeof OS_WORKFLOW_COPY)[Locale];

/* The co-founder itself: what needs you, and starting a company so there is
 * something for it to know. */
export const OS_COFOUNDER_COPY = {
  en: {
    kicker: "MaydaOS",
    openOs: "Open MaydaOS →",
    heading: "What needs you.",
    clear: "Nothing needs you right now. When something does, it waits here rather than chasing you.",
    routes: { decide: "Waiting on your decision", finish: "Approved, waiting to be done", blocked: "Stuck", other: "Waiting" },
    approve: "Approve",
    sendBack: "Send back",
    noteLabel: "Note (optional)",
    startHeading: "Start with your company.",
    startIntro: "MaydaOS works from what it knows about you. Two lines is enough to begin, and you can change them whenever.",
    nameLabel: "Company name",
    whatLabel: "What you do, and who for",
    whatPlaceholder: "We build booking software for small hotels in Turkey.",
    start: "Start",
    starting: "Starting...",
    startFailed: "That did not work.",
    tooMany: "You already have three companies, which is the limit.",
  },
  tr: {
    kicker: "MaydaOS",
    openOs: "MaydaOS'u aç →",
    heading: "Sizi bekleyenler.",
    clear: "Şu anda sizi bekleyen bir şey yok. Olduğunda peşinizden koşmaz, burada bekler.",
    routes: { decide: "Kararınızı bekliyor", finish: "Onaylandı, yapılmayı bekliyor", blocked: "Takıldı", other: "Bekliyor" },
    approve: "Onayla",
    sendBack: "Geri gönder",
    noteLabel: "Not (isteğe bağlı)",
    startHeading: "Şirketinizle başlayın.",
    startIntro: "MaydaOS sizin hakkınızda bildiklerinden çalışır. Başlamak için iki satır yeter; istediğiniz zaman değiştirirsiniz.",
    nameLabel: "Şirket adı",
    whatLabel: "Ne yapıyorsunuz, kimin için?",
    whatPlaceholder: "Türkiye'deki küçük oteller için rezervasyon yazılımı geliştiriyoruz.",
    start: "Başla",
    starting: "Başlatılıyor...",
    startFailed: "Bu işe yaramadı.",
    tooMany: "Zaten üç şirketiniz var, sınır bu.",
  },
  fr: {
    kicker: "MaydaOS",
    openOs: "Ouvrir MaydaOS →",
    heading: "Ce qui vous attend.",
    clear: "Rien ne vous attend pour le moment. Quand ce sera le cas, cela patientera ici au lieu de vous courir après.",
    routes: { decide: "En attente de votre décision", finish: "Validé, en attente d'exécution", blocked: "Bloqué", other: "En attente" },
    approve: "Valider",
    sendBack: "Renvoyer",
    noteLabel: "Note (facultatif)",
    startHeading: "Commencez par votre entreprise.",
    startIntro: "MaydaOS travaille à partir de ce qu'il sait de vous. Deux lignes suffisent pour commencer, et vous pouvez les changer quand vous voulez.",
    nameLabel: "Nom de l'entreprise",
    whatLabel: "Ce que vous faites, et pour qui",
    whatPlaceholder: "Nous créons des logiciels de réservation pour de petits hôtels en Turquie.",
    start: "Commencer",
    starting: "Démarrage...",
    startFailed: "Cela n'a pas fonctionné.",
    tooMany: "Vous avez déjà trois entreprises, c'est la limite.",
  },
} as const satisfies Record<Locale, unknown>;

export type OsCofounderCopy = (typeof OS_COFOUNDER_COPY)[Locale];

/* The process surface: what is scheduled, what ran, what it cost. This is
 * the screen that makes MaydaOS read as a system rather than a set of pages,
 * so it says plainly what is true right now and never implies activity that
 * is not there. */
export const OS_ACTIVITY_COPY = {
  en: {
    kicker: "Running",
    heading: "What is working while you are gone.",
    empty: "Nothing runs on its own yet. Give a workflow a company and a schedule, and it will appear here.",
    manual: "Only when you ask",
    daily: "Every day",
    weekly: "Every week",
    dueNow: "Due now",
    dueIn: (hours: number) => (hours < 24 ? `Due in ${hours}h` : `Due in ${Math.round(hours / 24)}d`),
    off: "Switched off",
    paused: "Paused",
    lastRun: "Last run",
    lastNever: "Has not run yet",
    ranOk: "prepared something",
    ranFailed: "could not finish",
    spend: (spent: string, budget: string) => `${spent} of ${budget} this month`,
    manage: "Set up workflows",
  },
  tr: {
    kicker: "Çalışıyor",
    heading: "Siz yokken çalışanlar.",
    empty: "Henüz kendi kendine çalışan bir şey yok. Bir iş akışına şirket ve program verin, burada görünsün.",
    manual: "Yalnızca siz istediğinizde",
    daily: "Her gün",
    weekly: "Her hafta",
    dueNow: "Şimdi sırada",
    dueIn: (hours: number) => (hours < 24 ? `${hours} saat sonra` : `${Math.round(hours / 24)} gün sonra`),
    off: "Kapalı",
    paused: "Duraklatıldı",
    lastRun: "Son çalışma",
    lastNever: "Henüz çalışmadı",
    ranOk: "bir şey hazırladı",
    ranFailed: "tamamlayamadı",
    spend: (spent: string, budget: string) => `Bu ay ${budget} bütçenin ${spent} kadarı`,
    manage: "İş akışlarını düzenle",
  },
  fr: {
    kicker: "En cours",
    heading: "Ce qui travaille pendant votre absence.",
    empty: "Rien ne se lance encore tout seul. Donnez à une tâche une entreprise et un rythme, et elle apparaîtra ici.",
    manual: "Seulement quand vous le demandez",
    daily: "Chaque jour",
    weekly: "Chaque semaine",
    dueNow: "À faire maintenant",
    dueIn: (hours: number) => (hours < 24 ? `Dans ${hours} h` : `Dans ${Math.round(hours / 24)} j`),
    off: "Désactivée",
    paused: "En pause",
    lastRun: "Dernière exécution",
    lastNever: "Jamais exécutée",
    ranOk: "a préparé quelque chose",
    ranFailed: "n'a pas pu terminer",
    spend: (spent: string, budget: string) => `${spent} sur ${budget} ce mois-ci`,
    manage: "Configurer les tâches",
  },
} as const;

export type OsActivityCopy = (typeof OS_ACTIVITY_COPY)[Locale];

/* The desktop's own words. Small on purpose: an operating system that
 * explains itself constantly is one nobody has learned. */
export const OS_SHELL_COPY = {
  en: {
    desktop: "Desktop",
    today: "Today",
    empty: "Nothing open.",
    emptyHint: "Pick something from the dock below.",
    waiting: (count: number) =>
      count === 0 ? "Nothing waiting" : count === 1 ? "1 waiting on you" : `${count} waiting on you`,
    close: "Close",
    minimize: "Put away",
    resize: "Resize",
    leftHalf: "Left half",
    rightHalf: "Right half",
    fill: "Fill the desk",
    signedInAs: "Signed in as",
    noCompany: "No company yet",
    leave: "Leave",
    commandPlaceholder: "Search, or say something.",
    commandAsk: "Ask the co-founder:",
    commandTell: "Tell it:",
    commandAdd: "Add to work:",
    commandLane: "Which part of the business?",
    commandOpen: "Open",
    commandNothing: "Nothing matches that.",
    commandHint: "↑↓ to choose · ↵ to run · esc to close",
    commandButton: "Search",
    newSince: "new",
    markSeen: "Mark seen",
    seen: "Seen.",
    theme: "Instrument",
    themeOther: "Quiet desk",
    apps: { needsYou: "Needs you", running: "Running", company: "Company" },
    companyHeading: "What it knows about you.",
    companyNothing: "You have not started a company yet. Do that on your account page and this fills in.",
    companyWhat: "What you do",
    companyWhatMissing: "Not written down yet.",
    companyPeople: "People",
    companyOwner: "owner",
    companyMember: "member",
    companySince: "Since",
  },
  tr: {
    desktop: "Masaüstü",
    today: "Bugün",
    empty: "Açık bir şey yok.",
    emptyHint: "Aşağıdaki çubuktan birini seçin.",
    waiting: (count: number) =>
      count === 0 ? "Bekleyen yok" : `Sizi bekleyen ${count}`,
    close: "Kapat",
    minimize: "Kaldır",
    resize: "Yeniden boyutlandır",
    leftHalf: "Sol yarı",
    rightHalf: "Sağ yarı",
    fill: "Masayı doldur",
    signedInAs: "Giriş yapan",
    noCompany: "Henüz şirket yok",
    leave: "Çık",
    commandPlaceholder: "Arayın ya da bir şey söyleyin.",
    commandAsk: "Kurucu ortağa sor:",
    commandTell: "Ona söyle:",
    commandAdd: "İşe ekle:",
    commandLane: "İşin hangi kısmı?",
    commandOpen: "Aç",
    commandNothing: "Eşleşen bir şey yok.",
    commandHint: "Seçmek için ↑↓ · çalıştırmak için ↵ · kapatmak için esc",
    commandButton: "Ara",
    newSince: "yeni",
    markSeen: "Görüldü",
    seen: "Görüldü.",
    theme: "Enstrüman",
    themeOther: "Sakin masa",
    apps: { needsYou: "Sizi bekleyen", running: "Çalışan", company: "Şirket" },
    companyHeading: "Sizin hakkınızda bildikleri.",
    companyNothing: "Henüz bir şirket kurmadınız. Hesap sayfanızdan kurun, burası dolsun.",
    companyWhat: "Ne yapıyorsunuz",
    companyWhatMissing: "Henüz yazılmamış.",
    companyPeople: "Kişiler",
    companyOwner: "sahip",
    companyMember: "üye",
    companySince: "Başlangıç",
  },
  fr: {
    desktop: "Bureau",
    today: "Aujourd'hui",
    empty: "Rien d'ouvert.",
    emptyHint: "Choisissez quelque chose dans la barre ci-dessous.",
    waiting: (count: number) =>
      count === 0 ? "Rien en attente" : count === 1 ? "1 en attente de vous" : `${count} en attente de vous`,
    close: "Fermer",
    minimize: "Ranger",
    resize: "Redimensionner",
    leftHalf: "Moitié gauche",
    rightHalf: "Moitié droite",
    fill: "Remplir le bureau",
    signedInAs: "Connecté en tant que",
    noCompany: "Pas encore d'entreprise",
    leave: "Quitter",
    commandPlaceholder: "Cherchez, ou dites quelque chose.",
    commandAsk: "Demander au cofondateur :",
    commandTell: "Lui dire :",
    commandAdd: "Ajouter au travail :",
    commandLane: "Quelle partie de l'entreprise ?",
    commandOpen: "Ouvrir",
    commandNothing: "Rien ne correspond.",
    commandHint: "↑↓ pour choisir · ↵ pour lancer · échap pour fermer",
    commandButton: "Chercher",
    newSince: "nouveau",
    markSeen: "Vu",
    seen: "Vu.",
    theme: "Instrument",
    themeOther: "Bureau calme",
    apps: { needsYou: "Pour vous", running: "En cours", company: "Entreprise" },
    companyHeading: "Ce qu'il sait de vous.",
    companyNothing: "Vous n'avez pas encore créé d'entreprise. Faites-le depuis votre compte et ceci se remplira.",
    companyWhat: "Ce que vous faites",
    companyWhatMissing: "Pas encore noté.",
    companyPeople: "Personnes",
    companyOwner: "propriétaire",
    companyMember: "membre",
    companySince: "Depuis",
  },
} as const;

export type OsShellCopyStrings = (typeof OS_SHELL_COPY)[Locale];

/* Settings. The choices are named things, never values: a person picks
 * "Ember", not a hex code, so what is stored is one of a few words. */
export const OS_SETTINGS_COPY = {
  en: {
    title: "Settings",
    wallpaper: "Wallpaper",
    moods: { lamp: "Lamp", ember: "Ember", sea: "Sea", plain: "Plain" } as Record<string, string>,
    accent: "Accent",
    accents: { periwinkle: "Periwinkle", amber: "Amber", mint: "Mint", rose: "Rose" } as Record<string, string>,
    language: "Language",
    languages: { en: "English", tr: "Türkçe", fr: "Français" } as Record<string, string>,
    desk: "The desk",
    resetLayout: "Put every window back where it started",
    install: "On your Mac",
    installBody: "MaydaOS can live in your Dock as an app of its own, in its own window, without the browser around it.",
    installButton: "Install MaydaOS",
    installHint: "In Safari: File → Add to Dock. In Chrome: the install icon at the right of the address bar.",
    installed: "Installed. It is in your Dock.",
    account: "Account",
    signedInAs: "Signed in as {email}",
    signOut: "Sign out",
  },
  tr: {
    title: "Ayarlar",
    wallpaper: "Duvar kağıdı",
    moods: { lamp: "Lamba", ember: "Kor", sea: "Deniz", plain: "Sade" } as Record<string, string>,
    accent: "Vurgu rengi",
    accents: { periwinkle: "Mor-mavi", amber: "Kehribar", mint: "Nane", rose: "Gül" } as Record<string, string>,
    language: "Dil",
    languages: { en: "English", tr: "Türkçe", fr: "Français" } as Record<string, string>,
    desk: "Masa",
    resetLayout: "Bütün pencereleri başlangıç yerine koy",
    install: "Mac'inizde",
    installBody: "MaydaOS, tarayıcı olmadan, kendi penceresinde, Dock'unuzda ayrı bir uygulama olarak durabilir.",
    installButton: "MaydaOS'u kur",
    installHint: "Safari'de: Dosya → Dock'a Ekle. Chrome'da: adres çubuğunun sağındaki kurulum simgesi.",
    installed: "Kuruldu. Dock'unuzda.",
    account: "Hesap",
    signedInAs: "{email} olarak giriş yapıldı",
    signOut: "Çıkış yap",
  },
  fr: {
    title: "Réglages",
    wallpaper: "Fond d'écran",
    moods: { lamp: "Lampe", ember: "Braise", sea: "Mer", plain: "Uni" } as Record<string, string>,
    accent: "Couleur d'accent",
    accents: { periwinkle: "Pervenche", amber: "Ambre", mint: "Menthe", rose: "Rose" } as Record<string, string>,
    language: "Langue",
    languages: { en: "English", tr: "Türkçe", fr: "Français" } as Record<string, string>,
    desk: "Le bureau",
    resetLayout: "Remettre chaque fenêtre à sa place d'origine",
    install: "Sur votre Mac",
    installBody: "MaydaOS peut vivre dans votre Dock comme une application à part entière, dans sa propre fenêtre, sans le navigateur autour.",
    installButton: "Installer MaydaOS",
    installHint: "Dans Safari : Fichier → Ajouter au Dock. Dans Chrome : l'icône d'installation à droite de la barre d'adresse.",
    installed: "Installé. C'est dans votre Dock.",
    account: "Compte",
    signedInAs: "Connecté en tant que {email}",
    signOut: "Se déconnecter",
  },
} as const;

/* The brief. The desk's first words, computed from the record rather than
 * written by anyone — so every sentence here has a count or a name in it, and
 * none of them promises more than the database can show. Plain strings; the
 * counts are filled in on the server. */
export const OS_BRIEF_COPY = {
  en: {
    needs: { none: "Nothing needs you.", one: "One thing needs you.", many: "{n} things need you." },
    changes: {
      none: "Nothing has changed since you last looked.",
      one: "One thing changed since you last looked.",
      many: "{n} things changed since you last looked.",
    },
    lastChange: "Last: {who} {event} “{title}”.",
    nextNone: "Nothing runs on its own yet.",
    nextDue: "{name} runs {when}.",
    nextSoon: "{name} runs within the hour.",
    nextPaused: "{name} is paused.",
    finished: {
      none: "Nothing finished this fortnight.",
      one: "One thing finished this fortnight.",
      many: "{n} things finished this fortnight.",
    },
    more: "and {n} more in {app}",
    emptyHint: "Add something in Work, or tell it what to look into.",
    due: "Due",
    dueToday: "due today",
    dueTomorrow: "due tomorrow",
    overdue: { one: "a day overdue", many: "{n} days overdue" },
  },
  tr: {
    needs: { none: "Sizi bekleyen bir şey yok.", one: "Bir şey sizi bekliyor.", many: "{n} şey sizi bekliyor." },
    changes: {
      none: "Son baktığınızdan beri bir şey değişmedi.",
      one: "Son baktığınızdan beri bir şey değişti.",
      many: "Son baktığınızdan beri {n} şey değişti.",
    },
    lastChange: "Son: {who} “{title}” {event}.",
    nextNone: "Henüz kendi başına çalışan bir şey yok.",
    nextDue: "{name} {when} çalışacak.",
    nextSoon: "{name} bir saat içinde çalışacak.",
    nextPaused: "{name} duraklatıldı.",
    finished: {
      none: "Bu iki haftada biten bir şey yok.",
      one: "Bu iki haftada bir şey bitti.",
      many: "Bu iki haftada {n} şey bitti.",
    },
    more: "ve {app} içinde {n} tane daha",
    emptyHint: "İş'e bir şey ekleyin ya da ona neye bakacağını söyleyin.",
    due: "Son tarih",
    dueToday: "bugün",
    dueTomorrow: "yarın",
    overdue: { one: "bir gün gecikti", many: "{n} gün gecikti" },
  },
  fr: {
    needs: { none: "Rien ne vous attend.", one: "Une chose vous attend.", many: "{n} choses vous attendent." },
    changes: {
      none: "Rien n'a changé depuis votre dernier passage.",
      one: "Une chose a changé depuis votre dernier passage.",
      many: "{n} choses ont changé depuis votre dernier passage.",
    },
    lastChange: "Dernier : {who} {event} « {title} ».",
    nextNone: "Rien ne tourne encore tout seul.",
    nextDue: "{name} tourne {when}.",
    nextSoon: "{name} tourne dans l'heure.",
    nextPaused: "{name} est en pause.",
    finished: {
      none: "Rien de terminé ces deux dernières semaines.",
      one: "Une chose terminée ces deux dernières semaines.",
      many: "{n} choses terminées ces deux dernières semaines.",
    },
    more: "et {n} de plus dans {app}",
    emptyHint: "Ajoutez quelque chose dans Travail, ou dites-lui quoi regarder.",
    due: "Échéance",
    dueToday: "pour aujourd'hui",
    dueTomorrow: "pour demain",
    overdue: { one: "un jour de retard", many: "{n} jours de retard" },
  },
} as const;

/* The conversation's own words. Plain strings only: this copy crosses into a
 * client component. */
export const OS_COFOUNDER_CHAT_COPY = {
  en: {
    title: "Co-founder",
    placeholder: "Ask, or tell it what to look into.",
    send: "Send",
    sending: "Thinking...",
    empty: "It knows your company.",
    emptyHint: "Ask what is open, what you decided, or what it would do next. It can put work in your queue, and it cannot approve any of it.",
    filed: 'Filed "{title}" — it is in your queue and waiting for you.',
    learned: "Noted: {fact}",
    failed: "That did not get through.",
    budget: "This month's conversation budget is spent.",
    notConfigured: "The co-founder is not switched on yet.",
    noCompany: "Start a company first and it will have something to know.",
  },
  tr: {
    title: "Kurucu ortak",
    placeholder: "Sorun ya da neye bakmasını istediğinizi söyleyin.",
    send: "Gönder",
    sending: "Düşünüyor...",
    empty: "Şirketinizi biliyor.",
    emptyHint: "Neyin açık olduğunu, ne karar verdiğinizi ya da sırada ne yapacağını sorun. İşinizi sıraya koyabilir, ama hiçbirini onaylayamaz.",
    filed: '"{title}" sıraya kondu — sizi bekliyor.',
    learned: "Not edildi: {fact}",
    failed: "Bu iletilemedi.",
    budget: "Bu ayki konuşma bütçesi doldu.",
    notConfigured: "Kurucu ortak henüz açık değil.",
    noCompany: "Önce bir şirket kurun, bilecek bir şeyi olsun.",
  },
  fr: {
    title: "Cofondateur",
    placeholder: "Demandez, ou dites-lui quoi examiner.",
    send: "Envoyer",
    sending: "Réflexion...",
    empty: "Il connaît votre entreprise.",
    emptyHint: "Demandez ce qui est ouvert, ce que vous avez décidé, ou ce qu'il ferait ensuite. Il peut mettre du travail dans votre file, et n'en approuver aucun.",
    filed: '« {title} » rangé — c\'est dans votre file et cela vous attend.',
    learned: "Noté : {fact}",
    failed: "Cela n'est pas passé.",
    budget: "Le budget de conversation du mois est épuisé.",
    notConfigured: "Le cofondateur n'est pas encore activé.",
    noCompany: "Créez d'abord une entreprise et il aura de quoi savoir.",
  },
} as const;

/* What it has learned. The wording avoids "memory" as a noun where it can:
 * people trust "what it knows about you" and are unsettled by a machine that
 * says it remembers them. */
export const OS_MEMORY_COPY = {
  en: {
    title: "What it knows",
    empty: "It has not written anything down yet. Tell it something, or let it learn as you work.",
    noCompany: "Start a company first and there will be something to know.",
    teach: "Tell it",
    teachLabel: "Something it should know",
    teachPlaceholder: "We never quote below 40 euros a pallet.",
    kindLabel: "What sort of thing",
    kinds: {
      fact: "Fact",
      preference: "Preference",
      constraint: "Constraint",
      person: "Person",
      decision: "Decision",
    },
    fromYou: "you told it",
    fromIt: "it learned this",
    retire: "Wrong",
    reasonLabel: "Why it is wrong",
    reasonPlaceholder: "Why (optional)",
    retiredHeading: "Things it used to think",
    because: "Retired because:",
    noted: "Noted.",
    retired: "Retired.",
  },
  tr: {
    title: "Bildikleri",
    empty: "Henüz bir şey not etmedi. Ona bir şey söyleyin ya da çalışırken öğrensin.",
    noCompany: "Önce bir şirket kurun, bilecek bir şey olsun.",
    teach: "Söyle",
    teachLabel: "Bilmesi gereken bir şey",
    teachPlaceholder: "Palet başına 40 avronun altına asla fiyat vermeyiz.",
    kindLabel: "Ne türden",
    kinds: {
      fact: "Bilgi",
      preference: "Tercih",
      constraint: "Kısıt",
      person: "Kişi",
      decision: "Karar",
    },
    fromYou: "siz söylediniz",
    fromIt: "kendi öğrendi",
    retire: "Yanlış",
    reasonLabel: "Neden yanlış",
    reasonPlaceholder: "Neden (isteğe bağlı)",
    retiredHeading: "Eskiden düşündükleri",
    because: "Kaldırılma nedeni:",
    noted: "Not edildi.",
    retired: "Kaldırıldı.",
  },
  fr: {
    title: "Ce qu'il sait",
    empty: "Il n'a encore rien noté. Dites-lui quelque chose, ou laissez-le apprendre en travaillant.",
    noCompany: "Créez d'abord une entreprise et il y aura de quoi savoir.",
    teach: "Dites-lui",
    teachLabel: "Quelque chose qu'il devrait savoir",
    teachPlaceholder: "Nous ne descendons jamais sous 40 euros la palette.",
    kindLabel: "De quel ordre",
    kinds: {
      fact: "Fait",
      preference: "Préférence",
      constraint: "Contrainte",
      person: "Personne",
      decision: "Décision",
    },
    fromYou: "vous le lui avez dit",
    fromIt: "il l'a appris",
    retire: "Faux",
    reasonLabel: "Pourquoi c'est faux",
    reasonPlaceholder: "Pourquoi (facultatif)",
    retiredHeading: "Ce qu'il pensait avant",
    because: "Retiré parce que :",
    noted: "Noté.",
    retired: "Retiré.",
  },
} as const;

/* The record, made visible. The wording is about who did what rather than
 * about events: "the system drafted this, you approved it" is the sentence
 * the whole product exists to be able to say. */
export const OS_RECORD_COPY = {
  en: {
    title: "Record",
    empty: "Nothing has happened yet. Everything either of you does will be listed here, permanently.",
    noCompany: "Start a company first and its record begins.",
    byYou: "a person",
    bySystem: "the system",
    newSince: "New since you last looked",
    events: {
      added: "added",
      edited: "edited",
      prepared: "prepared",
      approved: "approved",
      sent_back: "sent back",
      reopened: "reopened",
      resubmitted: "resubmitted",
      blocked: "blocked",
      completed: "completed",
      dismissed: "dismissed",
    } as Record<string, string>,
    markSeen: "Mark as seen",
    unread: (count: number) => (count === 1 ? "1 new" : `${count} new`),
  },
  tr: {
    title: "Kayıt",
    empty: "Henüz bir şey olmadı. İkinizin yaptığı her şey burada kalıcı olarak listelenecek.",
    noCompany: "Önce bir şirket kurun, kaydı başlasın.",
    byYou: "bir kişi",
    bySystem: "sistem",
    newSince: "Son baktığınızdan beri yeni",
    events: {
      added: "ekledi",
      edited: "düzenledi",
      prepared: "hazırladı",
      approved: "onayladı",
      sent_back: "geri gönderdi",
      reopened: "yeniden açtı",
      resubmitted: "yeniden sundu",
      blocked: "durdurdu",
      completed: "tamamladı",
      dismissed: "kaldırdı",
    } as Record<string, string>,
    markSeen: "Görüldü olarak işaretle",
    unread: (count: number) => `${count} yeni`,
  },
  fr: {
    title: "Registre",
    empty: "Rien ne s'est encore passé. Tout ce que vous ferez l'un ou l'autre sera listé ici, définitivement.",
    noCompany: "Créez d'abord une entreprise et son registre commence.",
    byYou: "une personne",
    bySystem: "le système",
    newSince: "Nouveau depuis votre dernier passage",
    events: {
      added: "a ajouté",
      edited: "a modifié",
      prepared: "a préparé",
      approved: "a approuvé",
      sent_back: "a renvoyé",
      reopened: "a rouvert",
      resubmitted: "a resoumis",
      blocked: "a bloqué",
      completed: "a terminé",
      dismissed: "a écarté",
    } as Record<string, string>,
    markSeen: "Marquer comme vu",
    unread: (count: number) => (count === 1 ? "1 nouveau" : `${count} nouveaux`),
  },
} as const;

/* A work item opened as a document. The words say what each part *is* —
 * the draft, what it drew on, what happened to it — because the reader is
 * about to put their name on it and should not have to guess which part is
 * the machine's claim and which is the evidence. */
export const OS_DOCUMENT_COPY = {
  en: {
    open: "Open",
    draft: "The draft",
    yourNote: "Your note",
    nothingWritten: "Nothing has been written for this yet.",
    claims: "What it says, and where from",
    unsupported: "not supported by any source",
    sources: "What it read",
    history: "What happened",
    nothingHappened: "Nothing yet.",
    waitingOn: "Waiting on",
    byPerson: "a person",
    bySystem: "the system",
    markDone: "Mark done",
    doneDraft: "Done",
    whereLabel: "Where did it go? (optional link)",
    doneNote: "Note (optional)",
    dismiss: "Dismiss",
    dismissReason: "Why (optional)",
    reopen: "Back to draft",
    resubmit: "Ready for review again",
    manualHint: "MaydaOS cannot do this one for you yet. Do it, then record that it is done and where it went.",
    whereItWent: "Where it went",
    finished: "Finished",
    draftedBy: { cofounder: "Drafted by the co-founder", worker: "Prepared while you were away", person: "Added by a person" } as Record<string, string>,
    edit: "Edit",
    editTitle: "Title",
    editLane: "Part of the business",
    editNote: "Note",
    editDue: "Due",
    save: "Save",
    cancel: "Cancel",
    frozen: "Approved work is frozen: what was approved is what stays.",
    editFailed: "That change did not go through.",
    due: "Due {date}",
    overdue: "{date} — overdue",
    notices: {
      approve: "Approved.",
      send_back: "Sent back.",
      done: "Marked done.",
      resubmit: "Ready for review.",
      reopen: "Back to draft.",
      dismiss: "Dismissed.",
      saved: "Saved.",
      added: "Added to work.",
    },
  },
  tr: {
    open: "Aç",
    draft: "Taslak",
    yourNote: "Notunuz",
    nothingWritten: "Bunun için henüz bir şey yazılmadı.",
    claims: "Ne diyor, nereden",
    unsupported: "hiçbir kaynakla desteklenmiyor",
    sources: "Ne okudu",
    history: "Ne oldu",
    nothingHappened: "Henüz bir şey yok.",
    waitingOn: "Bekleyen",
    byPerson: "bir kişi",
    bySystem: "sistem",
    markDone: "Tamamlandı olarak işaretle",
    doneDraft: "Tamam",
    whereLabel: "Nereye gitti? (isteğe bağlı bağlantı)",
    doneNote: "Not (isteğe bağlı)",
    dismiss: "Kapat",
    dismissReason: "Neden (isteğe bağlı)",
    reopen: "Taslağa geri al",
    resubmit: "Yeniden incelemeye hazır",
    manualHint: "MaydaOS bunu henüz sizin yerinize yapamıyor. Siz yapın, sonra bittiğini ve nereye gittiğini kaydedin.",
    whereItWent: "Nereye gitti",
    finished: "Tamamlandı",
    draftedBy: { cofounder: "Kurucu ortak hazırladı", worker: "Siz yokken hazırlandı", person: "Bir kişi ekledi" } as Record<string, string>,
    edit: "Düzenle",
    editTitle: "Başlık",
    editLane: "İşin hangi kısmı",
    editNote: "Not",
    editDue: "Son tarih",
    save: "Kaydet",
    cancel: "Vazgeç",
    frozen: "Onaylanmış iş dondurulur: onaylanan neyse o kalır.",
    editFailed: "Bu değişiklik geçmedi.",
    due: "Son tarih {date}",
    overdue: "{date} — gecikti",
    notices: {
      approve: "Onaylandı.",
      send_back: "Geri gönderildi.",
      done: "Bitti olarak işaretlendi.",
      resubmit: "Yeniden incelemeye hazır.",
      reopen: "Taslağa döndü.",
      dismiss: "Kaldırıldı.",
      saved: "Kaydedildi.",
      added: "İşe eklendi.",
    },
  },
  fr: {
    open: "Ouvrir",
    draft: "Le brouillon",
    yourNote: "Votre note",
    nothingWritten: "Rien n'a encore été écrit pour ceci.",
    claims: "Ce qu'il affirme, et d'où",
    unsupported: "soutenu par aucune source",
    sources: "Ce qu'il a lu",
    history: "Ce qui s'est passé",
    nothingHappened: "Rien encore.",
    waitingOn: "En attente de",
    byPerson: "une personne",
    bySystem: "le système",
    markDone: "Marquer comme fait",
    doneDraft: "Terminé",
    whereLabel: "Où est-ce parti ? (lien facultatif)",
    doneNote: "Note (facultative)",
    dismiss: "Écarter",
    dismissReason: "Pourquoi (facultatif)",
    reopen: "Retour au brouillon",
    resubmit: "Prêt à être revu",
    manualHint: "MaydaOS ne peut pas encore le faire à votre place. Faites-le, puis notez que c'est fait et où c'est parti.",
    whereItWent: "Où c'est parti",
    finished: "Terminé",
    draftedBy: { cofounder: "Rédigé par le cofondateur", worker: "Préparé pendant votre absence", person: "Ajouté par une personne" } as Record<string, string>,
    edit: "Modifier",
    editTitle: "Titre",
    editLane: "Partie de l'entreprise",
    editNote: "Note",
    editDue: "Échéance",
    save: "Enregistrer",
    cancel: "Annuler",
    frozen: "Le travail approuvé est figé : ce qui a été approuvé reste tel quel.",
    editFailed: "Cette modification n'est pas passée.",
    due: "Échéance {date}",
    overdue: "{date} — en retard",
    notices: {
      approve: "Approuvé.",
      send_back: "Renvoyé.",
      done: "Marqué comme terminé.",
      resubmit: "Prêt pour une nouvelle revue.",
      reopen: "De retour en brouillon.",
      dismiss: "Écarté.",
      saved: "Enregistré.",
      added: "Ajouté au travail.",
    },
  },
} as const;

/* The Work app. Status words are the founder's, not the state machine's:
 * "review" is Abidin's vocabulary, "Decide" is what it asks of a person. */
export const OS_WORKAPP_COPY = {
  en: {
    title: "Work",
    empty: "Nothing open. What you or the co-founder start lives here until it is finished.",
    add: "Add",
    addLabel: "Something to do",
    addPlaceholder: "Call the carrier about the revised contract",
    laneLabel: "Which part of the business",
    needYou: (count: number) => (count === 1 ? "1 needs you" : `${count} need you`),
    finished: "Finished this fortnight",
    dueLabel: "Due (optional)",
    due: "due {date}",
    dueToday: "due today",
    overdue: "overdue",
    lanes: { sales: "Sales", content: "Content", product: "Product", ops: "Ops", finance: "Finance" } as Record<string, string>,
    status: {
      review: "Decide",
      approved: "To do",
      blocked: "Stuck",
      drafted: "Draft",
      triaged: "Sorted",
      pending: "New",
      completed: "Done",
    } as Record<string, string>,
  },
  tr: {
    title: "İşler",
    empty: "Açık iş yok. Sizin ya da kurucu ortağın başlattığı her şey bitene kadar burada durur.",
    add: "Ekle",
    addLabel: "Yapılacak bir şey",
    addPlaceholder: "Revize sözleşme için nakliyeciyi ara",
    laneLabel: "İşin hangi tarafı",
    needYou: (count: number) => `${count} sizi bekliyor`,
    finished: "Bu iki haftada bitenler",
    dueLabel: "Son tarih (isteğe bağlı)",
    due: "son tarih {date}",
    dueToday: "bugün",
    overdue: "gecikti",
    lanes: { sales: "Satış", content: "İçerik", product: "Ürün", ops: "Operasyon", finance: "Finans" } as Record<string, string>,
    status: {
      review: "Karar",
      approved: "Yapılacak",
      blocked: "Takıldı",
      drafted: "Taslak",
      triaged: "Ayrıldı",
      pending: "Yeni",
      completed: "Bitti",
    } as Record<string, string>,
  },
  fr: {
    title: "Travail",
    empty: "Rien d'ouvert. Ce que vous ou le cofondateur commencez reste ici jusqu'à ce que ce soit terminé.",
    add: "Ajouter",
    addLabel: "Quelque chose à faire",
    addPlaceholder: "Appeler le transporteur au sujet du contrat révisé",
    laneLabel: "Quelle partie de l'entreprise",
    needYou: (count: number) => (count === 1 ? "1 vous attend" : `${count} vous attendent`),
    finished: "Terminé cette quinzaine",
    dueLabel: "Échéance (facultatif)",
    due: "pour le {date}",
    dueToday: "pour aujourd'hui",
    overdue: "en retard",
    lanes: { sales: "Ventes", content: "Contenu", product: "Produit", ops: "Opérations", finance: "Finance" } as Record<string, string>,
    status: {
      review: "Décider",
      approved: "À faire",
      blocked: "Bloqué",
      drafted: "Brouillon",
      triaged: "Trié",
      pending: "Nouveau",
      completed: "Fait",
    } as Record<string, string>,
  },
} as const;
