import type { Locale } from "@/lib/i18n";

/* MaydaOS beta, client-facing.
 *
 * Every value here is a plain string, including the ones with numbers in
 * them: this object crosses into a client component, and a function cannot
 * make that trip. */

export function fillCredits(template: string, left: number, granted: number): string {
  return template.replace("{left}", String(left)).replace("{granted}", String(granted));
}

export const OS_DESK_COPY = {
  en: {
    kicker: "MaydaOS / Beta",
    heading: "Give it sources. It produces the work. You decide what leaves.",
    creditsLeft: "{left} of {granted} credits left",
    creditsNote: "A credit is one run. Reading sources, editing, approving and rejecting cost nothing.",
    topicLabel: "What is this about?",
    topicPlaceholder: "e.g. What changed in EU stablecoin rules this month",
    shapeLabel: "Shape",
    shapes: { note: "Short note", post: "LinkedIn post", summary: "Summary of the sources" },
    sourcesLabel: "Sources (one link per line, up to 5)",
    run: "Run",
    running: "Reading the sources...",
    runsHeading: "Your runs",
    empty: "Nothing yet. Add a link and press run.",
    draftLabel: "Draft",
    claimsLabel: "Every claim, next to its source",
    unsourced: "No source. Check this before approving.",
    copy: "Copy the draft",
    copied: "Copied",
    outcomeLabel: "Where did it go?",
    outcomeNote: "Paste the public link once you have posted or sent it. MaydaOS never posts anything itself.",
    outcomeSave: "Save the link",
    approve: "Approve",
    reject: "Send back",
    noteLabel: "Note (optional)",
    decisions: { pending: "Waiting for you", approved: "Approved by you", rejected: "Sent back" },
    outOfHeading: "You have used your beta credits.",
    outOfBody: "Your workspace stays. Everything you produced and approved is below, and it is yours.",
    outOfCta: "Talk about running this properly",
    recordHeading: "What you did here",
    recordRuns: "runs",
    recordApproved: "approved",
    recordSources: "sources cited",
    failed: "This run failed and cost you nothing.",
  },
  tr: {
    kicker: "MaydaOS / Beta",
    heading: "Kaynakları siz verin. İşi o üretsin. Neyin çıkacağına siz karar verin.",
    creditsLeft: "{granted} kredinin {left} tanesi kaldı",
    creditsNote: "Bir kredi bir çalıştırmadır. Kaynakları okumak, düzenlemek, onaylamak ve geri göndermek ücretsizdir.",
    topicLabel: "Konu nedir?",
    topicPlaceholder: "örn. Bu ay AB stablecoin kurallarında ne değişti",
    shapeLabel: "Biçim",
    shapes: { note: "Kısa not", post: "LinkedIn gönderisi", summary: "Kaynakların özeti" },
    sourcesLabel: "Kaynaklar (her satıra bir bağlantı, en fazla 5)",
    run: "Çalıştır",
    running: "Kaynaklar okunuyor...",
    runsHeading: "Çalıştırmalarınız",
    empty: "Henüz bir şey yok. Bir bağlantı ekleyip çalıştırın.",
    draftLabel: "Taslak",
    claimsLabel: "Her iddia, kaynağının yanında",
    unsourced: "Kaynak yok. Onaylamadan önce kontrol edin.",
    copy: "Taslağı kopyala",
    copied: "Kopyalandı",
    outcomeLabel: "Nereye gitti?",
    outcomeNote: "Yayınladıktan veya gönderdikten sonra herkese açık bağlantıyı yapıştırın. MaydaOS hiçbir şeyi kendisi yayınlamaz.",
    outcomeSave: "Bağlantıyı kaydet",
    approve: "Onayla",
    reject: "Geri gönder",
    noteLabel: "Not (isteğe bağlı)",
    decisions: { pending: "Sizi bekliyor", approved: "Onayladınız", rejected: "Geri gönderildi" },
    outOfHeading: "Beta kredilerinizi kullandınız.",
    outOfBody: "Çalışma alanınız duruyor. Ürettiğiniz ve onayladığınız her şey aşağıda ve size ait.",
    outOfCta: "Bunu düzgün biçimde kurmayı konuşalım",
    recordHeading: "Burada yaptıklarınız",
    recordRuns: "çalıştırma",
    recordApproved: "onaylandı",
    recordSources: "kaynak gösterildi",
    failed: "Bu çalıştırma başarısız oldu ve size bir şeye mal olmadı.",
  },
  fr: {
    kicker: "MaydaOS / Beta",
    heading: "Donnez-lui les sources. Il produit le travail. Vous decidez de ce qui sort.",
    creditsLeft: "{left} credits restants sur {granted}",
    creditsNote: "Un credit vaut une execution. Lire les sources, editer, approuver et renvoyer ne coutent rien.",
    topicLabel: "De quoi s'agit-il ?",
    topicPlaceholder: "ex. Ce qui a change dans les regles europeennes ce mois-ci",
    shapeLabel: "Format",
    shapes: { note: "Note courte", post: "Post LinkedIn", summary: "Resume des sources" },
    sourcesLabel: "Sources (un lien par ligne, 5 maximum)",
    run: "Executer",
    running: "Lecture des sources...",
    runsHeading: "Vos executions",
    empty: "Rien pour l'instant. Ajoutez un lien et lancez.",
    draftLabel: "Brouillon",
    claimsLabel: "Chaque affirmation, a cote de sa source",
    unsourced: "Aucune source. Verifiez avant d'approuver.",
    copy: "Copier le brouillon",
    copied: "Copie",
    outcomeLabel: "Ou est-ce parti ?",
    outcomeNote: "Collez le lien public une fois publie ou envoye. MaydaOS ne publie jamais rien lui-meme.",
    outcomeSave: "Enregistrer le lien",
    approve: "Approuver",
    reject: "Renvoyer",
    noteLabel: "Note (facultatif)",
    decisions: { pending: "En attente de vous", approved: "Approuve par vous", rejected: "Renvoye" },
    outOfHeading: "Vous avez utilise vos credits beta.",
    outOfBody: "Votre espace reste. Tout ce que vous avez produit et approuve est ci-dessous, et vous appartient.",
    outOfCta: "Parlons d'une installation complete",
    recordHeading: "Ce que vous avez fait ici",
    recordRuns: "executions",
    recordApproved: "approuvees",
    recordSources: "sources citees",
    failed: "Cette execution a echoue et ne vous a rien coute.",
  },
} as const satisfies Record<Locale, unknown>;

export type OsDeskCopy = (typeof OS_DESK_COPY)[Locale];
