import type { Locale } from "@/lib/i18n";

export const SERVICE_IDS = ["websites", "software", "automation", "email", "support"] as const;
export type ServiceId = (typeof SERVICE_IDS)[number];
type Service = { id: ServiceId; title: string; need: string; summary: string; deliverables: string[]; example: string };

// Public services are independent of existing customers' pilot and billing records.
export const SERVICES: Record<Locale, Service[]> = {
  en: [
    { id: "websites", title: "Websites & online stores", need: "Make it easier to enquire, book or buy.", summary: "New websites, redesigns and online stores that explain your business and help customers take the next step.", deliverables: ["Site structure, design and responsive development", "Enquiry, booking or checkout journeys", "Content setup, analytics and handover"], example: "A clearer company website with enquiries sent to the right person." },
    { id: "software", title: "Custom software", need: "Build the tool your business needs.", summary: "Web apps, customer portals, dashboards and internal tools — with the frontend, backend and integrations working together.", deliverables: ["A prototype or scoped first release", "Frontend, backend, database and access control", "Integrations, testing and documentation"], example: "A customer portal that replaces status-update emails and scattered files." },
    { id: "automation", title: "AI & automation", need: "Stop doing the same work by hand.", summary: "Connect your tools and automate repetitive tasks. Use AI where it helps, with checks and human approval where needed.", deliverables: ["A map of the current workflow and its failure points", "Tool integrations and task automation", "Review steps, error handling and operating instructions"], example: "Turn incoming requests into organized records and reviewable drafts." },
    { id: "email", title: "Email & customer journeys", need: "Give each customer a useful next step.", summary: "Connect enquiries, your CRM and email so leads get a follow-up and customers get useful onboarding and ongoing communication.", deliverables: ["Lead routing and CRM connections", "Consent-aware onboarding and follow-up emails", "Templates, segmentation and measurement"], example: "A new enquiry reaches your CRM with a clear owner and a follow-up task." },
    { id: "support", title: "Fixes & ongoing support", need: "Get unfinished or unreliable software moving again.", summary: "Resolve bugs, improve performance, repair integrations and take care of the systems your business already relies on.", deliverables: ["An initial review and prioritized repair plan", "Agreed fixes with regression checks", "Optional maintenance with clear responsibilities"], example: "Finish an incomplete app, repair its broken flow and document how to run it." },
  ],
  tr: [
    { id: "websites", title: "Web siteleri ve e-ticaret", need: "İletişimi, rezervasyonu ve alışverişi kolaylaştırın.", summary: "İşinizi açıkça anlatan ve müşteriye sonraki adımı gösteren yeni siteler, site yenilemeleri ve online mağazalar.", deliverables: ["Site yapısı, tasarım ve tüm ekranlara uyumlu geliştirme", "İletişim, rezervasyon veya satın alma akışları", "İçerik kurulumu, ölçümleme ve teslim"], example: "Gelen talepleri doğru kişiye ileten, anlaşılır bir şirket sitesi." },
    { id: "software", title: "Özel yazılım", need: "İşinizin ihtiyaç duyduğu aracı geliştirin.", summary: "Web uygulamaları, müşteri portalları, paneller ve şirket içi araçlar. Arayüz, sunucu tarafı ve entegrasyonlar birlikte çalışır.", deliverables: ["Prototip veya kapsamı belirlenmiş ilk sürüm", "Arayüz, sunucu tarafı, veritabanı ve erişim kontrolü", "Entegrasyonlar, testler ve dokümantasyon"], example: "Durum güncelleme e-postaları ve dağınık dosyaların yerini alan bir müşteri portalı." },
    { id: "automation", title: "Yapay zekâ ve otomasyon", need: "Aynı işleri elle tekrarlamayın.", summary: "Araçlarınızı bağlayın, tekrar eden işleri otomatikleştirin. Yapay zekâyı faydalı olduğu yerde, gerekli kontroller ve insan onayıyla kullanın.", deliverables: ["Mevcut iş akışı ve aksayan noktaların haritası", "Araç entegrasyonları ve görev otomasyonu", "İnceleme adımları, hata yönetimi ve kullanım rehberi"], example: "Gelen talepleri düzenli kayıtlara ve incelemeye hazır taslaklara dönüştürün." },
    { id: "email", title: "E-posta ve müşteri yolculukları", need: "Müşteriye doğru sonraki adımı gösterin.", summary: "Talepleri, CRM'inizi ve e-postayı birbirine bağlayın. Potansiyel müşterileri takip edin, yeni müşterilere rehberlik edin ve iletişimi sürdürün.", deliverables: ["Talep yönlendirme ve CRM bağlantıları", "İzinlere uygun karşılama ve takip e-postaları", "Şablonlar, segmentasyon ve ölçümleme"], example: "Yeni bir talebin sorumlusu ve takip göreviyle birlikte CRM'e aktarılması." },
    { id: "support", title: "Düzeltmeler ve sürekli destek", need: "Yarım kalan veya aksayan yazılımı işler hâle getirin.", summary: "Hataları giderin, performansı iyileştirin, entegrasyonları onarın ve işinizin kullandığı sistemleri bakımlı tutun.", deliverables: ["İlk inceleme ve önceliklendirilmiş onarım planı", "Kararlaştırılan düzeltmeler ve regresyon testleri", "Sorumlulukları net, isteğe bağlı bakım"], example: "Yarım kalmış bir uygulamayı tamamlayıp aksayan akışını düzeltmek ve kullanımını belgelemek." },
  ],
  fr: [
    { id: "websites", title: "Sites web & boutiques en ligne", need: "Facilitez la prise de contact, la réservation et l’achat.", summary: "Création de sites, refontes et boutiques en ligne qui expliquent votre activité et aident vos clients à passer à l’étape suivante.", deliverables: ["Structure, design et développement responsive", "Parcours de contact, de réservation ou d’achat", "Mise en place du contenu, mesure et transmission"], example: "Un site d’entreprise clair qui transmet les demandes à la bonne personne." },
    { id: "software", title: "Logiciels sur mesure", need: "Construisez l’outil dont votre entreprise a besoin.", summary: "Applications web, portails clients, tableaux de bord et outils internes : interface, serveur et intégrations conçus ensemble.", deliverables: ["Prototype ou première version au périmètre défini", "Interface, backend, base de données et contrôle d’accès", "Intégrations, tests et documentation"], example: "Un portail client qui remplace les échanges de suivi et les fichiers dispersés." },
    { id: "automation", title: "IA & automatisation", need: "Ne refaites plus les mêmes tâches à la main.", summary: "Connectez vos outils et automatisez les tâches répétitives. Utilisez l’IA là où elle est utile, avec des contrôles et une validation humaine si nécessaire.", deliverables: ["Cartographie du processus et de ses points de défaillance", "Intégrations et automatisation des tâches", "Étapes de validation, gestion des erreurs et mode d’emploi"], example: "Transformer les demandes entrantes en dossiers organisés et en brouillons à relire." },
    { id: "email", title: "Email & parcours clients", need: "Donnez à chaque client une prochaine étape utile.", summary: "Reliez demandes, CRM et emails pour suivre vos prospects, accompagner vos nouveaux clients et entretenir la relation.", deliverables: ["Routage des demandes et connexions CRM", "Emails d’accueil et de suivi respectant le consentement", "Modèles, segmentation et mesure"], example: "Une demande arrive dans le CRM avec un responsable et une tâche de suivi." },
    { id: "support", title: "Corrections & maintenance", need: "Remettez vos logiciels inachevés ou fragiles sur les rails.", summary: "Corrigez les bugs, améliorez les performances, réparez les intégrations et entretenez les systèmes que votre entreprise utilise déjà.", deliverables: ["Examen initial et plan de correction priorisé", "Corrections convenues et tests de non-régression", "Maintenance optionnelle avec responsabilités définies"], example: "Terminer une application inachevée, réparer son parcours et documenter son fonctionnement." },
  ],
};

export const SERVICES_COPY = {
  en: { kicker: "Services", heading: "What does your business need next?", intro: "Start with the problem, not a package. We can build something new, improve what you have, or connect the tools you already use.", detail: "Explore services", includes: "A project can include", example: "For example", cta: "Tell us what you need", work: "See our work", scope: "We agree the scope, price and responsibilities before work begins. You can start with one project; ongoing support is optional.", unsure: "Not sure where to start?", unsureText: "Tell us what is taking too much time, what is not working, or what you want to build. No account or diagnostic required." },
  tr: { kicker: "Hizmetler", heading: "İşinizin sıradaki ihtiyacı ne?", intro: "Bir paketle değil, ihtiyaçla başlayın. Yeni bir şey geliştirebilir, elinizdekini iyileştirebilir veya kullandığınız araçları birbirine bağlayabiliriz.", detail: "Hizmetleri inceleyin", includes: "Proje kapsamında neler olabilir?", example: "Örneğin", cta: "Neye ihtiyacınız olduğunu anlatın", work: "Projelerimizi görün", scope: "Çalışmaya başlamadan önce kapsamı, ücreti ve sorumlulukları birlikte netleştiririz. Tek bir projeyle başlayabilirsiniz; sürekli destek isteğe bağlıdır.", unsure: "Nereden başlayacağınızdan emin değil misiniz?", unsureText: "Neyin çok zaman aldığını, neyin çalışmadığını veya ne geliştirmek istediğinizi anlatın. Hesap açmanız ya da değerlendirme doldurmanız gerekmez." },
  fr: { kicker: "Services", heading: "De quoi votre entreprise a-t-elle besoin maintenant ?", intro: "Partez du problème, pas d’un forfait. Nous pouvons créer, améliorer l’existant ou connecter les outils que vous utilisez déjà.", detail: "Explorer les services", includes: "Un projet peut comprendre", example: "Par exemple", cta: "Parlez-nous de votre besoin", work: "Voir nos réalisations", scope: "Nous convenons du périmètre, du prix et des responsabilités avant de commencer. Un seul projet suffit pour démarrer ; la maintenance reste optionnelle.", unsure: "Vous ne savez pas par où commencer ?", unsureText: "Dites-nous ce qui prend trop de temps, ce qui ne fonctionne pas ou ce que vous voulez construire. Aucun compte ni diagnostic requis." },
} as const;
