import type { Locale } from "@/lib/i18n";

export const OS_COPY = {
  en: {
    menu: [
      ["Work", "/case-studies"],
      ["Services", "/services"],
      ["About", "/about"],
    ],
    boot: [
      "MAYDAOS 26.08 — signal kernel",
      "mounting /work .......... 4 transmissions",
      "telemetry link .......... up",
      "locales ................. en · tr · fr",
      "sound ................... off (SND to enable)",
      "boot complete — welcome",
    ],
    welcome: {
      title: "welcome — read me",
      kicker: "MaydaLabs — product & growth studio",
      hero: ["We build software", "people can", "feel."],
      body: [
        "MaydaLabs is an independent product and growth studio based in Istanbul, working with founders and teams worldwide. We design, build, and operate production web software: applications, marketplaces, commerce platforms, and the measurement and lifecycle systems that make them grow.",
        "Two of our products are publicly verifiable today — HodlStay, a Bitcoin-native stay marketplace delivered as a client build, and Satoshi Gazette, our own intelligence publication. Two further builds are in active private development. The system monitor on this desktop reports their live status.",
        "Engagements are scoped individually after a first conversation. We work in short cycles against working software, instrument what we ship, and hand over documented systems.",
      ],
      note: "This site runs as a small operating system. Everything on it is functional — the shell, the telemetry, the tour.",
      capabilities: [
        ["Product engineering", "/services"],
        ["Commerce & marketplaces", "/services"],
        ["Growth & measurement systems", "/services"],
      ],
      start: "Start a project",
      explore: "Open the work",
    },
    workWindow: {
      title: "work — transmissions",
      open: "Open case",
      rows: [
        { tx: "TX-01", name: "HodlStay", status: "Client build · Broadcasting", path: "/case-studies/hodlstay" },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Studio product · Broadcasting", path: "/case-studies/satoshi-gazette" },
        { tx: "TX-03", name: "Mortal Vault", status: "Private alpha · Encrypted", path: "/case-studies/mortal-vault" },
        { tx: "TX-04", name: "Sofra", status: "Phase 1 · Encrypted", path: "/case-studies/sofra" },
      ],
    },
    hodlstayWindow: { title: "hodlstay.com — TX-01", caption: "Bitcoin-native stay marketplace · client build", cta: "Inspect the case" },
    gazetteWindow: { title: "satoshigazette.org — TX-02", caption: "Bitcoin-only newsroom · studio product", cta: "Inspect the case" },
    monitorWindow: { title: "system monitor", scanning: "scanning…", noCarrier: "no carrier", block: "btc block height" },
    arrayWindow: { title: "signal array — product map" },
    toasts: { block: "new block mined" },
    tour: {
      offer: "New here? Watch the 20-second tour",
      dock: "Tour",
      done: "your turn — this desktop is yours",
      skipped: "tour skipped — reduced motion is on",
    },
    terminalWindow: { title: "maydalabs — shell", hint: "type `help` to see what this thing can do" },
    dock: { welcome: "Read me", work: "Work", terminal: "Shell", monitor: "Monitor", services: "Services", about: "About", call: "Book a call", trash: "Trash" },
    aboutWindow: {
      title: "about this mayda",
      rows: [
        ["Version", "MaydaOS 26.08"],
        ["Kernel", "signal / 26.08"],
        ["Shell", "mayda-sh 1.0"],
        ["Display", "Bitcoin orange"],
        ["Memory", "enough"],
        ["Locales", "EN · TR · FR"],
      ],
      uptime: "Uptime",
      footer: "Built in the open by MaydaLabs — Istanbul / Everywhere.",
    },
    trashWindow: {
      title: "trash",
      items: ["agency_theatre.zip — 4.2 GB", "endless_revisions_final_FINAL_v7.psd", "buzzword_strategy_deck.pptx", "scope_creep.log"],
      empty: "Empty trash",
      emptied: "already empty where it counts.",
    },
    palette: {
      placeholder: "Type to jump — pages, cases, actions…",
      hint: "⌘K anywhere · ↑↓ to move · ⏎ to run",
      empty: "no signal on that frequency",
      items: [
        { label: "Desktop", kind: "page", target: "/" },
        { label: "Work — all transmissions", kind: "page", target: "/case-studies" },
        { label: "HodlStay — TX-01", kind: "page", target: "/case-studies/hodlstay" },
        { label: "Satoshi Gazette — TX-02", kind: "page", target: "/case-studies/satoshi-gazette" },
        { label: "Mortal Vault — TX-03", kind: "page", target: "/case-studies/mortal-vault" },
        { label: "Sofra — TX-04", kind: "page", target: "/case-studies/sofra" },
        { label: "Services", kind: "page", target: "/services" },
        { label: "About the studio", kind: "page", target: "/about" },
        { label: "Contact — start something", kind: "page", target: "/contact" },
        { label: "Book a project call", kind: "call", target: "" },
        { label: "Toggle interface sound", kind: "sound", target: "" },
      ],
    },
    screensaver: { line: "signal never sleeps", wake: "move to wake" },
    mobile: {
      greeting: "MaydaOS",
      sub: "Software people can feel.",
      apps: [
        { label: "Work", path: "/case-studies", glyph: "grid" },
        { label: "Services", path: "/services", glyph: "layers" },
        { label: "About", path: "/about", glyph: "mark" },
        { label: "Contact", path: "/contact", glyph: "send" },
      ],
      call: "Book a project call",
    },
  },
  tr: {
    menu: [
      ["Projeler", "/case-studies"],
      ["Hizmetler", "/services"],
      ["Hakkımızda", "/about"],
    ],
    boot: [
      "MAYDAOS 26.08 — sinyal çekirdeği",
      "/work bağlanıyor ........ 4 yayın",
      "telemetri bağlantısı .... açık",
      "diller .................. en · tr · fr",
      "ses ..................... kapalı (SND ile açın)",
      "açılış tamam — hoş geldiniz",
    ],
    welcome: {
      title: "hoş geldiniz — beni oku",
      kicker: "MaydaLabs — ürün ve büyüme stüdyosu",
      hero: ["İnsanların hissedebileceği", "yazılımlar", "geliştiriyoruz."],
      body: [
        "MaydaLabs, İstanbul merkezli bağımsız bir ürün ve büyüme stüdyosudur; dünyanın her yerinden kurucular ve ekiplerle çalışır. Üretimde çalışan web yazılımları tasarlar, geliştirir ve işletiriz: uygulamalar, pazar yerleri, e-ticaret platformları ve bunları büyüten ölçüm ile yaşam döngüsü sistemleri.",
        "Bugün iki ürünümüz herkese açık şekilde doğrulanabilir: müşteri projesi olarak teslim edilen Bitcoin-native konaklama pazar yeri HodlStay ve kendi yayınımız Satoshi Gazette. İki ek ürün özel geliştirme aşamasındadır. Bu masaüstündeki sistem monitörü canlı durumlarını raporlar.",
        "Her çalışmanın kapsamı ilk görüşmeden sonra ayrıca belirlenir. Kısa döngülerle, çalışan yazılım üzerinden ilerler; yayınladığımızı ölçer ve dokümante edilmiş sistemler teslim ederiz.",
      ],
      note: "Bu site küçük bir işletim sistemi olarak çalışır. Üzerindeki her şey gerçekten işlevseldir — kabuk, telemetri, tur.",
      capabilities: [
        ["Ürün mühendisliği", "/services"],
        ["E-ticaret ve pazar yerleri", "/services"],
        ["Büyüme ve ölçüm sistemleri", "/services"],
      ],
      start: "Proje başlat",
      explore: "Projeleri aç",
    },
    workWindow: {
      title: "projeler — yayınlar",
      open: "Vakayı aç",
      rows: [
        { tx: "TX-01", name: "HodlStay", status: "Müşteri projesi · Yayında", path: "/case-studies/hodlstay" },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Stüdyo ürünü · Yayında", path: "/case-studies/satoshi-gazette" },
        { tx: "TX-03", name: "Mortal Vault", status: "Özel alpha · Şifreli", path: "/case-studies/mortal-vault" },
        { tx: "TX-04", name: "Sofra", status: "Faz 1 · Şifreli", path: "/case-studies/sofra" },
      ],
    },
    hodlstayWindow: { title: "hodlstay.com — TX-01", caption: "Bitcoin-native konaklama pazar yeri · müşteri projesi", cta: "Vakayı incele" },
    gazetteWindow: { title: "satoshigazette.org — TX-02", caption: "Yalnızca Bitcoin haber merkezi · stüdyo ürünü", cta: "Vakayı incele" },
    monitorWindow: { title: "sistem monitörü", scanning: "taranıyor…", noCarrier: "sinyal yok", block: "btc blok yüksekliği" },
    arrayWindow: { title: "sinyal dizisi — ürün haritası" },
    toasts: { block: "yeni blok kazıldı" },
    tour: {
      offer: "Yeni misiniz? 20 saniyelik turu izleyin",
      dock: "Tur",
      done: "sıra sizde — bu masaüstü sizin",
      skipped: "tur atlandı — azaltılmış hareket açık",
    },
    terminalWindow: { title: "maydalabs — kabuk", hint: "`help` yazarak neler yapabildiğini görün" },
    dock: { welcome: "Beni oku", work: "Projeler", terminal: "Kabuk", monitor: "Monitör", services: "Hizmetler", about: "Hakkımızda", call: "Görüşme ayarla", trash: "Çöp" },
    aboutWindow: {
      title: "bu mayda hakkında",
      rows: [
        ["Sürüm", "MaydaOS 26.08"],
        ["Çekirdek", "sinyal / 26.08"],
        ["Kabuk", "mayda-sh 1.0"],
        ["Ekran", "Bitcoin turuncusu"],
        ["Bellek", "yeterli"],
        ["Diller", "EN · TR · FR"],
      ],
      uptime: "Çalışma süresi",
      footer: "MaydaLabs tarafından açıkta geliştirildi — İstanbul / Her yer.",
    },
    trashWindow: {
      title: "çöp",
      items: ["ajans_tiyatrosu.zip — 4.2 GB", "sonsuz_revizyon_final_SON_v7.psd", "moda_kelime_sunumu.pptx", "kapsam_kaymasi.log"],
      empty: "Çöpü boşalt",
      emptied: "önemli olan yerde zaten boş.",
    },
    palette: {
      placeholder: "Yazın ve atlayın — sayfalar, vakalar, eylemler…",
      hint: "Her yerde ⌘K · ↑↓ gezin · ⏎ çalıştır",
      empty: "bu frekansta sinyal yok",
      items: [
        { label: "Masaüstü", kind: "page", target: "/" },
        { label: "Projeler — tüm yayınlar", kind: "page", target: "/case-studies" },
        { label: "HodlStay — TX-01", kind: "page", target: "/case-studies/hodlstay" },
        { label: "Satoshi Gazette — TX-02", kind: "page", target: "/case-studies/satoshi-gazette" },
        { label: "Mortal Vault — TX-03", kind: "page", target: "/case-studies/mortal-vault" },
        { label: "Sofra — TX-04", kind: "page", target: "/case-studies/sofra" },
        { label: "Hizmetler", kind: "page", target: "/services" },
        { label: "Stüdyo hakkında", kind: "page", target: "/about" },
        { label: "İletişim — bir şey başlat", kind: "page", target: "/contact" },
        { label: "Proje görüşmesi ayarla", kind: "call", target: "" },
        { label: "Arayüz sesini aç/kapat", kind: "sound", target: "" },
      ],
    },
    screensaver: { line: "sinyal hiç uyumaz", wake: "uyandırmak için hareket edin" },
    mobile: {
      greeting: "MaydaOS",
      sub: "Hissedebileceğiniz yazılımlar.",
      apps: [
        { label: "Projeler", path: "/case-studies", glyph: "grid" },
        { label: "Hizmetler", path: "/services", glyph: "layers" },
        { label: "Hakkımızda", path: "/about", glyph: "mark" },
        { label: "İletişim", path: "/contact", glyph: "send" },
      ],
      call: "Proje görüşmesi ayarla",
    },
  },
  fr: {
    menu: [
      ["Projets", "/case-studies"],
      ["Services", "/services"],
      ["À propos", "/about"],
    ],
    boot: [
      "MAYDAOS 26.08 — noyau signal",
      "montage de /work ........ 4 transmissions",
      "lien télémétrie ......... actif",
      "langues ................. en · tr · fr",
      "son ..................... coupé (SND pour activer)",
      "démarrage terminé — bienvenue",
    ],
    welcome: {
      title: "bienvenue — lisez-moi",
      kicker: "MaydaLabs — studio produit et croissance",
      hero: ["Nous créons des logiciels", "que l’on peut", "ressentir."],
      body: [
        "MaydaLabs est un studio indépendant de produit et de croissance basé à Istanbul, travaillant avec des fondateurs et des équipes du monde entier. Nous concevons, construisons et opérons des logiciels web en production : applications, marketplaces, plateformes e-commerce, et les systèmes de mesure et de cycle de vie qui les font croître.",
        "Deux de nos produits sont vérifiables publiquement : HodlStay, marketplace de séjours Bitcoin-native livrée comme projet client, et Satoshi Gazette, notre propre publication. Deux autres produits sont en développement privé. Le moniteur système de ce bureau rapporte leur état en direct.",
        "Chaque mission est cadrée individuellement après un premier échange. Nous travaillons en cycles courts sur du logiciel fonctionnel, mesurons ce que nous livrons et transmettons des systèmes documentés.",
      ],
      note: "Ce site fonctionne comme un petit système d’exploitation. Tout y est réellement fonctionnel — le shell, la télémétrie, la visite.",
      capabilities: [
        ["Ingénierie produit", "/services"],
        ["E-commerce et marketplaces", "/services"],
        ["Systèmes de croissance et de mesure", "/services"],
      ],
      start: "Lancer un projet",
      explore: "Ouvrir les projets",
    },
    workWindow: {
      title: "projets — transmissions",
      open: "Ouvrir le cas",
      rows: [
        { tx: "TX-01", name: "HodlStay", status: "Projet client · En émission", path: "/case-studies/hodlstay" },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Produit studio · En émission", path: "/case-studies/satoshi-gazette" },
        { tx: "TX-03", name: "Mortal Vault", status: "Alpha privée · Chiffré", path: "/case-studies/mortal-vault" },
        { tx: "TX-04", name: "Sofra", status: "Phase 1 · Chiffré", path: "/case-studies/sofra" },
      ],
    },
    hodlstayWindow: { title: "hodlstay.com — TX-01", caption: "Marketplace de séjours Bitcoin-native · projet client", cta: "Voir le cas" },
    gazetteWindow: { title: "satoshigazette.org — TX-02", caption: "Rédaction 100 % Bitcoin · produit du studio", cta: "Voir le cas" },
    monitorWindow: { title: "moniteur système", scanning: "balayage…", noCarrier: "pas de signal", block: "hauteur de bloc btc" },
    arrayWindow: { title: "réseau de signaux — carte produit" },
    toasts: { block: "nouveau bloc miné" },
    tour: {
      offer: "Première visite ? Regardez le tour de 20 secondes",
      dock: "Visite",
      done: "à vous — ce bureau est le vôtre",
      skipped: "visite ignorée — mouvement réduit activé",
    },
    terminalWindow: { title: "maydalabs — shell", hint: "tapez `help` pour voir ce que ça sait faire" },
    dock: { welcome: "Lisez-moi", work: "Projets", terminal: "Shell", monitor: "Moniteur", services: "Services", about: "À propos", call: "Réserver un appel", trash: "Corbeille" },
    aboutWindow: {
      title: "à propos de ce mayda",
      rows: [
        ["Version", "MaydaOS 26.08"],
        ["Noyau", "signal / 26.08"],
        ["Shell", "mayda-sh 1.0"],
        ["Écran", "orange Bitcoin"],
        ["Mémoire", "suffisante"],
        ["Langues", "EN · TR · FR"],
      ],
      uptime: "Uptime",
      footer: "Construit au grand jour par MaydaLabs — Istanbul / Partout.",
    },
    trashWindow: {
      title: "corbeille",
      items: ["theatre_agence.zip — 4,2 Go", "revisions_sans_fin_final_FINAL_v7.psd", "deck_buzzwords.pptx", "derive_du_scope.log"],
      empty: "Vider la corbeille",
      emptied: "déjà vide là où ça compte.",
    },
    palette: {
      placeholder: "Tapez pour naviguer — pages, cas, actions…",
      hint: "⌘K partout · ↑↓ naviguer · ⏎ lancer",
      empty: "aucun signal sur cette fréquence",
      items: [
        { label: "Bureau", kind: "page", target: "/" },
        { label: "Projets — toutes les transmissions", kind: "page", target: "/case-studies" },
        { label: "HodlStay — TX-01", kind: "page", target: "/case-studies/hodlstay" },
        { label: "Satoshi Gazette — TX-02", kind: "page", target: "/case-studies/satoshi-gazette" },
        { label: "Mortal Vault — TX-03", kind: "page", target: "/case-studies/mortal-vault" },
        { label: "Sofra — TX-04", kind: "page", target: "/case-studies/sofra" },
        { label: "Services", kind: "page", target: "/services" },
        { label: "À propos du studio", kind: "page", target: "/about" },
        { label: "Contact — démarrer quelque chose", kind: "page", target: "/contact" },
        { label: "Réserver un appel projet", kind: "call", target: "" },
        { label: "Activer/couper le son", kind: "sound", target: "" },
      ],
    },
    screensaver: { line: "le signal ne dort jamais", wake: "bougez pour réveiller" },
    mobile: {
      greeting: "MaydaOS",
      sub: "Du logiciel que l’on ressent.",
      apps: [
        { label: "Projets", path: "/case-studies", glyph: "grid" },
        { label: "Services", path: "/services", glyph: "layers" },
        { label: "À propos", path: "/about", glyph: "mark" },
        { label: "Contact", path: "/contact", glyph: "send" },
      ],
      call: "Réserver un appel projet",
    },
  },
} as const;

export type OsCopy = (typeof OS_COPY)[Locale];
