import type { Locale } from "@/lib/i18n";

export const OS_COPY = {
  en: {
    menu: [
      ["Work", "/case-studies", "Shipped products and active private builds"],
      ["Services", "/services", "What MaydaLabs can design, build, measure, and operate"],
      ["About", "/about", "Studio principles, operating model, and founder context"],
      ["Profile", "/profile", "Mehmet’s evidence, capabilities, and hiring materials"],
    ],
    menubarHelp: {
      brand: "Open MaydaOS system information",
      startProjectLabel: "Start a project",
      startProject: "Start with a problem, idea, or rough brief",
      palette: "Search every page, case, and action",
      sound: "Toggle the optional interface sound",
      language: "Switch the interface language",
      block: "Latest observed Bitcoin block height",
    },
    boot: [
      "MAYDAOS 26.08 — signal kernel",
      "mounting /work .......... 4 transmissions",
      "telemetry link .......... up",
      "locales ................. en · tr · fr",
      "sound ................... off (SND to enable)",
      "boot complete — welcome",
    ],
    arrival: {
      label: "MaydaLabs first arrival",
      ready: "MaydaOS ready",
      eyebrow: "Product strategy · engineering · growth systems",
      body: "MaydaLabs turns ambitious product ideas and operational friction into software that ships, measures, and keeps working.",
      proof: "2 live products · 2 active private builds · founder-led end to end",
      enter: "Enter MaydaOS",
      enterHint: "Open the desktop, shell, telemetry, and product tools.",
      proofLabel: "Live product evidence",
      proofHint: "Choose a transmission",
      footer: "Istanbul / Everywhere",
    },
    welcome: {
      title: "welcome — read me",
      kicker: "MaydaLabs — product & growth studio",
      hero: ["We build software", "people can", "feel."],
      body: [
        "A founder-led studio for teams that need product strategy, engineering, measurement, and operation to stay connected.",
      ],
      proof: "Two live products you can inspect. Two active private builds. One hands-on builder from the first useful version through live operation.",
      intents: {
        start: ["Start with your problem", "No polished brief needed."],
        work: ["Inspect shipped work", "Open the product and the decisions behind it."],
        profile: ["Evaluating Mehmet?", "See evidence, range, and hiring materials."],
      },
      explore: "Explore MaydaOS freely",
    },
    workWindow: {
      title: "work — live transmissions",
      open: "Open case",
      intro: "Two live products. Open the interface, then inspect what was designed, built, and operated.",
      viewAll: "View all four transmissions",
      privateLabel: "Also in active private build",
      live: [
        { tx: "TX-01", name: "HodlStay", status: "Client build · Live", path: "/case-studies/hodlstay", image: "/work/hodlstay-2026-08-home.jpg", width: 1430, height: 894, alt: "HodlStay global stay marketplace", proof: "A Bitcoin-native stay marketplace spanning discovery, host operations, booking, payments, and migration." },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Studio product · Live", path: "/case-studies/satoshi-gazette", image: "/work/satoshi-gazette-2026-08-data.jpg", width: 1280, height: 720, alt: "Satoshi Gazette evidence-led Data Desk", proof: "An evidence-led Bitcoin newsroom with editorial systems, data desks, and automation built in." },
      ],
      rows: [
        { tx: "TX-01", name: "HodlStay", status: "Client build · Broadcasting", path: "/case-studies/hodlstay" },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Studio product · Broadcasting", path: "/case-studies/satoshi-gazette" },
        { tx: "TX-03", name: "Mortal Vault", status: "Private alpha · Encrypted", path: "/case-studies/mortal-vault" },
        { tx: "TX-04", name: "Sofra", status: "Phase 1 · Encrypted", path: "/case-studies/sofra" },
      ],
    },
    hodlstayWindow: { title: "hodlstay.com — TX-01", caption: "Bitcoin-native stay marketplace · client build", cta: "Inspect the case" },
    gazetteWindow: { title: "satoshigazette.org — TX-02", caption: "Bitcoin-only newsroom · studio product", cta: "Inspect the case" },
    monitorWindow: { title: "system monitor", scanning: "scanning…", noCarrier: "no carrier", block: "btc block height", network: "btc network", publicStatus: "public status" },
    arrayWindow: { title: "signal array — product map" },
    toasts: { block: "new block mined" },
    tour: {
      offer: "New here? Watch the 20-second tour",
      dock: "Tour",
      done: "your turn — this desktop is yours",
      skipped: "tour skipped — reduced motion is on",
    },
    terminalGuide: {
      welcome: "Start here. Type one command and press Enter:",
      entryNote: "Nothing is sent from this window. `help all` reveals the rest of MaydaOS.",
      routes: [
        { command: "meet", label: "Meet", detail: "open the calendar for a 30-minute discovery call" },
        { command: "idea", label: "Idea", detail: "present something you want to build" },
        { command: "problem", label: "Problem", detail: "describe what is getting in the way" },
      ],
      problem: {
        start: "No polished brief needed. Start with the friction.",
        questions: [
          "What is slow, fragile, manual, or unclear?",
          "Who feels it, and what happens if it stays this way?",
          "What exists today, or what has already been tried?",
        ],
        labels: ["FRICTION", "IMPACT", "TODAY"],
      },
      idea: {
        start: "Keep it rough. We are looking for the first useful shape.",
        questions: [
          "What should exist when this works?",
          "Who is it for, and what do they do today?",
          "What is the first useful outcome — not the full vision?",
        ],
        labels: ["IDEA", "FOR", "FIRST MOVE"],
      },
      answerHint: "Type an answer · `back` to revise · `cancel` to leave",
      inputPlaceholder: "meet, idea, or problem",
      draftPlaceholder: "review, meet, copy, or restart",
      answerPlaceholder: "type your answer",
      enterHint: "enter ↵",
      helpAll: "For products, proof, and OS commands: help all",
      backAtStart: "You are already at the first question.",
      cancelled: "Draft discarded. Nothing left this browser.",
      ready: "Draft ready. Nothing has been sent.",
      nextLabel: "Next:",
      reviewDetail: "open this in a private editable brief",
      meetDetail: "open the 30-minute calendar now",
      copyDetail: "place this draft on your clipboard",
      restartDetail: "answer the questions again",
      meetOpening: "Opening the 30-minute calendar in a new tab…",
      reviewOpening: "Opening your private editable brief…",
      noDraft: "No draft yet. Type `idea` or `problem` first.",
      copyUnavailable: "Clipboard access was blocked. Type `review` to continue with the draft instead.",
      handoffUnavailable: "This browser blocked the private handoff. Copy the draft instead; nothing was sent.",
      copied: "Copied",
    },
    terminalWindow: { title: "maydalabs — shell", hint: "type `help` to see what this thing can do" },
    dock: { welcome: "Read me", work: "Work", terminal: "Shell", monitor: "Monitor", services: "Services", about: "About", call: "What do you need?", trash: "Trash" },
    dockHelp: {
      welcome: "Studio orientation and current product status",
      work: "All four product transmissions",
      terminal: "Create a guided session or control MaydaOS",
      monitor: "Live product and Bitcoin telemetry",
      array: "How the products and capabilities connect",
      services: "Product engineering and growth-system scope",
      about: "Studio principles and operating model",
      call: "Shape a project brief without booking a call",
      tour: "Watch MaydaOS operate itself",
      trash: "A small archive of things we refuse to ship",
    },
    aboutWindow: {
      title: "about this mayda",
      rows: [
        ["Version", "MaydaOS 26.08"],
        ["Kernel", "signal / 26.08"],
        ["Shell", "mayda-sh 1.0"],
        ["Display", "Bitcoin orange"],
        ["Memory", "enough"],
        ["Locales", "EN · TR · FR"],
      ],
      uptime: "Uptime",
      footer: "Built in the open by MaydaLabs — Istanbul / Everywhere.",
    },
    trashWindow: {
      title: "trash",
      items: ["agency_theatre.zip — 4.2 GB", "endless_revisions_final_FINAL_v7.psd", "buzzword_strategy_deck.pptx", "scope_creep.log"],
      empty: "Empty trash",
      emptied: "already empty where it counts.",
    },
    palette: {
      placeholder: "Type to jump — pages, cases, actions…",
      hint: "⌘K anywhere · ↑↓ to move · ⏎ to run",
      empty: "no signal on that frequency",
      items: [
        { label: "Desktop", kind: "page", target: "/" },
        { label: "Work — all transmissions", kind: "page", target: "/case-studies" },
        { label: "HodlStay — TX-01", kind: "page", target: "/case-studies/hodlstay" },
        { label: "Satoshi Gazette — TX-02", kind: "page", target: "/case-studies/satoshi-gazette" },
        { label: "Mortal Vault — TX-03", kind: "page", target: "/case-studies/mortal-vault" },
        { label: "Sofra — TX-04", kind: "page", target: "/case-studies/sofra" },
        { label: "Services", kind: "page", target: "/services" },
        { label: "About the studio", kind: "page", target: "/about" },
        { label: "Contact — start something", kind: "page", target: "/contact" },
        { label: "Shape a project brief", kind: "call", target: "/contact" },
        { label: "Toggle interface sound", kind: "sound", target: "" },
      ],
    },
    screensaver: { line: "signal never sleeps", wake: "move to wake" },
    mobile: {
      greeting: "MaydaOS",
      sub: "Software people can feel.",
      appsLabel: "MaydaOS tools",
      apps: [
        { label: "Work", path: "/case-studies", glyph: "grid" },
        { label: "Services", path: "/services", glyph: "layers" },
        { label: "About", path: "/about", glyph: "mark" },
        { label: "Profile", path: "/profile", glyph: "doc" },
        { label: "Contact", path: "/contact", glyph: "send" },
      ],
    },
  },
  tr: {
    menu: [
      ["Projeler", "/case-studies", "Yayındaki ürünler ve aktif özel geliştirmeler"],
      ["Hizmetler", "/services", "MaydaLabs'in tasarladığı, geliştirdiği, ölçtüğü ve işlettiği sistemler"],
      ["Hakkımızda", "/about", "Stüdyo ilkeleri, çalışma modeli ve kurucu bağlamı"],
      ["Profil", "/profile", "Mehmet'in kanıtları, yetkinlikleri ve işe alım materyalleri"],
    ],
    menubarHelp: {
      brand: "MaydaOS sistem bilgisini aç",
      startProjectLabel: "Proje başlat",
      startProject: "Bir problem, fikir veya ham brief ile başlayın",
      palette: "Tüm sayfa, vaka ve eylemlerde ara",
      sound: "İsteğe bağlı arayüz sesini aç veya kapat",
      language: "Arayüz dilini değiştir",
      block: "Gözlenen son Bitcoin blok yüksekliği",
    },
    boot: [
      "MAYDAOS 26.08 — sinyal çekirdeği",
      "/work bağlanıyor ........ 4 yayın",
      "telemetri bağlantısı .... açık",
      "diller .................. en · tr · fr",
      "ses ..................... kapalı (SND ile açın)",
      "açılış tamam — hoş geldiniz",
    ],
    arrival: {
      label: "MaydaLabs ilk karşılama",
      ready: "MaydaOS hazır",
      eyebrow: "Ürün stratejisi · mühendislik · büyüme sistemleri",
      body: "MaydaLabs; iddialı ürün fikirlerini ve operasyonel sürtünmeleri yayına çıkan, ölçülen ve çalışmaya devam eden yazılımlara dönüştürür.",
      proof: "2 canlı ürün · 2 aktif özel geliştirme · uçtan uca kurucu liderliği",
      enter: "MaydaOS'e girin",
      enterHint: "Masaüstünü, kabuğu, telemetriyi ve ürün araçlarını açın.",
      proofLabel: "Canlı ürün kanıtı",
      proofHint: "Bir yayın seçin",
      footer: "İstanbul / Her yer",
    },
    welcome: {
      title: "hoş geldiniz — beni oku",
      kicker: "MaydaLabs — ürün ve büyüme stüdyosu",
      hero: ["İnsanların hissedebileceği", "yazılımlar", "geliştiriyoruz."],
      body: [
        "Ürün stratejisi, mühendislik, ölçüm ve operasyonun birbirinden kopmaması gereken ekipler için kurucu liderliğinde çalışan bir stüdyo.",
      ],
      proof: "İnceleyebileceğiniz iki canlı ürün. İki aktif özel geliştirme. İlk faydalı sürümden canlı operasyona kadar işin içinde tek bir üretici.",
      intents: {
        start: ["Probleminizle başlayın", "Kusursuz bir brief gerekmiyor."],
        work: ["Yayınlanmış işleri inceleyin", "Ürünü ve arkasındaki kararları açın."],
        profile: ["Mehmet'i değerlendiriyor musunuz?", "Kanıtları, yetkinlikleri ve işe alım materyallerini görün."],
      },
      explore: "MaydaOS'i özgürce keşfedin",
    },
    workWindow: {
      title: "projeler — canlı yayınlar",
      open: "Vakayı aç",
      intro: "İki canlı ürün. Arayüzü açın; ardından neyin tasarlandığını, geliştirildiğini ve işletildiğini inceleyin.",
      viewAll: "Dört yayının tamamını görün",
      privateLabel: "Aktif özel geliştirmede olanlar",
      live: [
        { tx: "TX-01", name: "HodlStay", status: "Müşteri projesi · Canlı", path: "/case-studies/hodlstay", image: "/work/hodlstay-2026-08-home.jpg", width: 1430, height: 894, alt: "HodlStay küresel konaklama pazarı", proof: "Keşif, ev sahibi operasyonları, rezervasyon, ödeme ve veri göçünü kapsayan Bitcoin-native konaklama pazarı." },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Stüdyo ürünü · Canlı", path: "/case-studies/satoshi-gazette", image: "/work/satoshi-gazette-2026-08-data.jpg", width: 1280, height: 720, alt: "Satoshi Gazette kanıt odaklı Veri Masası", proof: "Editoryal sistemleri, veri masaları ve otomasyonu ürünün içine yerleştirilmiş kanıt odaklı Bitcoin haber merkezi." },
      ],
      rows: [
        { tx: "TX-01", name: "HodlStay", status: "Müşteri projesi · Yayında", path: "/case-studies/hodlstay" },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Stüdyo ürünü · Yayında", path: "/case-studies/satoshi-gazette" },
        { tx: "TX-03", name: "Mortal Vault", status: "Özel alpha · Şifreli", path: "/case-studies/mortal-vault" },
        { tx: "TX-04", name: "Sofra", status: "Faz 1 · Şifreli", path: "/case-studies/sofra" },
      ],
    },
    hodlstayWindow: { title: "hodlstay.com — TX-01", caption: "Bitcoin-native konaklama pazar yeri · müşteri projesi", cta: "Vakayı incele" },
    gazetteWindow: { title: "satoshigazette.org — TX-02", caption: "Yalnızca Bitcoin haber merkezi · stüdyo ürünü", cta: "Vakayı incele" },
    monitorWindow: { title: "sistem monitörü", scanning: "taranıyor…", noCarrier: "sinyal yok", block: "btc blok yüksekliği", network: "btc ağı", publicStatus: "açık durum" },
    arrayWindow: { title: "sinyal dizisi — ürün haritası" },
    toasts: { block: "yeni blok kazıldı" },
    tour: {
      offer: "Yeni misiniz? 20 saniyelik turu izleyin",
      dock: "Tur",
      done: "sıra sizde — bu masaüstü sizin",
      skipped: "tur atlandı — azaltılmış hareket açık",
    },
    terminalGuide: {
      welcome: "Buradan başlayın. Bir komut yazıp Enter'a basın:",
      entryNote: "Bu pencereden hiçbir şey gönderilmez. MaydaOS'in geri kalanı için `help all` yazın.",
      routes: [
        { command: "meet", label: "Görüşme", detail: "30 dakikalık keşif görüşmesi için takvimi aç" },
        { command: "idea", label: "Fikir", detail: "geliştirmek istediğiniz şeyi anlatın" },
        { command: "problem", label: "Problem", detail: "önünüzdeki engeli tarif edin" },
      ],
      problem: {
        start: "Kusursuz bir brief gerekmiyor. Sürtünmeden başlayın.",
        questions: [
          "Yavaş, kırılgan, manuel veya belirsiz olan ne?",
          "Bunu kim hissediyor ve böyle kalırsa ne oluyor?",
          "Bugün ne var veya daha önce ne denendi?",
        ],
        labels: ["SÜRTÜNME", "ETKİ", "BUGÜN"],
      },
      idea: {
        start: "Ham bırakın. İlk faydalı şekli arıyoruz.",
        questions: [
          "Bu çalıştığında ne var olmalı?",
          "Kimin için ve bugün ne yapıyorlar?",
          "Tüm vizyon değil, ilk faydalı sonuç ne?",
        ],
        labels: ["FİKİR", "KİMİN İÇİN", "İLK HAMLE"],
      },
      answerHint: "Yanıtınızı yazın · düzeltmek için `back` · çıkmak için `cancel`",
      inputPlaceholder: "meet, idea veya problem",
      draftPlaceholder: "review, meet, copy veya restart",
      answerPlaceholder: "yanıtınızı yazın",
      enterHint: "enter ↵",
      helpAll: "Ürünler, kanıtlar ve OS komutları için: help all",
      backAtStart: "Zaten ilk sorudasınız.",
      cancelled: "Taslak silindi. Bu tarayıcıdan hiçbir şey çıkmadı.",
      ready: "Taslak hazır. Henüz hiçbir şey gönderilmedi.",
      nextLabel: "Sıradaki adım:",
      reviewDetail: "özel ve düzenlenebilir brief'te aç",
      meetDetail: "30 dakikalık takvimi şimdi aç",
      copyDetail: "bu taslağı panoya al",
      restartDetail: "soruları yeniden yanıtla",
      meetOpening: "30 dakikalık takvim yeni sekmede açılıyor…",
      reviewOpening: "Özel ve düzenlenebilir brief'iniz açılıyor…",
      noDraft: "Henüz taslak yok. Önce `idea` veya `problem` yazın.",
      copyUnavailable: "Panoya erişim engellendi. Taslakla devam etmek için `review` yazın.",
      handoffUnavailable: "Tarayıcı özel aktarımı engelledi. Taslağı kopyalayın; hiçbir şey gönderilmedi.",
      copied: "Kopyalandı",
    },
    terminalWindow: { title: "maydalabs — kabuk", hint: "`help` yazarak neler yapabildiğini görün" },
    dock: { welcome: "Beni oku", work: "Projeler", terminal: "Kabuk", monitor: "Monitör", services: "Hizmetler", about: "Hakkımızda", call: "Neye ihtiyacınız var?", trash: "Çöp" },
    dockHelp: {
      welcome: "Stüdyo yönlendirmesi ve güncel ürün durumu",
      work: "Dört ürün yayınının tamamı",
      terminal: "Rehberli oturum oluşturun veya MaydaOS'i kontrol edin",
      monitor: "Canlı ürün ve Bitcoin telemetrisi",
      array: "Ürün ve yetkinliklerin nasıl bağlandığı",
      services: "Ürün mühendisliği ve büyüme sistemleri kapsamı",
      about: "Stüdyo ilkeleri ve çalışma modeli",
      call: "Görüşme ayarlamadan proje brief'i oluşturun",
      tour: "MaydaOS'in kendini çalıştırmasını izleyin",
      trash: "Yayınlamayı reddettiğimiz şeylerin küçük arşivi",
    },
    aboutWindow: {
      title: "bu mayda hakkında",
      rows: [
        ["Sürüm", "MaydaOS 26.08"],
        ["Çekirdek", "sinyal / 26.08"],
        ["Kabuk", "mayda-sh 1.0"],
        ["Ekran", "Bitcoin turuncusu"],
        ["Bellek", "yeterli"],
        ["Diller", "EN · TR · FR"],
      ],
      uptime: "Çalışma süresi",
      footer: "MaydaLabs tarafından açıkta geliştirildi — İstanbul / Her yer.",
    },
    trashWindow: {
      title: "çöp",
      items: ["ajans_tiyatrosu.zip — 4.2 GB", "sonsuz_revizyon_final_SON_v7.psd", "moda_kelime_sunumu.pptx", "kapsam_kaymasi.log"],
      empty: "Çöpü boşalt",
      emptied: "önemli olan yerde zaten boş.",
    },
    palette: {
      placeholder: "Yazın ve atlayın — sayfalar, vakalar, eylemler…",
      hint: "Her yerde ⌘K · ↑↓ gezin · ⏎ çalıştır",
      empty: "bu frekansta sinyal yok",
      items: [
        { label: "Masaüstü", kind: "page", target: "/" },
        { label: "Projeler — tüm yayınlar", kind: "page", target: "/case-studies" },
        { label: "HodlStay — TX-01", kind: "page", target: "/case-studies/hodlstay" },
        { label: "Satoshi Gazette — TX-02", kind: "page", target: "/case-studies/satoshi-gazette" },
        { label: "Mortal Vault — TX-03", kind: "page", target: "/case-studies/mortal-vault" },
        { label: "Sofra — TX-04", kind: "page", target: "/case-studies/sofra" },
        { label: "Hizmetler", kind: "page", target: "/services" },
        { label: "Stüdyo hakkında", kind: "page", target: "/about" },
        { label: "İletişim — bir şey başlat", kind: "page", target: "/contact" },
        { label: "Proje brief'i oluştur", kind: "call", target: "/contact" },
        { label: "Arayüz sesini aç/kapat", kind: "sound", target: "" },
      ],
    },
    screensaver: { line: "sinyal hiç uyumaz", wake: "uyandırmak için hareket edin" },
    mobile: {
      greeting: "MaydaOS",
      sub: "Hissedebileceğiniz yazılımlar.",
      appsLabel: "MaydaOS araçları",
      apps: [
        { label: "Projeler", path: "/case-studies", glyph: "grid" },
        { label: "Hizmetler", path: "/services", glyph: "layers" },
        { label: "Hakkımızda", path: "/about", glyph: "mark" },
        { label: "Profil", path: "/profile", glyph: "doc" },
        { label: "İletişim", path: "/contact", glyph: "send" },
      ],
    },
  },
  fr: {
    menu: [
      ["Projets", "/case-studies", "Produits en ligne et constructions privées actives"],
      ["Services", "/services", "Ce que MaydaLabs peut concevoir, construire, mesurer et opérer"],
      ["À propos", "/about", "Principes du studio, modèle opérationnel et contexte fondateur"],
      ["Profil", "/profile", "Preuves, capacités et matériel de recrutement de Mehmet"],
    ],
    menubarHelp: {
      brand: "Ouvrir les informations système de MaydaOS",
      startProjectLabel: "Lancer un projet",
      startProject: "Commencer par un problème, une idée ou un brief brut",
      palette: "Rechercher toutes les pages, études et actions",
      sound: "Activer ou couper le son optionnel de l'interface",
      language: "Changer la langue de l'interface",
      block: "Dernière hauteur de bloc Bitcoin observée",
    },
    boot: [
      "MAYDAOS 26.08 — noyau signal",
      "montage de /work ........ 4 transmissions",
      "lien télémétrie ......... actif",
      "langues ................. en · tr · fr",
      "son ..................... coupé (SND pour activer)",
      "démarrage terminé — bienvenue",
    ],
    arrival: {
      label: "Première arrivée chez MaydaLabs",
      ready: "MaydaOS prêt",
      eyebrow: "Stratégie produit · ingénierie · systèmes de croissance",
      body: "MaydaLabs transforme les idées produit ambitieuses et les frictions opérationnelles en logiciels livrés, mesurés et durables.",
      proof: "2 produits en ligne · 2 constructions privées · pilotage fondateur de bout en bout",
      enter: "Entrer dans MaydaOS",
      enterHint: "Ouvrez le bureau, le shell, la télémétrie et les outils produit.",
      proofLabel: "Preuves produit en direct",
      proofHint: "Choisissez une transmission",
      footer: "Istanbul / Partout",
    },
    welcome: {
      title: "bienvenue — lisez-moi",
      kicker: "MaydaLabs — studio produit et croissance",
      hero: ["Nous créons des logiciels", "que l’on peut", "ressentir."],
      body: [
        "Un studio dirigé par son fondateur pour les équipes qui veulent garder stratégie produit, ingénierie, mesure et opérations reliées.",
      ],
      proof: "Deux produits en ligne à inspecter. Deux constructions privées actives. Un builder impliqué de la première version utile aux opérations en production.",
      intents: {
        start: ["Commencez par votre problème", "Aucun brief parfait n'est nécessaire."],
        work: ["Inspectez le travail livré", "Ouvrez le produit et les décisions qui l'ont façonné."],
        profile: ["Vous évaluez Mehmet ?", "Voyez les preuves, l'étendue et les éléments de recrutement."],
      },
      explore: "Explorez MaydaOS librement",
    },
    workWindow: {
      title: "projets — transmissions en direct",
      open: "Ouvrir le cas",
      intro: "Deux produits en ligne. Ouvrez l'interface, puis inspectez ce qui a été conçu, construit et opéré.",
      viewAll: "Voir les quatre transmissions",
      privateLabel: "Également en construction privée active",
      live: [
        { tx: "TX-01", name: "HodlStay", status: "Projet client · En ligne", path: "/case-studies/hodlstay", image: "/work/hodlstay-2026-08-home.jpg", width: 1430, height: 894, alt: "Marketplace mondiale de séjours HodlStay", proof: "Une marketplace de séjours Bitcoin-native couvrant découverte, opérations hôtes, réservation, paiements et migration." },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Produit studio · En ligne", path: "/case-studies/satoshi-gazette", image: "/work/satoshi-gazette-2026-08-data.jpg", width: 1280, height: 720, alt: "Data Desk de Satoshi Gazette fondé sur les preuves", proof: "Une rédaction Bitcoin fondée sur les preuves, avec systèmes éditoriaux, data desks et automatisation intégrés." },
      ],
      rows: [
        { tx: "TX-01", name: "HodlStay", status: "Projet client · En émission", path: "/case-studies/hodlstay" },
        { tx: "TX-02", name: "Satoshi Gazette", status: "Produit studio · En émission", path: "/case-studies/satoshi-gazette" },
        { tx: "TX-03", name: "Mortal Vault", status: "Alpha privée · Chiffré", path: "/case-studies/mortal-vault" },
        { tx: "TX-04", name: "Sofra", status: "Phase 1 · Chiffré", path: "/case-studies/sofra" },
      ],
    },
    hodlstayWindow: { title: "hodlstay.com — TX-01", caption: "Marketplace de séjours Bitcoin-native · projet client", cta: "Voir le cas" },
    gazetteWindow: { title: "satoshigazette.org — TX-02", caption: "Rédaction 100 % Bitcoin · produit du studio", cta: "Voir le cas" },
    monitorWindow: { title: "moniteur système", scanning: "balayage…", noCarrier: "pas de signal", block: "hauteur de bloc btc", network: "réseau btc", publicStatus: "statut public" },
    arrayWindow: { title: "réseau de signaux — carte produit" },
    toasts: { block: "nouveau bloc miné" },
    tour: {
      offer: "Première visite ? Regardez le tour de 20 secondes",
      dock: "Visite",
      done: "à vous — ce bureau est le vôtre",
      skipped: "visite ignorée — mouvement réduit activé",
    },
    terminalGuide: {
      welcome: "Commencez ici. Tapez une commande puis Entrée :",
      entryNote: "Rien n'est envoyé depuis cette fenêtre. `help all` révèle le reste de MaydaOS.",
      routes: [
        { command: "meet", label: "Rendez-vous", detail: "ouvrir l'agenda pour un échange découverte de 30 minutes" },
        { command: "idea", label: "Idée", detail: "présenter ce que vous souhaitez construire" },
        { command: "problem", label: "Problème", detail: "décrire ce qui vous bloque" },
      ],
      problem: {
        start: "Pas besoin d’un brief parfait. Commencez par la friction.",
        questions: [
          "Qu’est-ce qui est lent, fragile, manuel ou flou ?",
          "Qui le ressent, et que se passe-t-il si rien ne change ?",
          "Qu’existe-t-il aujourd’hui, ou qu’avez-vous déjà essayé ?",
        ],
        labels: ["FRICTION", "IMPACT", "AUJOURD’HUI"],
      },
      idea: {
        start: "Gardez-la brute. Nous cherchons la première forme utile.",
        questions: [
          "Que devrait-il exister lorsque cela fonctionne ?",
          "Pour qui, et que font ces personnes aujourd’hui ?",
          "Quel est le premier résultat utile — pas toute la vision ?",
        ],
        labels: ["IDÉE", "POUR", "PREMIER PAS"],
      },
      answerHint: "Tapez une réponse · `back` pour corriger · `cancel` pour quitter",
      inputPlaceholder: "meet, idea ou problem",
      draftPlaceholder: "review, meet, copy ou restart",
      answerPlaceholder: "tapez votre réponse",
      enterHint: "entrée ↵",
      helpAll: "Pour les produits, les preuves et l'OS : help all",
      backAtStart: "Vous êtes déjà à la première question.",
      cancelled: "Brouillon supprimé. Rien n’a quitté ce navigateur.",
      ready: "Brouillon prêt. Rien n'a encore été envoyé.",
      nextLabel: "Suite :",
      reviewDetail: "ouvrir le brief privé et modifiable",
      meetDetail: "ouvrir maintenant l'agenda de 30 minutes",
      copyDetail: "placer ce brouillon dans le presse-papiers",
      restartDetail: "répondre à nouveau",
      meetOpening: "Ouverture de l'agenda de 30 minutes dans un nouvel onglet…",
      reviewOpening: "Ouverture de votre brief privé et modifiable…",
      noDraft: "Aucun brouillon. Tapez d'abord `idea` ou `problem`.",
      copyUnavailable: "Accès au presse-papiers bloqué. Tapez `review` pour continuer avec le brouillon.",
      handoffUnavailable: "Le navigateur a bloqué le transfert privé. Copiez le brouillon ; rien n’a été envoyé.",
      copied: "Copié",
    },
    terminalWindow: { title: "maydalabs — shell", hint: "tapez `help` pour voir ce que ça sait faire" },
    dock: { welcome: "Lisez-moi", work: "Projets", terminal: "Shell", monitor: "Moniteur", services: "Services", about: "À propos", call: "Votre besoin", trash: "Corbeille" },
    dockHelp: {
      welcome: "Orientation du studio et état actuel des produits",
      work: "Les quatre transmissions produit",
      terminal: "Créer une session guidée ou contrôler MaydaOS",
      monitor: "Télémétrie produit et Bitcoin en direct",
      array: "Comment produits et capacités se connectent",
      services: "Périmètre ingénierie produit et systèmes de croissance",
      about: "Principes du studio et modèle opérationnel",
      call: "Structurer un brief sans réserver d'appel",
      tour: "Regarder MaydaOS se piloter",
      trash: "Une petite archive de ce que nous refusons de livrer",
    },
    aboutWindow: {
      title: "à propos de ce mayda",
      rows: [
        ["Version", "MaydaOS 26.08"],
        ["Noyau", "signal / 26.08"],
        ["Shell", "mayda-sh 1.0"],
        ["Écran", "orange Bitcoin"],
        ["Mémoire", "suffisante"],
        ["Langues", "EN · TR · FR"],
      ],
      uptime: "Uptime",
      footer: "Construit au grand jour par MaydaLabs — Istanbul / Partout.",
    },
    trashWindow: {
      title: "corbeille",
      items: ["theatre_agence.zip — 4,2 Go", "revisions_sans_fin_final_FINAL_v7.psd", "deck_buzzwords.pptx", "derive_du_scope.log"],
      empty: "Vider la corbeille",
      emptied: "déjà vide là où ça compte.",
    },
    palette: {
      placeholder: "Tapez pour naviguer — pages, cas, actions…",
      hint: "⌘K partout · ↑↓ naviguer · ⏎ lancer",
      empty: "aucun signal sur cette fréquence",
      items: [
        { label: "Bureau", kind: "page", target: "/" },
        { label: "Projets — toutes les transmissions", kind: "page", target: "/case-studies" },
        { label: "HodlStay — TX-01", kind: "page", target: "/case-studies/hodlstay" },
        { label: "Satoshi Gazette — TX-02", kind: "page", target: "/case-studies/satoshi-gazette" },
        { label: "Mortal Vault — TX-03", kind: "page", target: "/case-studies/mortal-vault" },
        { label: "Sofra — TX-04", kind: "page", target: "/case-studies/sofra" },
        { label: "Services", kind: "page", target: "/services" },
        { label: "À propos du studio", kind: "page", target: "/about" },
        { label: "Contact — démarrer quelque chose", kind: "page", target: "/contact" },
        { label: "Structurer un brief projet", kind: "call", target: "/contact" },
        { label: "Activer/couper le son", kind: "sound", target: "" },
      ],
    },
    screensaver: { line: "le signal ne dort jamais", wake: "bougez pour réveiller" },
    mobile: {
      greeting: "MaydaOS",
      sub: "Du logiciel que l’on ressent.",
      appsLabel: "Outils MaydaOS",
      apps: [
        { label: "Projets", path: "/case-studies", glyph: "grid" },
        { label: "Services", path: "/services", glyph: "layers" },
        { label: "À propos", path: "/about", glyph: "mark" },
        { label: "Profil", path: "/profile", glyph: "doc" },
        { label: "Contact", path: "/contact", glyph: "send" },
      ],
    },
  },
} as const;

export type OsCopy = (typeof OS_COPY)[Locale];
