import { InProgressCaseStudy } from "@/components/InProgressCaseStudy";
import { getPageLocale, type LocalePageProps } from "@/lib/localePage";
import { createPageMetadata } from "@/lib/metadata";

const COPY = {
  en: {
    meta: { title: "Sofra case study", socialTitle: "Sofra: a managed household dinner marketplace · MaydaLabs", description: "A private Phase 1 MaydaLabs product connecting household-hosted dinners, trust, privacy, and bilingual marketplace operations." },
    back: "Selected work", kicker: "Work in progress 04 / Private Phase 1", status: "Private Phase 1", statusNote: "Active development · demo-safe", scope: "Current scope", scopeItems: ["Next.js", "Supabase", "EN/TR", "Marketplace ops"], hero: ["A dinner marketplace built around", "trust at home."], lead: "Sofra is a Türkiye-first managed marketplace for scheduled dinners in verified households. The product treats each table as inventory and the full evening—from welcome to tea—as the experience.", visitWork: "Inspect the current build", builtKicker: "Current build / Product evidence", builtTitle: "The household is the venue. Trust is the system.", boundary: "The current Phase 1 build connects public discovery to host, guest, and operator workflows while deliberately separating public presentation from exact household and safety data.", built: [["01", "Managed marketplace lifecycle", "Hosts apply, the platform approves, tables are scheduled, guests book, operators oversee, and completion and reviews remain explicit states."], ["02", "Household privacy boundary", "Public table projections can show approximate area and product context while exact addresses, coordinates, dietary details, assessments, and safety data remain private."], ["03", "Bilingual product system", "English and Turkish journeys share the same Next.js application, navigation, messages, host tools, guest account, and operator surfaces."], ["04", "Demo-safe infrastructure", "Repository adapters and seeded journeys make the product testable without pretending that production services, real payments, or real customer activity exist." ]], boundaryKicker: "Honest boundary / What this is not", boundaryTitle: "Phase 1 is a product, not a launch claim.", boundaryItems: ["No public launch, real booking volume, host network, or commercial outcome is claimed.", "Payments are not connected to real production processing.", "Demo records are product evidence, not evidence of real people or transactions.", "Brand, photography, policies, and operating choices remain open to iteration."], nextKicker: "Next gates / Toward a real pilot", next: "Validate the marketplace with people.", nextItems: ["Complete the remaining guest, host, and operator lifecycle checks.", "Replace demo photography and records with approved pilot material.", "Validate trust, incident, pricing, and payout operations with counsel and real operators.", "Connect production services only after privacy and operational gates pass."], ctaKicker: "Building a marketplace where trust matters?", cta: ["Design the public promise.", "Protect the private truth."], start: "Start a project",
  },
  tr: {
    meta: { title: "Sofra vaka çalışması", socialTitle: "Sofra: yönetilen ev yemeği pazarı · MaydaLabs", description: "Evlerde düzenlenen yemekleri, güveni, gizliliği ve iki dilli pazar yeri operasyonlarını bağlayan özel Phase 1 MaydaLabs ürünü." },
    back: "Seçili projeler", kicker: "Geliştirme aşamasında 04 / Özel Phase 1", status: "Özel Phase 1", statusNote: "Aktif geliştirme · demo güvenli", scope: "Mevcut kapsam", scopeItems: ["Next.js", "Supabase", "EN/TR", "Pazar operasyonu"], hero: ["Evde güven etrafında kurulan", "akşam yemeği pazarı."], lead: "Sofra, doğrulanmış hanelerde planlı akşam yemekleri için Türkiye odaklı yönetilen bir pazar yeridir. Her sofra envanter; karşılamadan çaya kadar tüm akşam ise deneyimdir.", visitWork: "Mevcut ürünü incele", builtKicker: "Mevcut ürün / Ürün kanıtı", builtTitle: "Mekân evdir. Sistem güvendir.", boundary: "Mevcut Phase 1 ürün açık keşfi ev sahibi, misafir ve operatör akışlarına bağlarken açık sunumu tam hane ve güvenlik verilerinden bilinçli olarak ayırır.", built: [["01", "Yönetilen pazar yaşam döngüsü", "Ev sahipleri başvurur, platform onaylar, sofralar planlanır, misafirler ayırır, operatörler izler; tamamlama ve yorumlar açık durumlardır."], ["02", "Hane gizliliği sınırı", "Açık yüzey yaklaşık bölge ve ürün bağlamını gösterebilir; tam adres, koordinat, beslenme, değerlendirme ve güvenlik verileri özel kalır."], ["03", "İki dilli ürün sistemi", "İngilizce ve Türkçe yolculuklar aynı Next.js uygulaması, navigasyon, mesajlar, ev sahibi, misafir hesabı ve operatör yüzeylerini paylaşır."], ["04", "Demo güvenli altyapı", "Adapter'lar ve seed yolculukları, üretim servisleri, gerçek ödemeler veya müşteri aktivitesi varmış gibi göstermeden ürünü test edilebilir kılar." ]], boundaryKicker: "Dürüst sınır / Ne değildir", boundaryTitle: "Phase 1 bir üründür; lansman iddiası değil.", boundaryItems: ["Herkese açık lansman, gerçek rezervasyon hacmi, ev sahibi ağı veya ticari sonuç iddia edilmez.", "Ödemeler gerçek üretim işlemlerine bağlı değildir.", "Demo kayıtları ürün kanıtıdır; gerçek kişi veya işlem kanıtı değildir.", "Marka, fotoğraf, politikalar ve işletim kararları iterasyona açıktır."], nextKicker: "Sonraki kapılar / Gerçek pilot yolunda", next: "Pazar yerini insanlarla doğrula.", nextItems: ["Kalan misafir, ev sahibi ve operatör yaşam döngüsü kontrollerini tamamla.", "Demo fotoğraf ve kayıtlarını onaylı pilot materyaliyle değiştir.", "Güven, olay, fiyat ve ödeme operasyonlarını uzmanlar ve gerçek operatörlerle doğrula.", "Üretim servislerini yalnızca gizlilik ve operasyon kapıları geçilince bağla."], ctaKicker: "Güvenin önemli olduğu bir pazar mı geliştiriyorsunuz?", cta: ["Açık vaadi tasarlayın.", "Özel gerçeği koruyun."], start: "Proje başlat",
  },
  fr: {
    meta: { title: "Étude de cas Sofra", socialTitle: "Sofra : marketplace gérée de dîners chez l’habitant · MaydaLabs", description: "Un produit MaydaLabs privé en Phase 1 reliant dîners chez l’habitant, confiance, confidentialité et opérations bilingues." },
    back: "Projets sélectionnés", kicker: "En cours 04 / Phase 1 privée", status: "Phase 1 privée", statusNote: "Construction active · démo sûre", scope: "Périmètre actuel", scopeItems: ["Next.js", "Supabase", "EN/TR", "Opérations"], hero: ["Une marketplace de dîners fondée sur", "la confiance à domicile."], lead: "Sofra est une marketplace gérée, pensée d’abord pour la Türkiye, pour des dîners planifiés dans des foyers vérifiés. Chaque table est l’inventaire et toute la soirée est l’expérience.", visitWork: "Inspecter le produit actuel", builtKicker: "Produit actuel / Preuves produit", builtTitle: "Le foyer est le lieu. La confiance est le système.", boundary: "La Phase 1 relie découverte publique, hôtes, voyageurs et opérateurs tout en séparant la présentation publique des données exactes du foyer et de sécurité.", built: [["01", "Cycle de marketplace géré", "Candidature, approbation, planification, réservation, supervision, clôture et avis sont des états explicites."], ["02", "Limite de confidentialité", "La zone approximative peut être publique; adresses, coordonnées, régimes, évaluations et sécurité restent privés."], ["03", "Système bilingue", "Les parcours anglais et turcs partagent application Next.js, navigation, messages, outils hôtes, compte invité et opérations."], ["04", "Infrastructure de démo sûre", "Adaptateurs et parcours de démonstration permettent de tester sans prétendre à des services, paiements ou clients réels." ]], boundaryKicker: "Limite honnête / Ce que ce n’est pas", boundaryTitle: "La Phase 1 est un produit, pas un lancement.", boundaryItems: ["Aucun lancement, volume, réseau d’hôtes ou résultat commercial n’est revendiqué.", "Les paiements ne sont pas reliés à un traitement réel.", "Les données de démo prouvent le produit, pas des personnes ou transactions réelles.", "Marque, photos, politiques et opérations restent ouvertes à l’itération."], nextKicker: "Prochaines conditions / Vers un pilote", next: "Valider avec de vraies personnes.", nextItems: ["Terminer les contrôles des cycles invité, hôte et opérateur.", "Remplacer photos et données de démo par du matériel de pilote approuvé.", "Valider confiance, incidents, prix et versements avec experts et opérateurs.", "Connecter les services réels après les conditions de confidentialité et d’opérations."], ctaKicker: "Vous construisez une marketplace de confiance ?", cta: ["Concevez la promesse publique.", "Protégez la vérité privée."], start: "Lancer un projet",
  },
} as const;

export async function generateMetadata({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  return createPageMetadata({ ...COPY[locale].meta, path: "/case-studies/sofra", locale, socialCard: "sofra" });
}

export default async function SofraCaseStudyPage({ params }: LocalePageProps) {
  const locale = await getPageLocale(params);
  return <InProgressCaseStudy copy={COPY[locale]} locale={locale} name="Sofra" variant="sofra" />;
}
