import { LegalDocument } from "@/components/LegalDocument";
import { getPageLocale, type LocalePageProps } from "@/lib/localePage";
import { createPageMetadata } from "@/lib/metadata";

const COPY = {
  en: { meta: { title: "Website terms", socialTitle: "Website terms · MaydaLabs", description: "Plain-language terms for using the MaydaLabs website and contacting the studio about project work." }, kicker: "Legal / Website terms", heading: ["Clear terms.", "Real agreements."], introduction: "These terms govern the public website. Actual client work is governed by a separate written project agreement.", updated: "Last updated · 22 July 2026", documentTitle: "Website terms", contactTitle: "Contact", contactCopy: "Questions about these terms can be sent to", contactLink: "Discuss a project", sections: [
    { number: "01", title: "Using this website", paragraphs: ["You may browse and share links to this website for lawful purposes. Do not disrupt the site, seek unauthorized access, harm availability through scraping, or misrepresent MaydaLabs and its work."] },
    { number: "02", title: "Information, not a promise", paragraphs: ["The website describes MaydaLabs capabilities, selected work, and points of view. It is not legal, financial, tax, or other regulated professional advice.", "Project examples do not guarantee that another project will produce the same result, timeline, or commercial outcome."] },
    { number: "03", title: "Project engagements", paragraphs: ["A project call, email, proposal, or estimate does not by itself create a client relationship. Scope, fees, ownership, confidentiality, responsibilities, and delivery terms are agreed separately in writing."] },
    { number: "04", title: "Work and intellectual property", paragraphs: ["The MaydaLabs name, site design, writing, graphics, and original materials may not be republished or presented as another party’s work without permission.", "Client and flagship product names, screenshots, and trademarks belong to their respective owners. Project ownership is governed by the applicable agreement."] },
    { number: "05", title: "Availability and external services", paragraphs: ["We aim to keep the site accurate and available, but it may change, contain errors, or be interrupted. MaydaLabs does not control the availability, content, or terms of external services."] },
    { number: "06", title: "Updates", paragraphs: ["These terms may change as the site and studio evolve. The current version will be published here with its revision date."] },
  ] },
  tr: { meta: { title: "Web sitesi koşulları", socialTitle: "Web sitesi koşulları · MaydaLabs", description: "MaydaLabs web sitesini kullanma ve proje çalışmaları için stüdyoyla iletişime geçme koşulları." }, kicker: "Yasal / Web sitesi koşulları", heading: ["Açık koşullar.", "Gerçek anlaşmalar."], introduction: "Bu koşullar herkese açık web sitesini düzenler. Gerçek müşteri çalışmaları ayrı yazılı proje sözleşmesine tabidir.", updated: "Son güncelleme · 22 Temmuz 2026", documentTitle: "Web sitesi koşulları", contactTitle: "İletişim", contactCopy: "Bu koşullar hakkındaki sorularınızı şu adrese gönderebilirsiniz:", contactLink: "Projeyi konuşalım", sections: [
    { number: "01", title: "Web sitesinin kullanımı", paragraphs: ["Bu siteyi yasal amaçlarla inceleyebilir ve bağlantılarını paylaşabilirsiniz. Siteyi bozmaya, yetkisiz erişim sağlamaya, zararlı veri toplamaya veya MaydaLabs ve çalışmalarını yanlış tanıtmaya çalışmayın."] },
    { number: "02", title: "Bilgi, garanti değil", paragraphs: ["Site MaydaLabs yetkinliklerini, seçili projeleri ve bakış açılarını anlatır. Hukuki, mali, vergisel veya düzenlemeye tabi profesyonel tavsiye değildir.", "Proje örnekleri başka bir projenin aynı sonucu, süreyi veya ticari çıktıyı üreteceğini garanti etmez."] },
    { number: "03", title: "Proje çalışmaları", paragraphs: ["Proje görüşmesi, e-posta, teklif veya tahmin tek başına müşteri ilişkisi oluşturmaz. Kapsam, ücret, sahiplik, gizlilik, sorumluluklar ve teslimat koşulları her çalışma için ayrıca yazılı olarak kararlaştırılır."] },
    { number: "04", title: "Çalışma ve fikri mülkiyet", paragraphs: ["MaydaLabs adı, site tasarımı, yazılar, grafikler ve özgün materyaller izin olmadan yeniden yayınlanamaz veya başka bir tarafın çalışması gibi sunulamaz.", "Müşteri ve amiral ürün adları, ekran görüntüleri ve markalar ilgili sahiplerine aittir. Proje sahipliği geçerli sözleşmeyle düzenlenir."] },
    { number: "05", title: "Erişilebilirlik ve dış hizmetler", paragraphs: ["Siteyi doğru ve erişilebilir tutmayı amaçlarız; ancak site değişebilir, hata içerebilir veya kesintiye uğrayabilir. MaydaLabs dış hizmetlerin erişilebilirliğini, içeriğini veya koşullarını kontrol etmez."] },
    { number: "06", title: "Güncellemeler", paragraphs: ["Site ve stüdyo geliştikçe bu koşullar değişebilir. Güncel sürüm revizyon tarihiyle burada yayınlanır."] },
  ] },
  fr: { meta: { title: "Conditions du site", socialTitle: "Conditions du site · MaydaLabs", description: "Conditions claires pour utiliser le site MaydaLabs et contacter le studio au sujet d’un projet." }, kicker: "Juridique / Conditions du site", heading: ["Des règles claires.", "De vrais accords."], introduction: "Ces conditions encadrent le site public. Le travail client est régi par un accord de projet écrit séparé.", updated: "Dernière mise à jour · 22 juillet 2026", documentTitle: "Conditions du site", contactTitle: "Contact", contactCopy: "Les questions concernant ces conditions peuvent être envoyées à", contactLink: "Discuter d’un projet", sections: [
    { number: "01", title: "Utilisation du site", paragraphs: ["Vous pouvez consulter et partager les liens du site à des fins légales. Ne perturbez pas le site, ne tentez pas d’accès non autorisé, ne nuisez pas à sa disponibilité et ne présentez pas faussement MaydaLabs ou son travail."] },
    { number: "02", title: "Information, pas promesse", paragraphs: ["Le site décrit les compétences, projets et points de vue de MaydaLabs. Il ne constitue pas un conseil juridique, financier, fiscal ou réglementé.", "Les exemples ne garantissent pas le même résultat, calendrier ou impact commercial pour un autre projet."] },
    { number: "03", title: "Missions client", paragraphs: ["Un appel, e-mail, devis ou proposition ne crée pas à lui seul une relation client. Périmètre, honoraires, propriété, confidentialité, responsabilités et livraison sont convenus séparément par écrit."] },
    { number: "04", title: "Travail et propriété intellectuelle", paragraphs: ["Le nom MaydaLabs, le design du site, les textes, graphiques et matériaux originaux ne peuvent être republiés ou présentés comme le travail d’un tiers sans autorisation.", "Les noms, captures et marques des clients et produits phares appartiennent à leurs propriétaires. La propriété des livrables dépend de l’accord applicable."] },
    { number: "05", title: "Disponibilité et services externes", paragraphs: ["Nous visons un site exact et disponible, mais il peut changer, contenir des erreurs ou être interrompu. MaydaLabs ne contrôle pas la disponibilité, le contenu ou les conditions des services externes."] },
    { number: "06", title: "Mises à jour", paragraphs: ["Ces conditions peuvent évoluer avec le site et le studio. La version actuelle sera publiée ici avec sa date de révision."] },
  ] },
} as const;

export async function generateMetadata({ params }: LocalePageProps) { const locale = await getPageLocale(params); return createPageMetadata({ ...COPY[locale].meta, path: "/terms", locale, socialCard: "legal" }); }
export default async function TermsPage({ params }: LocalePageProps) { const locale = await getPageLocale(params); const copy = COPY[locale]; return <LegalDocument locale={locale} kicker={copy.kicker} heading={copy.heading} introduction={copy.introduction} updated={copy.updated} documentId="Document / ML-T01" documentTitle={copy.documentTitle} sections={copy.sections} contactNumber="07" contactTitle={copy.contactTitle} contactCopy={copy.contactCopy} contactLink={copy.contactLink} />; }
